'use strict';
(()=>{
const q=new URLSearchParams(location.search);
const signoffMode=['goal3signofftest','goal3freshbenchmark','goal3multisoak','goal3diversity'].some(k=>q.has(k));
const otherGate=['selftest','goal3test','goal3mobiletest','goal3soak','goal3progressiontest','goal3progressionsoak','goal3loadoutuitest','goal3skillsoak'].some(k=>q.has(k));
if(otherGate&&!signoffMode)return;
const api=window.DopamineSkills,p=window.DopamineSkillProgression;
if(!api||!p?.progress)return;
const VERSION='Goal 03 Signoff v1.3',KEY='dopamineSkillSignoffV13',PROGKEY='dopamineSkillProgressionV12',BACKUP='dopamineSkillProgressionBackupV12';
const ids=api.ids();
const MASTERIES={
 Slash:[['5','Cleave','Slash hits a nearby enemy.'],['10','Execution','Massive damage against wounded enemies.'],['20','Ravager','Executions release a brutal cleave wave.']],
 Firebolt:[['5','Ignite','Firebolt burns its target.'],['10','Ember Splash','Impact splashes to another enemy.'],['20','Solar Fork','Impact forks into two extra embers.']],
 Whirlwind:[['5','Momentum','Consecutive hits ramp damage.'],['10','Bloodwind','Whirlwind restores life on hit.'],['20','Tempest','Momentum periodically releases a cyclone pulse.']],
 Dash:[['5','Impact','Long Vault Strikes hit harder.'],['10','Second Wind','Vault Strike restores life.'],['20','Meteor Step','Landing releases a damaging shock ring.']],
 Slam:[['5','Stagger','Ground Slam slows survivors.'],['10','Aftershock','The impact echoes for bonus damage.'],['20','Fault Line','A delayed second quake hits the landing zone.']],
 Scorch:[['5','Heat','Repeated ticks amplify damage.'],['10','Cinder Grip','Scorch Field slows enemies.'],['20','Wildfire','Inferno heat leaps to nearby enemies.']],
 Wisp:[['5','Chain Ember','Wisp bolts chain to another enemy.'],['10','Warmth','Wisp damage restores life.'],['20','Twin Spark','Wisp chains to two targets with stronger sustain.']]
};
const ROLE={Slash:'melee',Whirlwind:'melee',Slam:'control',Firebolt:'ranged',Dash:'movement',Scorch:'control',Wisp:'summon'};
const CAST_HINT={single:'Casts when its target is in range.',aoe:'Waits for an efficient cluster, then flex-casts if held too long.',utility:'Maintains the effect when its current utility actor expires.'};
const baseState=()=>({schema:13,history:[],stats:{casts:{},damage:{},hits:{},kills:{}},kills:0,dry:0,bandDry:{},selected:null,lastMigration:null});
let state=baseState();
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);if(x&&x.schema===13)state={...baseState(),...x,stats:{...baseState().stats,...(x.stats||{})}}}if(!localStorage.getItem(BACKUP)&&localStorage.getItem(PROGKEY)){localStorage.setItem(BACKUP,localStorage.getItem(PROGKEY));state.lastMigration='v12-backed-up';save()}}catch(e){}}
function save(){if(signoffMode)return;try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
load();
function def(id){return api.get(id)}
function lv(id){return p.level(id)||0}
function eff(id){return p.effective(id)||{}}
function ml(e){return Math.max(1,(depth|0)+(e?.type==='elite'?1:e?.type==='boss'?3:0))}
function stat(id,k){state.stats[k][id]=(state.stats[k][id]||0)+1}
function addDamage(id,a){state.stats.damage[id]=(state.stats.damage[id]||0)+Math.max(0,a||0);state.stats.hits[id]=(state.stats.hits[id]||0)+1}
function sourceId(k){if(!k)return null;const s=String(k);return ids.find(id=>s===id||s===def(id).name||s.startsWith(def(id).name.split(' ')[0])||({Burn:'Firebolt','Firebolt Ember':'Firebolt','Slash Cleave':'Slash','Slam Aftershock':'Slam','Wisp Chain':'Wisp'}[s]===id))||null}
function medianOwned(){const a=ids.filter(id=>p.isOwned(id)).map(lv).sort((a,b)=>a-b);return a.length?a[Math.floor(a.length/2)]:1}
function eligibleLocked(level){return ids.filter(id=>!p.isOwned(id)&&p.unlockDepth(id)<=level).sort((a,b)=>p.unlockDepth(a)-p.unlockDepth(b))}
function quality(last){if(!last)return{label:'SKILL DROP',cls:'common'};const cap=p.capForMonster(last.monsterLevel),delta=last.level-cap;if(delta>=2||last.level>=20)return{label:'GOD ROLL',cls:'god'};if(delta>=1)return{label:'EPIC DROP',cls:'epic'};if(last.level>=cap)return{label:'RARE DROP',cls:'rare'};return{label:'SKILL DROP',cls:'common'}}
function snapshot(){const r={};for(const id of ids){const s=eff(id);r[id]={owned:p.isOwned(id),level:lv(id),baseDamage:+(s.baseDamage||0),cooldown:+(s.cooldown||0),area:+(s.area||0),range:+(s.range||0),duration:+(s.duration||0)}}return r}
let beforeStats=snapshot(),lastDropCount=p.progress().drops||0;
function historyPush(last,kind='drop'){if(!last)return;const ql=quality(last);state.history.unshift({t:Date.now(),room:typeof depth==='number'?depth:1,id:last.id,level:last.level,monsterLevel:last.monsterLevel,quality:ql.label,kind});state.history=state.history.slice(0,24);save()}
function ensureCss(){if(document.getElementById('g3signoffCss'))return;const st=document.createElement('style');st.id='g3signoffCss';st.textContent=`
#g3worldloot{position:fixed;inset:0;z-index:27;pointer-events:none}.g3drop{position:absolute;transform:translate(-50%,-50%);text-align:center;font:900 9px system-ui;transition:left .5s cubic-bezier(.2,.8,.2,1),top .5s cubic-bezier(.2,.8,.2,1),opacity .3s,transform .5s}.g3drop i{display:block;width:8px;height:42px;margin:auto;background:linear-gradient(180deg,#fff0, currentColor);filter:drop-shadow(0 0 7px currentColor)}.g3drop b{display:block;background:#07111ee8;border:1px solid currentColor;border-radius:8px;padding:4px 7px;box-shadow:0 5px 18px #000a}.g3drop.collect{transform:translate(-50%,-50%) scale(.35);opacity:.15}.g3drop.common{color:#b8d0eb}.g3drop.rare{color:#7ee2ff}.g3drop.epic{color:#d49cff}.g3drop.god{color:#ffd56a;text-shadow:0 0 8px #ffb300}
#g3compare{position:fixed;left:50%;top:11%;z-index:31;transform:translate(-50%,-14px);opacity:0;pointer-events:none;width:min(470px,90vw);background:#091322f5;border:1px solid #617da5;border-radius:13px;padding:10px 12px;box-shadow:0 10px 30px #000b;color:#eef5ff;font:800 10px system-ui;transition:.18s}#g3compare.show{opacity:1;transform:translate(-50%,0)}#g3compare b{font-size:13px}#g3compare .delta{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:7px}#g3compare .delta span{background:#0e2033;border-radius:7px;padding:6px;text-align:center}#g3compare em{font-style:normal;color:#8ff0b4}
#g3castbar{position:fixed;left:50%;bottom:82px;transform:translateX(-50%);width:min(300px,68vw);height:7px;z-index:24;border:1px solid #6c8cae;border-radius:99px;background:#07111e;overflow:hidden;opacity:0;transition:opacity .1s}#g3castbar.show{opacity:1}#g3castbar i{display:block;height:100%;width:0;background:linear-gradient(90deg,#71d4ff,#d49cff);border-radius:99px}
.skill .g3radial{position:absolute;inset:3px;border-radius:10px;pointer-events:none;background:conic-gradient(#0009 var(--g3cd,0%),transparent 0);mix-blend-mode:multiply}.skill{position:relative}.g3masteries{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin:8px 0}.g3mastery{border:1px solid #394e6b;border-radius:7px;padding:5px;font-size:8px;line-height:1.25}.g3mastery.on{border-color:#80e9a7;background:#0d261d}.g3brainhint{font-size:8px;line-height:1.3;opacity:.72;margin:6px 0}.g3selectskill{width:100%;min-height:36px;margin-top:6px}.g3selectskill.active{outline:2px solid #d49cff}.g3slot.g3target{outline:2px dashed #d49cff;cursor:pointer}.g3slot.flash{animation:g3flash .45s ease}@keyframes g3flash{50%{box-shadow:0 0 0 3px #8fe8ff88 inset}}
#g3presetbar{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin:8px 0}#g3presetbar button{min-height:38px;font-size:8px}.g3buildwarn{border:1px solid #7f5e35;background:#251b10;border-radius:8px;padding:7px;margin:7px 0;font-size:9px}.g3buildwarn.good{border-color:#315c4b;background:#0c201a}.g3history{margin-top:10px;border-top:1px solid #2b3e59;padding-top:8px}.g3history h4{margin:0 0 6px}.g3historyrow{display:grid;grid-template-columns:1fr auto auto;gap:6px;font-size:8px;padding:4px 0;border-bottom:1px solid #1f2b3e}.g3collection{font-size:9px;padding:7px 9px;border-radius:8px;background:#0b1b2a;margin-bottom:7px}.g3collection b{font-size:11px}.g3stats{font-size:8px;opacity:.8;margin-top:5px}.g3under{color:#ffbd73}.g3cap{color:#ffd56a;font-weight:900}.g3drop.god b{animation:g3god .7s ease-in-out 2}@keyframes g3god{50%{transform:scale(1.08);filter:brightness(1.4)}}
@media(max-width:520px){#g3presetbar{grid-template-columns:1fr 1fr}.g3masteries{grid-template-columns:1fr}.g3drop b{font-size:8px}#g3compare .delta{grid-template-columns:1fr}}
`;document.head.appendChild(st);const world=document.createElement('div');world.id='g3worldloot';document.body.appendChild(world);const cmp=document.createElement('div');cmp.id='g3compare';document.body.appendChild(cmp);const cast=document.createElement('div');cast.id='g3castbar';cast.innerHTML='<i></i>';document.body.appendChild(cast)}
ensureCss();
let compareTimer=0;
function showCompare(id,prev,last){const box=document.getElementById('g3compare');if(!box||!id)return;const now=eff(id),d=def(id),qv=quality(last),rows=[];if(prev?.owned){rows.push(`<span>DMG<br>${prev.baseDamage.toFixed(0)} → <em>${(now.baseDamage||0).toFixed(0)}</em></span>`);rows.push(`<span>CD<br>${prev.cooldown.toFixed(2)}s → <em>${(now.cooldown||0).toFixed(2)}s</em></span>`);const pk=now.area?'AREA':now.range?'RANGE':'LEVEL',pv=now.area||now.range||prev.level,nv=now.area||now.range||lv(id);rows.push(`<span>${pk}<br>${(+pv).toFixed(pk==='LEVEL'?0:0)} → <em>${(+nv).toFixed(pk==='LEVEL'?0:0)}</em></span>`)}else rows.push(`<span>NEW SKILL<br><em>LEVEL ${lv(id)}</em></span>`);box.innerHTML=`<b>${qv.label} • ${d.name}</b><div>${prev?.owned?`Level ${prev.level} → ${lv(id)}`:`Discovered from monster level ${last?.monsterLevel||1}`}</div><div class="delta">${rows.join('')}</div>`;box.classList.add('show');clearTimeout(compareTimer);compareTimer=setTimeout(()=>box.classList.remove('show'),2800)}
function canvasPoint(x,y){const c=document.querySelector('canvas'),r=c?.getBoundingClientRect();if(!r)return{x:innerWidth/2,y:innerHeight/2};const iw=typeof W==='number'?W:r.width,ih=typeof H==='number'?H:r.height;return{x:r.left+x/iw*r.width,y:r.top+y/ih*r.height}}
function worldDrop(e,last){const root=document.getElementById('g3worldloot');if(!root||!last)return;const pt=canvasPoint(e?.x||((typeof W==='number'?W:innerWidth)/2),e?.y||((typeof H==='number'?H:innerHeight)/2)),qv=quality(last),el=document.createElement('div');el.className=`g3drop ${qv.cls}`;el.style.left=pt.x+'px';el.style.top=pt.y+'px';el.innerHTML=`<i></i><b>${qv.label}<br>${def(last.id).name} • LV ${last.level}</b>`;root.appendChild(el);setTimeout(()=>{const chip=document.getElementById('skillProgressChip')?.getBoundingClientRect();if(chip){el.classList.add('collect');el.style.left=(chip.left+chip.width/2)+'px';el.style.top=(chip.top+chip.height/2)+'px'}},620);setTimeout(()=>el.remove(),1250)}
let audio=null;function audioReady(){if(audio)return;try{audio=new (window.AudioContext||window.webkitAudioContext)()}catch(e){}}document.addEventListener('pointerdown',audioReady,{once:true});
function cue(delivery){if(!audio||audio.state!=='running')return;const f={melee_arc:190,spin:260,slam:120,projectile:430,dash_strike:520,ground_dot:150,summon:620}[delivery]||300;try{const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type=delivery==='slam'?'square':'sine';g.gain.setValueAtTime(.018,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.07);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.075)}catch(e){}}
function vfx(id){const d=def(id),delivery=d?.delivery;if(!d)return;try{if(delivery==='melee_arc')burst(P.x+Math.cos(P.facing||0)*24,P.y+Math.sin(P.facing||0)*24,d.color||'#d9efff',3);else if(delivery==='spin')ring(P.x,P.y,d.area||70,'#72d9ff',3);else if(delivery==='slam')ring(P.x,P.y,34,'#ffc056',4);else if(delivery==='projectile')ring(P.x,P.y,18,'#ff7b42',2);else if(delivery==='dash_strike')burst(P.x,P.y,'#82e8ff',5);else if(delivery==='ground_dot')ring(P.x,P.y,28,'#ff5c36',3);else if(delivery==='summon')ring(P.x,P.y,28,'#ffd66a',4)}catch(e){}cue(delivery)}
function recordDrop(last,entity,prev){if(!last)return;historyPush(last);worldDrop(entity,last);showCompare(last.id,prev?.[last.id],last);beforeStats=snapshot();state.dry=0;save()}
function adaptivePacing(e,prevProg,prevOwned){if(!e?.dead)return;const level=ml(e),after=p.progress(),dropped=(after.drops||0)>(prevProg.drops||0);if(dropped)state.dry=0;else state.dry++;
 const locked=eligibleLocked(level),boss=e.type==='boss';
 if(boss&&locked.length){const last=after.lastDrop,wasUseful=last&&!prevOwned[last.id];if(!wasUseful){const id=locked[0],target=Math.min(p.capForMonster(level),Math.max(1,medianOwned()-2));const pre=snapshot(),r=p.grantDrop(id,target,level);if(r?.accepted){recordDrop(p.progress().lastDrop,e,pre);return}}}
 if(!dropped&&locked.length){const band=locked[0],bandKey=String(p.unlockDepth(band));state.bandDry[bandKey]=(state.bandDry[bandKey]||0)+1;const threshold=level<5?3:level<12?4:5;if(state.bandDry[bandKey]>=threshold||state.dry>=7){const target=Math.min(p.capForMonster(level),Math.max(1,medianOwned()-2)),pre=snapshot(),r=p.grantDrop(band,target,level);state.bandDry[bandKey]=0;if(r?.accepted){recordDrop(p.progress().lastDrop,e,pre);return}}}
 if(dropped){const last=p.progress().lastDrop;if(last&&!prevOwned[last.id]){const current=lv(last.id),target=Math.min(p.capForMonster(level),Math.max(current,medianOwned()-2));if(target>current){const pre=snapshot(),r=p.grantDrop(last.id,target,level);if(r?.accepted)recordDrop(p.progress().lastDrop,e,pre)}}}
 save()}
const oldKill=typeof kill==='function'?kill:null;if(oldKill)kill=function(e){const prog=p.progress(),ownedBefore=Object.fromEntries(ids.map(id=>[id,p.isOwned(id)])),pre=snapshot(),wasDead=e?.dead;oldKill(e);if(e&&!wasDead&&e.dead){state.kills++;const after=p.progress();if((after.drops||0)>(prog.drops||0))recordDrop(after.lastDrop,e,pre);adaptivePacing(e,prog,ownedBefore);save()}};
const oldCast=typeof castSkill==='function'?castSkill:null;if(oldCast)castSkill=function(id,t,forced=false,fromCombo=false){const ok=oldCast(id,t,forced,fromCombo);if(ok&&id){stat(id,'casts');vfx(id);save()}return ok};
const oldHit=typeof hit==='function'?hit:null;let whirlCap=0,lastSlamCap=-99;const echoes=[];if(oldHit)hit=function(e,a,k,crit=false,kb=0){const id=sourceId(k),alive=e&&!e.dead;oldHit(e,a,k,crit,kb);if(id)addDamage(id,a);if(!alive||!id)return;const level=lv(id);if(level<20)return;
 if(id==='Slash'&&e.hp/e.max<=.22){for(const n of nearest(e,2,95))oldHit(n,a*.28,'Ravager Wave',false,3);try{ring(e.x,e.y,70,'#d9efff',3)}catch(x){}}
 else if(id==='Firebolt'){for(const n of nearest(e,2,120))oldHit(n,a*.24,'Solar Fork',false,0);try{burst(e.x,e.y,'#ff9a5f',5)}catch(x){}}
 else if(id==='Whirlwind'){whirlCap++;if(whirlCap%5===0){for(const n of enemiesNearPlayer(92))oldHit(n,a*.22,'Tempest Pulse',false,2);try{ring(P.x,P.y,92,'#72d9ff',3)}catch(x){}}}
 else if(id==='Slam'&&roomClock-lastSlamCap>.25){lastSlamCap=roomClock;echoes.push({x:P.x,y:P.y,left:.42,damage:a*.32});}
 else if(id==='Scorch'){const n=nearest(e,1,115)[0];if(n)oldHit(n,a*.22,'Wildfire',false,0)}
 else if(id==='Wisp'){const ns=nearest(e,2,135);ns.forEach(n=>oldHit(n,a*.25,'Twin Spark',false,0));try{ring(e.x,e.y,35,'#ffd66a',2)}catch(x){}}
 save()};
function nearest(e,count,r){return en.filter(x=>!x.dead&&x!==e).map(x=>[x,Math.hypot(x.x-e.x,x.y-e.y)]).filter(x=>x[1]<=r).sort((a,b)=>a[1]-b[1]).slice(0,count).map(x=>x[0])}
function enemiesNearPlayer(r){return en.filter(x=>!x.dead&&Math.hypot(x.x-P.x,x.y-P.y)<=r)}
const oldCast2=castSkill;castSkill=function(id,t,forced=false,fromCombo=false){const ok=oldCast2(id,t,forced,fromCombo);if(ok&&id==='Dash'&&lv('Dash')>=20){try{ring(P.x,P.y,88,'#82e8ff',5)}catch(e){}for(const n of enemiesNearPlayer(88))oldHit(n,(def('Dash').baseDamage||60)*.34,'Meteor Step',false,8);try{heal(8)}catch(e){}}return ok};
const oldStep=typeof step==='function'?step:null;if(oldStep)step=function(dt){for(let i=echoes.length-1;i>=0;i--){const e=echoes[i];e.left-=dt;if(e.left<=0){try{ring(e.x,e.y,115,'#ffc056',5)}catch(x){}for(const n of en)if(!n.dead&&Math.hypot(n.x-e.x,n.y-e.y)<=115+(n.r||0))oldHit(n,e.damage,'Fault Line',false,12);echoes.splice(i,1)}}oldStep(dt)};
let roomStart=null;const oldBegin=typeof beginRoom==='function'?beginRoom:null;if(oldBegin)beginRoom=function(){roomStart={casts:{...state.stats.casts},damage:{...state.stats.damage},time:performance.now()};beforeStats=snapshot();return oldBegin()};
function ensureRadials(){if(typeof skillEls==='undefined')return;[skillEls.Slash,skillEls.Whirlwind,skillEls.Slam].forEach(el=>{if(el&&!el.querySelector('.g3radial')){const r=document.createElement('div');r.className='g3radial';el.appendChild(r)}})}
let castDecision='',castStarted=0,castDuration=.2;
function hudPolish(){ensureRadials();if(typeof skillEls!=='undefined'){const cards=[skillEls.Slash,skillEls.Whirlwind,skillEls.Slam],load=p.loadout();cards.forEach((el,i)=>{const id=load[i];if(!el||!id)return;const txt=el.querySelector('.cd')?.textContent||'',m=txt.match(/^([0-9.]+)s/),rem=m?+m[1]:0,total=Math.max(.01,def(id).cooldown||1),pct=Math.max(0,Math.min(100,rem/total*100));el.style.setProperty('--g3cd',pct+'%')})}
 const d=String(typeof lastDecision!=='undefined'?lastDecision:'');const bar=document.getElementById('g3castbar'),fill=bar?.querySelector('i');if(d.startsWith('CASTING ')){if(d!==castDecision){castDecision=d;castStarted=performance.now();const name=d.slice(8).trim().toLowerCase(),id=ids.find(x=>def(x).name.toLowerCase()===name)||ids.find(x=>name.includes(def(x).name.toLowerCase()));castDuration=Math.max(.08,def(id)?.castTime||.2)}const pct=Math.min(100,(performance.now()-castStarted)/(castDuration*1000)*100);if(bar){bar.classList.add('show');fill.style.width=pct+'%'}}else if(bar){bar.classList.remove('show');castDecision=''}
 decorateLab();}
const oldHud=typeof hud==='function'?hud:null;if(oldHud)hud=function(){oldHud();hudPolish()};
function roleKey(id){return ROLE[id]||def(id)?.delivery||'other'}
function buildWarnings(){const load=p.loadout().filter(Boolean),w=[];if(load.length<3)w.push(`${3-load.length} priority slot${load.length===2?'':'s'} empty.`);const roles=load.map(roleKey);for(const r of new Set(roles))if(roles.filter(x=>x===r).length>=2&&['melee','control'].includes(r))w.push(`Role overlap: ${roles.filter(x=>x===r).length} ${r} skills may compete for the same Brain window.`);if(load.length===3&&load.every(id=>(def(id).cooldown||0)>=3))w.push('All three skills have long cooldowns; add a frequent attack for smoother pressure.');const direct=load.some(id=>['Slash','Firebolt','Dash'].includes(id));if(load.length===3&&!direct)w.push('No frequent single-target finisher equipped.');return w}
function statsLine(id){const c=state.stats.casts[id]||0,d=state.stats.damage[id]||0;return `${c} casts • ${Math.round(d)} tracked damage`}
function preset(kind){const owned=api.ownedIds();const score=id=>{const r=roleKey(id);if(kind==='melee')return r==='melee'?5:id==='Dash'?4:id==='Slam'?3:1;if(kind==='ranged')return id==='Firebolt'?6:id==='Wisp'?5:id==='Scorch'?4:id==='Dash'?2:1;if(kind==='control')return id==='Scorch'?6:id==='Slam'?5:id==='Whirlwind'?4:id==='Firebolt'?2:1;if(kind==='summon')return id==='Wisp'?7:id==='Firebolt'?5:id==='Dash'?4:id==='Scorch'?3:1;return 1};const pick=[...owned].sort((a,b)=>score(b)-score(a)).slice(0,3);[0,1,2].forEach(i=>p.equip(pick[i]||null,i));decorateLab(true)}
function decorateLab(force=false){const panel=document.getElementById('skillLabPanel');if(!panel)return;const card=panel.querySelector('.g3card'),grid=panel.querySelector('#g3skills');if(!card||!grid)return;
 let collection=card.querySelector('.g3collection');if(!collection){collection=document.createElement('div');collection.className='g3collection';const tags=card.querySelector('.g3tags');tags?.after(collection)}const owned=api.ownedIds(),next=api.nextUnlock?.();collection.innerHTML=`<b>COLLECTION ${owned.length}/${ids.length}</b> • ${owned.length===ids.length?'Complete current catalog':`Next discovery around monster level ${next?.monsterLevel||'?'}`}<br><span>Skill saves use schema v13 with an automatic v12 backup for future migration safety.</span>`;
 let presets=card.querySelector('#g3presetbar');if(!presets){presets=document.createElement('div');presets.id='g3presetbar';presets.innerHTML=['melee','ranged','control','summon'].map(x=>`<button data-g3preset="${x}">${x.toUpperCase()}</button>`).join('');collection.after(presets);presets.querySelectorAll('[data-g3preset]').forEach(b=>b.onclick=()=>preset(b.dataset.g3preset))}
 let warn=card.querySelector('.g3buildwarn');if(!warn){warn=document.createElement('div');warn.className='g3buildwarn';presets.after(warn)}const ws=buildWarnings();warn.classList.toggle('good',!ws.length);warn.innerHTML=ws.length?`<b>BUILD CHECK</b><br>${ws.join('<br>')}`:'<b>BUILD CHECK ✓</b> Loadout has healthy role/cooldown coverage.';
 const load=p.loadout();[...card.querySelectorAll('.g3slot')].forEach((s,i)=>{s.dataset.g3slot=i;s.draggable=true;s.classList.toggle('g3target',!!state.selected);s.ondragstart=ev=>ev.dataTransfer.setData('text/g3slot',String(i));s.ondragover=ev=>ev.preventDefault();s.ondrop=ev=>{ev.preventDefault();const from=+ev.dataTransfer.getData('text/g3slot'),id=load[from];if(id)p.equip(id,i);decorateLab(true)};s.onclick=ev=>{if(ev.target.closest('button'))return;if(state.selected){p.equip(state.selected,i);state.selected=null;save();s.classList.add('flash');setTimeout(()=>s.classList.remove('flash'),450);decorateLab(true)}}});
 for(const skill of card.querySelectorAll('.g3skill')){const name=skill.querySelector('h3')?.textContent,id=ids.find(x=>def(x).name===name);if(!id)continue;let hint=skill.querySelector('.g3brainhint');if(!hint){hint=document.createElement('div');hint.className='g3brainhint';skill.querySelector('.g3meta')?.after(hint)}hint.innerHTML=`<b>BRAIN:</b> ${CAST_HINT[def(id).brain?.kind]||'Uses the skill when its runtime conditions are satisfied.'}<br><span class="g3stats">${statsLine(id)}</span>`;
 let ms=skill.querySelector('.g3masteries');if(!ms){ms=document.createElement('div');ms.className='g3masteries';hint.after(ms)}ms.innerHTML=MASTERIES[id].map(([l,n,d])=>`<div class="g3mastery ${lv(id)>=+l?'on':''}"><b>LV ${l} • ${n}</b><br>${d}</div>`).join('');
 if(p.isOwned(id)){let sel=skill.querySelector('.g3selectskill');if(!sel){sel=document.createElement('button');sel.className='g3selectskill';ms.after(sel)}sel.textContent=state.selected===id?'SELECTED — TAP PRIORITY SLOT':'SELECT → PRIORITY SLOT';sel.classList.toggle('active',state.selected===id);sel.onclick=()=>{state.selected=state.selected===id?null:id;save();decorateLab(true)}}
 }
 let hist=card.querySelector('.g3history');if(!hist){hist=document.createElement('div');hist.className='g3history';card.querySelector('.g3foot')?.before(hist)}hist.innerHTML=`<h4>RECENT SKILL DROPS</h4>${state.history.length?state.history.slice(0,8).map(h=>`<div class="g3historyrow"><span>${def(h.id)?.name||h.id}</span><b>Lv ${h.level}</b><span>${h.quality}</span></div>`).join(''):'<div class="g3historyrow"><span>No drops recorded yet</span><b>—</b><span>—</span></div>'}`;
}
const observer=new MutationObserver(()=>{if(document.getElementById('skillLabPanel')?.style.display==='block')requestAnimationFrame(()=>decorateLab())});observer.observe(document.body,{childList:true,subtree:true});
const oldFinish=typeof finish==='function'?finish:null;if(oldFinish)finish=function(win){oldFinish(win);if(!statsEl||!roomStart)return;const load=p.loadout().filter(Boolean),rows=load.map(id=>({id,casts:(state.stats.casts[id]||0)-(roomStart.casts[id]||0),damage:(state.stats.damage[id]||0)-(roomStart.damage[id]||0)})).sort((a,b)=>b.damage-a.damage),under=rows.filter(x=>x.casts===0).map(x=>def(x.id).name);const overlap=buildWarnings();statsEl.textContent=`Skill performance    ${rows.map((x,i)=>`${i+1}. ${def(x.id).name} ${x.casts} casts / ${Math.round(x.damage)} dmg`).join(' • ')}\n${under.length?`Underused warning     ${under.join(', ')} had 0 casts\n`:''}${overlap.length?`Loadout note          ${overlap.join(' | ')}\n`:''}`+statsEl.textContent};
function resetSignoff(){state=baseState();beforeStats=snapshot();lastDropCount=p.progress().drops||0;save();decorateLab(true)}
window.DopamineSkillSignoff={version:VERSION,state:()=>JSON.parse(JSON.stringify(state)),masteries:MASTERIES,quality,buildWarnings,preset,decorate:decorateLab,reset:resetSignoff,saveSchema:13,backupKey:BACKUP};
hudPolish();decorateLab();
})();
