'use strict';
(()=>{
const q=new URLSearchParams(location.search),mode=q.has('goal3signofftest')?'test':q.has('goal3freshbenchmark')?'fresh':q.has('goal3diversity')?'diversity':q.has('goal3multisoak')?'multi':null;if(!mode)return;
const p=window.DopamineSkillProgression,s=window.DopamineSkillSignoff,ids=DopamineSkills.ids();if(!p||!s)return;
function report(id,rows,obj){active=false;pausedForBrain=true;document.body.innerHTML=`<pre id="${id}" style="white-space:pre-wrap;background:#07101a;color:#eaf3ff;padding:18px;font:13px/1.5 ui-monospace,monospace">${rows.join('\n')}</pre>`;window[id]=obj}
function grantAll(level=10){p.reset();s.reset();for(const id of ids)if(id!=='Slash')p.grantDrop(id,level,30);p.grantDrop('Slash',level,30)}
function setLoad(load){brain.skills=[null,null,null];load.forEach((id,i)=>p.equip(id,i))}
function simRoom(seed,dep,limit=2600){baseSeed=seed>>>0;depth=dep;beginRoom();let steps=0;while(active&&steps<limit&&!runtimeErrors.length){step(.035);steps++}const live=en.filter(e=>!e.dead),casts=Object.fromEntries(ids.map(id=>[id,skillCasts[id]||0]));const stalled=active&&steps>=limit;if(stalled)active=false;return{steps,stalled,win:!P.dead&&!live.length,loss:P.dead||(!active&&live.length),clock:+roomClock.toFixed(2),live:live.length,casts}}
function castsNow(){return Object.fromEntries(ids.map(id=>[id,skillCasts[id]||0]))}
if(mode==='test'){
 grantAll(10);document.getElementById('skillLabBtn')?.click();s.decorate();
 const card=document.querySelector('.g3card'),masteries=document.querySelectorAll('.g3mastery').length===ids.length*3,capstones=ids.every(id=>s.masteries[id]?.some(x=>x[0]==='20')),collection=!!card?.querySelector('.g3collection'),presets=card?.querySelectorAll('#g3presetbar button').length===4,history=!!card?.querySelector('.g3history'),brainHints=card?.querySelectorAll('.g3brainhint').length===ids.length,selectButtons=card?.querySelectorAll('.g3selectskill').length===ids.length,radials=document.querySelectorAll('.g3radial').length===3,castbar=!!document.getElementById('g3castbar'),worldLoot=!!document.getElementById('g3worldloot'),compare=!!document.getElementById('g3compare'),schema=s.saveSchema===13;
 s.preset('ranged');const ranged=p.loadout().includes('Firebolt')&&p.loadout().includes('Wisp');s.preset('control');const control=p.loadout().includes('Scorch')&&p.loadout().includes('Slam');const warnings=Array.isArray(s.buildWarnings());
 const ok=[masteries,capstones,collection,presets,history,brainHints,selectButtons,radials,castbar,worldLoot,compare,schema,ranged,control,warnings,runtimeErrors.length===0].every(Boolean);
 report('__DOPAMINE_SIGNOFF_TEST',[`GOAL3_SIGNOFF_TEST_OK=${ok}`,`MASTERY_TRACKS=${masteries}`,`LEVEL20_CAPSTONES=${capstones}`,`COLLECTION_VIEW=${collection}`,`SMART_PRESETS=${presets&&ranged&&control}`,`DROP_HISTORY=${history}`,`BRAIN_DESCRIPTIONS=${brainHints}`,`TAP_TO_SLOT=${selectButtons}`,`COOLDOWN_RADIALS=${radials}`,`CAST_BAR=${castbar}`,`WORLD_LOOT=${worldLoot}`,`UPGRADE_COMPARE=${compare}`,`SAVE_SCHEMA_V13=${schema}`,`BUILD_WARNINGS=${warnings}`,`ERRORS=${runtimeErrors.join('|')}`],{ok,masteries,capstones,collection,presets,history,brainHints,selectButtons,radials,castbar,worldLoot,compare,schema,ranged,control,warnings,errors:runtimeErrors});return;
}
if(mode==='fresh'){
 p.reset();s.reset();pausedForBrain=false;active=false;const originalSeed=baseSeed,startDrops=p.progress().drops;let sim=0,steps=0,rooms=0,stalls=0,lastDrops=startDrops,lastDropTime=0,maxDry=0,firstNew=null,fourSkills=null,firstMastery=null,allSkills=null,firstHigh=null;const unlockAt={Slash:0};
 while(sim<1800&&steps<70000&&!runtimeErrors.length){const dep=Math.min(22,1+Math.floor(sim/82));baseSeed=(originalSeed+Math.imul(rooms+1,6151))>>>0;depth=dep;const owned=DopamineSkills.ownedIds();setLoad(owned.slice(-3).reverse());const before=Object.fromEntries(ids.map(id=>[id,p.isOwned(id)]));beginRoom();let local=0,clockEnd=false;while(active&&local<2600&&!runtimeErrors.length){if(sim>=1800){clockEnd=true;break}step(.035);local++;steps++;sim+=.035;const pr=p.progress();if(pr.drops>lastDrops){maxDry=Math.max(maxDry,sim-lastDropTime);lastDropTime=sim;lastDrops=pr.drops;const last=pr.lastDrop;if(last&&s.quality(last).label!=='SKILL DROP'&&!firstHigh)firstHigh=sim}for(const id of ids)if(!before[id]&&p.isOwned(id)&&unlockAt[id]==null)unlockAt[id]=sim;if(!firstNew&&DopamineSkills.ownedIds().length>=2)firstNew=sim;if(!fourSkills&&DopamineSkills.ownedIds().length>=4)fourSkills=sim;if(!firstMastery&&ids.some(id=>p.level(id)>=5))firstMastery=sim;if(!allSkills&&DopamineSkills.ownedIds().length===ids.length)allSkills=sim}
 if(clockEnd&&active){active=false;break}if(active&&local>=2600){stalls++;active=false}rooms++}
 maxDry=Math.max(maxDry,sim-lastDropTime);baseSeed=originalSeed;const discoveries=DopamineSkills.ownedIds().length,pace=firstNew!=null&&firstNew<=180&&fourSkills!=null&&fourSkills<=750,mastery=firstMastery!=null&&firstMastery<=1100,collection=discoveries===ids.length||discoveries>=6,dry=maxDry<=260,high=firstHigh!=null,noStall=stalls===0,ok=pace&&mastery&&collection&&dry&&high&&noStall&&runtimeErrors.length===0;
 report('__DOPAMINE_FRESH_BENCHMARK',[`GOAL3_FRESH_BENCHMARK_OK=${ok}`,`SIM_SECONDS=${sim.toFixed(1)}`,`STEPS=${steps}`,`ROOMS=${rooms}`,`STALLS=${stalls}`,`FIRST_NEW_SKILL=${firstNew?.toFixed(1)??'NONE'}`,`FOUR_SKILLS=${fourSkills?.toFixed(1)??'NONE'}`,`FIRST_MASTERY=${firstMastery?.toFixed(1)??'NONE'}`,`ALL_SKILLS=${allSkills?.toFixed(1)??'NONE'}`,`FIRST_HIGH_ROLL=${firstHigh?.toFixed(1)??'NONE'}`,`MAX_DROP_DRY_SECONDS=${maxDry.toFixed(1)}`,`DISCOVERED=${discoveries}/${ids.length}`,`UNLOCK_TIMES=${Object.entries(unlockAt).map(([k,v])=>k+':'+(+v).toFixed(0)).join(',')}`,`ERRORS=${runtimeErrors.join('|')}`],{ok,sim,steps,rooms,stalls,firstNew,fourSkills,firstMastery,allSkills,firstHigh,maxDry,discoveries,unlockAt,errors:runtimeErrors});return;
}
if(mode==='diversity'){
 grantAll(12);pausedForBrain=false;active=false;const originalSeed=baseSeed,builds={melee:['Slash','Whirlwind','Slam'],ranged:['Firebolt','Wisp','Dash'],control:['Scorch','Slam','Firebolt'],summon:['Wisp','Scorch','Dash'],movement:['Dash','Slash','Firebolt'],mixed:['Slash','Scorch','Wisp']},results={};let totalStalls=0;
 let bi=0;for(const [name,load] of Object.entries(builds)){setLoad(load);let wins=0,losses=0,stalls=0,steps=0;const casts=Object.fromEntries(load.map(id=>[id,0]));for(let r=0;r<24;r++){const res=simRoom((originalSeed+Math.imul(++bi,3571))>>>0,10+(r%15),2600);steps+=res.steps;if(res.stalled)stalls++;else if(res.win)wins++;else losses++;for(const id of load)casts[id]+=res.casts[id]||0}const castCoverage=load.every(id=>casts[id]>0),viable=wins>0&&stalls===0&&castCoverage;results[name]={viable,wins,losses,stalls,steps,casts};totalStalls+=stalls}
 baseSeed=originalSeed;const all=Object.values(results).every(x=>x.viable),ok=all&&totalStalls===0&&runtimeErrors.length===0;
 report('__DOPAMINE_DIVERSITY',[`GOAL3_DIVERSITY_OK=${ok}`,`BUILDS=${Object.keys(builds).length}`,`ALL_BUILDS_VIABLE=${all}`,`TOTAL_STALLS=${totalStalls}`,...Object.entries(results).map(([k,v])=>`${k.toUpperCase()}=${v.viable};W${v.wins};L${v.losses};S${v.stalls};CASTS=${Object.entries(v.casts).map(([i,n])=>i+':'+n).join(',')}`),`ERRORS=${runtimeErrors.join('|')}`],{ok,results,totalStalls,errors:runtimeErrors});return;
}
if(mode==='multi'){
 const seeds=[22994417,13371337,38118421],originalSeed=baseSeed,runs=[];let grandSteps=0;
 for(const seed0 of seeds){p.reset();s.reset();pausedForBrain=false;active=false;let sim=0,steps=0,rooms=0,wins=0,losses=0,stalls=0,truncated=0,firstNew=null,allUnlock=null,maxLevel=1;const casts=Object.fromEntries(ids.map(id=>[id,0]));while(sim<3600&&steps<155000&&!runtimeErrors.length){depth=1+(rooms%30);baseSeed=(seed0+Math.imul(rooms+1,7919))>>>0;const owned=DopamineSkills.ownedIds(),load=[];for(let j=0;j<Math.min(3,owned.length);j++)load.push(owned[(rooms+j)%owned.length]);setLoad(load);beginRoom();let local=0,clock=false;while(active&&local<2600&&!runtimeErrors.length){if(sim>=3600){clock=true;break}step(.035);local++;steps++;sim+=.035;if(!firstNew&&DopamineSkills.ownedIds().length>=2)firstNew=sim;if(!allUnlock&&DopamineSkills.ownedIds().length===ids.length)allUnlock=sim;for(const id of ids)maxLevel=Math.max(maxLevel,p.level(id))}for(const id of ids)casts[id]+=(skillCasts[id]||0);const live=en.filter(e=>!e.dead);if(clock&&active){truncated++;active=false;break}else if(active&&local>=2600){stalls++;active=false}else if(P.dead)losses++;else if(!live.length)wins++;else losses++;rooms++}const pr=p.progress(),castCoverage=ids.every(id=>casts[id]>0),allUnlocked=DopamineSkills.ownedIds().length===ids.length,pass=sim>=3599&&stalls===0&&castCoverage&&allUnlocked;grandSteps+=steps;runs.push({seed:seed0,pass,sim,steps,rooms,wins,losses,stalls,truncated,drops:pr.drops,upgrades:pr.upgrades,maxLevel,firstNew,allUnlock,castCoverage,allUnlocked})}
 baseSeed=originalSeed;const drops=runs.map(r=>r.drops),unlockTimes=runs.map(r=>r.allUnlock||3600),spread=Math.max(...drops)-Math.min(...drops),unlockSpread=Math.max(...unlockTimes)-Math.min(...unlockTimes),consistent=spread<=Math.max(90,Math.min(...drops)*.35)&&unlockSpread<=900,ok=runs.every(r=>r.pass)&&consistent&&runtimeErrors.length===0;
 report('__DOPAMINE_MULTI_SOAK',[`GOAL3_MULTI_SOAK_OK=${ok}`,`RUNS=${runs.length}`,`TOTAL_SIM_SECONDS=${runs.reduce((a,r)=>a+r.sim,0).toFixed(1)}`,`TOTAL_STEPS=${grandSteps}`,`CONSISTENT_PACING=${consistent}`,`DROP_SPREAD=${spread}`,`ALL_UNLOCK_SPREAD_SECONDS=${unlockSpread.toFixed(1)}`,...runs.map((r,i)=>`RUN${i+1}=seed:${r.seed};pass:${r.pass};sim:${r.sim.toFixed(1)};steps:${r.steps};wins:${r.wins};losses:${r.losses};stalls:${r.stalls};drops:${r.drops};upgrades:${r.upgrades};maxLv:${r.maxLevel};firstNew:${r.firstNew?.toFixed(1)};allUnlock:${r.allUnlock?.toFixed(1)}`),`ERRORS=${runtimeErrors.join('|')}`],{ok,runs,grandSteps,consistent,spread,unlockSpread,errors:runtimeErrors});
}
})();
