'use strict';
(()=>{
const q=new URLSearchParams(location.search),test=q.has('supporttest'),mobile=q.has('supportmobile'),soak=q.has('supportsoak');if(!test&&!mobile&&!soak)return;
const api=window.DopamineSkills,g4=window.DopamineGoal4,p=window.DopamineSkillProgression,sup=window.DopamineSupports,cat=window.DopamineSupportCatalog;if(!api||!g4||!p||!sup||!cat)return;
function report(id,rows,obj){active=false;pausedForBrain=true;document.body.innerHTML=`<pre id="${id}" style="white-space:pre-wrap;background:#07101a;color:#eaf3ff;padding:18px;font:13px/1.5 ui-monospace,monospace">${rows.join('\n')}</pre>`;window[id]=obj}
function fail(id,label,e){const msg=String(e?.stack||e?.message||e);report(id,[`${label}=false`,`EXCEPTION=${msg.replace(/\n/g,' | ')}`,`ERRORS=${(typeof runtimeErrors!=='undefined'?runtimeErrors:[]).join('|')}`],{ok:false,exception:msg})}
function unlockSkills(lv=16){p.reset();for(const id of ['Firebolt','Whirlwind','Dash','Slam','Scorch','Wisp'])p.grantDrop(id,lv,60);g4.debugUnlockAll(lv)}
const builds=[['Slash','Whirlwind','Slam'],['Firebolt','Dash','Scorch'],['Wisp','FrostLance','ChainLightning'],['Meteor','Orbit','ChainHook'],['ShieldCharge','BladeStorm','Riposte'],['FrostNova','FrozenOrb','Glacier'],['Thunderstep','StormTotem','BallLightning'],['VenomFang','PlagueBurst','AcidPool'],['ShadowKnives','Ricochet','Barrage'],['BoneGolem','RavenSwarm','GravityWell']];
if(test){try{
 unlockSkills();sup.reset();
 const ids=cat.ids(),names=ids.map(id=>cat.get(id).name),effectKeys=['mods','repeat','conversion','pattern','onKill','splash','chain','pierce','ignoreLos','pull','knockback','dot','execute','selfDamage','leech','healOnCast','needBonus'];
 const meaningful=ids.every(id=>effectKeys.some(k=>cat.get(id)[k]!==undefined&&cat.get(id)[k]!==false&&cat.get(id)[k]!==0)),catalog=ids.length===60&&new Set(ids).size===60&&new Set(names).size===60&&cat.categories.length>=6&&meaningful;
 const coverage=api.ids().every(id=>sup.compatibleCount(id)>=20),minCompatible=Math.min(...api.ids().map(id=>sup.compatibleCount(id)));
 const ten=['quickened','overclocked','loaded_chamber','deliberate_power','staccato','crescendo','kill_reset','pyre','blood_price','heavy_hands'];[...ten,'leeching'].forEach(id=>sup.grant(id,1,60,true));const tenResults=ten.map(id=>sup.equip('Slash',id)),eleventh=sup.equip('Slash','leeching'),slotCap=tenResults.every(Boolean)&&sup.equipped('Slash').length===10&&!eleventh;
 sup.reset();sup.grant('quickened',1,60,true);const alloc1=sup.equip('Firebolt','quickened'),alloc2=sup.equip('FrostLance','quickened'),copyAllocation=alloc1&&!alloc2;
 sup.reset();['quickened','rime','echo'].forEach(id=>sup.grant(id,2,60,true));sup.equip('Firebolt','quickened');sup.equip('Firebolt','rime');sup.equip('Firebolt','echo');const prev=sup.preview('Firebolt'),cooldownChanged=prev.cooldownMult<1&&prev.activeType==='Cold';
 forceRoom(['guard','rot']);const target=pickTarget();if(!target)throw new Error('No target after forceRoom');const beforeCasts=skillCasts.Firebolt||0;const fired=castSkill('Firebolt',target,false,false);hit(target,10,'Firebolt',false,0);const coldApplied=(target.g6SlowUntil||0)>roomClock;for(let i=0;i<24;i++)step(.035);const repeatWorked=fired&&(skillCasts.Firebolt||0)>=beforeCasts+2;
 sup.reset();const reward=sup.awardStage(10),stageDrop=reward.length===2&&sup.state().drops===2;
 sup.debugUnlockAll(3);window.DopamineSupportUI.open('Firebolt');const uiCards=document.querySelectorAll('.g6support').length,uiSlots=document.querySelectorAll('.g6slot').length,ui=uiCards===60&&uiSlots===10;document.getElementById('g6supportPanel').style.display='none';
 const errs=typeof runtimeErrors!=='undefined'?runtimeErrors:[],ok=catalog&&coverage&&slotCap&&copyAllocation&&cooldownChanged&&coldApplied&&repeatWorked&&stageDrop&&ui&&errs.length===0;
 report('__DOPAMINE_SUPPORT_TEST',[`SUPPORT_TEST_OK=${ok}`,`CATALOG_COUNT=${ids.length}`,`CATEGORY_COUNT=${cat.categories.length}`,`MEANINGFUL_EFFECTS=${meaningful}`,`MIN_COMPATIBLE_PER_SKILL=${minCompatible}`,`TEN_SLOT_CAP=${slotCap}`,`ELEVENTH_REJECTED=${!eleventh}`,`COPY_ALLOCATION=${copyAllocation}`,`COOLDOWN_CHANGED=${cooldownChanged}`,`CONVERSION_COLD_APPLIED=${coldApplied}`,`ECHO_REPEAT_CAST=${repeatWorked}`,`BOSS_STAGE_DROPS=${reward.length}`,`SUPPORT_UI_CARDS=${uiCards}`,`SUPPORT_UI_SLOTS=${uiSlots}`,`ERRORS=${errs.join('|')}`],{ok,catalog,meaningful,coverage,minCompatible,slotCap,copyAllocation,cooldownChanged,coldApplied,repeatWorked,stageDrop,ui,errors:errs});return;
}catch(e){fail('__DOPAMINE_SUPPORT_TEST','SUPPORT_TEST_OK',e);return}}
if(mobile){try{
 unlockSkills();sup.reset();sup.debugUnlockAll(2);window.DopamineStageSummary.pin(true);
 const overlay=document.getElementById('overlay'),footer=document.querySelector('footer'),next=document.getElementById('next'),or=overlay.getBoundingClientRect(),fr=footer.getBoundingClientRect(),nr=next.getBoundingClientRect(),cx=nr.left+nr.width/2,cy=nr.top+nr.height/2,hitEl=document.elementFromPoint(cx,cy),summaryVisible=getComputedStyle(overlay).display!=='none',clearance=fr.top-or.bottom,proceedVisible=nr.top>=0&&nr.bottom<=innerHeight&&nr.width>30&&nr.height>30,proceedTopmost=hitEl===next||next.contains(hitEl);
 window.DopamineSupportUI.open('Firebolt');const panel=document.getElementById('g6supportPanel'),supportPanel=getComputedStyle(panel).display!=='none'&&document.querySelectorAll('.g6slot').length===10&&document.querySelectorAll('.g6support').length===60;panel.style.display='none';const errs=typeof runtimeErrors!=='undefined'?runtimeErrors:[],ok=summaryVisible&&clearance>=0&&proceedVisible&&proceedTopmost&&supportPanel&&errs.length===0;
 report('__DOPAMINE_SUPPORT_MOBILE',[`SUPPORT_MOBILE_OK=${ok}`,`SUMMARY_VISIBLE=${summaryVisible}`,`SUMMARY_FOOTER_CLEARANCE=${clearance.toFixed(1)}`,`PROCEED_VISIBLE=${proceedVisible}`,`PROCEED_TOPMOST=${proceedTopmost}`,`PROCEED_TEXT=${next.textContent}`,`SUPPORT_PANEL=${supportPanel}`,`VIEWPORT=${innerWidth}x${innerHeight}`,`ERRORS=${errs.join('|')}`],{ok,summaryVisible,clearance,proceedVisible,proceedTopmost,supportPanel,errors:errs});return;
}catch(e){fail('__DOPAMINE_SUPPORT_MOBILE','SUPPORT_MOBILE_OK',e);return}}
if(soak){try{
 unlockSkills();sup.reset();sup.debugUnlockAll(40);const conv=['pyre','rime','storm','void','iron'];for(const [i,sid] of api.ids().entries()){const d=api.get(sid),want=['quickened','crescendo','kill_reset',conv[i%conv.length]];if((d.tags||[]).includes('Projectile'))want.push('forking_impact','seeker');else if((d.tags||[]).includes('Minion'))want.push('command_chain','guardian_pact');else if((d.tags||[]).includes('Melee'))want.push('cleaving_edge','leeching');else if((d.tags||[]).includes('DoT')||d.area)want.push('expanded_area','lingering_pain');else want.push('loaded_chamber','blood_price');for(const id of want)if(sup.compatible(sid,id))sup.equip(sid,id)}
 pausedForBrain=false;active=false;const seed0=baseSeed,ids=api.ids(),agg={sim:0,steps:0,rooms:0,wins:0,losses:0,stalls:0,truncated:0,stallInfo:[],casts:Object.fromEntries(ids.map(id=>[id,0]))};let stop=false;
 while(!stop&&agg.sim<3600&&agg.steps<155000){depth=1+(agg.rooms%30);baseSeed=(seed0+Math.imul(agg.rooms+1,7919))>>>0;brain.skills=builds[agg.rooms%builds.length].slice();beginRoom();let local=0,cut=false;while(active&&local<2600){if(agg.sim>=3600){cut=true;break}step(.035);local++;agg.steps++;agg.sim+=.035}for(const id of ids)agg.casts[id]+=(skillCasts[id]||0);const live=en.filter(e=>!e.dead);if(cut&&active){agg.truncated++;active=false;stop=true}else if(active&&local>=2600){agg.stalls++;agg.stallInfo.push({room:agg.rooms,depth,load:brain.skills.slice(),clock:+roomClock.toFixed(1),live:live.length,decision:lastDecision});active=false}else if(P.dead||live.length)agg.losses++;else agg.wins++;agg.rooms++}
 baseSeed=seed0;const coverage=ids.every(id=>agg.casts[id]>0),supportCoverage=ids.every(id=>sup.equipped(id).length>=5),errs=typeof runtimeErrors!=='undefined'?runtimeErrors:[],ok=agg.sim>=3599&&agg.stalls===0&&coverage&&supportCoverage&&errs.length===0;
 report('__DOPAMINE_SUPPORT_SOAK',[`SUPPORT_SOAK_OK=${ok}`,`SIM_SECONDS=${agg.sim.toFixed(1)}`,`STEPS=${agg.steps}`,`ROOMS=${agg.rooms}`,`WINS=${agg.wins}`,`LOSSES=${agg.losses}`,`STALLS=${agg.stalls}`,`TRUNCATED_FINAL_ROOMS=${agg.truncated}`,`CAST_COVERAGE=${coverage}`,`SUPPORT_COVERAGE=${supportCoverage}`,`SUPPORT_DROPS=${sup.state().drops}`,`CASTS=${Object.entries(agg.casts).map(([k,v])=>k+':'+v).join(',')}`,`STALL_INFO=${JSON.stringify(agg.stallInfo)}`,`ERRORS=${errs.join('|')}`],{ok,...agg,coverage,supportCoverage,state:sup.state(),errors:errs});
}catch(e){fail('__DOPAMINE_SUPPORT_SOAK','SUPPORT_SOAK_OK',e)}}
})();
