'use strict';
(()=>{
const q=new URLSearchParams(location.search),QA=['supporttest','supportmobile','supportsoak'].some(k=>q.has(k));
const api=window.DopamineSkills,g4=window.DopamineGoal4,cat=window.DopamineSupportCatalog;if(!api||!g4||!cat)return;
const KEY='dopamineSupportsV10',MAX=10,ids=cat.ids(),defs=Object.fromEntries(ids.map(id=>[id,cat.get(id)]));
const fresh=()=>({schema:10,owned:{},equipped:{},drops:0,stageClears:0,newPity:0,history:[],lastDrop:null});let state=fresh();
if(!QA){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.schema===10)state={...fresh(),...x,owned:{...(x.owned||{})},equipped:{...(x.equipped||{})}}}catch(e){}}
const save=()=>{if(QA)return;try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}};
const trait=(sid,t)=>{const d=api.get(sid),tags=d?.tags||[];if(tags.includes(t))return true;if(t==='AoE')return!!d?.area||d?.brain?.kind==='aoe';if(t==='Damage')return(d?.baseDamage||0)>0;return false};
function compatible(sid,supid){const s=defs[supid];if(!s||!api.get(sid))return false;return!s.requires?.length||s.requires.some(t=>trait(sid,t))}
function equipped(sid){const a=Array.isArray(state.equipped[sid])?state.equipped[sid]:[];return a.filter(id=>defs[id]&&state.owned[id]>0&&compatible(sid,id)).slice(0,MAX)}
function usedCopies(supid,except=null){let n=0;for(const sid of api.ids())if(sid!==except&&equipped(sid).includes(supid))n++;return n}
function availableCopies(supid,except=null){return Math.max(0,(state.owned[supid]||0)-usedCopies(supid,except))}
function equip(sid,supid){if(!api.isOwned(sid)||!defs[supid]||!state.owned[supid]||!compatible(sid,supid))return false;const current=equipped(sid),already=current.includes(supid);if(!already&&availableCopies(supid,sid)<=0)return false;let a=current.filter(x=>x!==supid),group=defs[supid].group;if(group)a=a.filter(x=>defs[x]?.group!==group);if(a.length>=MAX)return false;a.push(supid);state.equipped[sid]=a;save();window.DopamineSupportUI?.refresh(sid);return true}
function unequip(sid,supid){state.equipped[sid]=equipped(sid).filter(x=>x!==supid);save();window.DopamineSupportUI?.refresh(sid);return true}
function grant(supid,count=1,sourceDepth=(typeof depth==='number'?depth:1),quiet=false){if(!defs[supid])return false;count=Math.max(1,count|0);state.owned[supid]=(state.owned[supid]||0)+count;state.drops+=count;state.lastDrop={id:supid,depth:sourceDepth,t:Date.now()};state.history.unshift({...state.lastDrop,name:defs[supid].name});state.history=state.history.slice(0,40);save();if(!quiet)window.DopamineSupportUI?.toast(defs[supid],state.owned[supid]);return true}
function rollSupport(d){const pool=ids.filter(id=>defs[id].tier<=1+(d>=10?1:0)+(d>=25?1:0)),unseen=pool.filter(id=>!state.owned[id]);state.newPity++;let pick;if(unseen.length&&state.newPity>=5){pick=unseen[(rng()*unseen.length)|0];state.newPity=0}else{const weighted=[];for(const id of pool){const w=defs[id].tier===1?7:defs[id].tier===2?3:1;for(let i=0;i<w;i++)weighted.push(id)}pick=weighted[(rng()*weighted.length)|0];if(!state.owned[pick])state.newPity=0}return pick}
function awardStage(d=(typeof depth==='number'?depth:1)){state.stageClears++;const n=d%10===0?2:1,out=[];for(let i=0;i<n;i++){const id=rollSupport(d);grant(id,1,d,true);out.push(id)}save();out.forEach(id=>window.DopamineSupportUI?.toast(defs[id],state.owned[id]));return out}
function supportDefs(sid){return equipped(sid).map(id=>defs[id])}
function aggregate(sid){let damage=1,cooldown=1,range=1,needBonus=0,ignoreLos=false,knockback=0;for(const s of supportDefs(sid)){const m=s.mods||{};damage*=m.damage||1;cooldown*=m.cooldown||1;range*=m.range||1;needBonus+=s.needBonus||0;ignoreLos=ignoreLos||!!s.ignoreLos;knockback+=s.knockback||0}return{damage:Math.max(.25,Math.min(4,damage)),cooldown:Math.max(.35,Math.min(2.4,cooldown)),range:Math.max(.65,Math.min(1.8,range)),needBonus,ignoreLos,knockback}}
const castCount={},lastCast={},streak={},lastStreak={},forcedReady={},activeType={},repeatQ=[],dotQ=[];let secondary=false,supportCast=false,lastRewards=[];
const now=()=>typeof roomClock==='number'?roomClock:0,liveEnemies=()=>typeof en==='undefined'?[]:en.filter(e=>!e.dead);
function supportedCooldown(sid){const d=api.effective(sid)||api.get(sid)||{},a=aggregate(sid);let cd=(d.cooldown||0)*a.cooldown;if(supportDefs(sid).some(s=>s.pattern==='staccato'))cd*=((castCount[sid]||0)%2?1.25:.62);return Math.max(.05,cd)}
function resolveType(sid){const s=supportDefs(sid).find(x=>x.conversion);if(!s)return(api.get(sid)?.tags||[]).find(t=>['Fire','Cold','Lightning','Chaos','Physical'].includes(t))||'Native';if(s.conversion==='Cycle'){const a=['Fire','Cold','Lightning'];return a[((castCount[sid]||1)-1)%3]}if(s.conversion==='Random'){const a=['Fire','Cold','Lightning','Chaos','Physical'];return a[(rng()*a.length)|0]}return s.conversion}
function sourceSkill(k){const x=String(k||''),aliases={Burn:'Firebolt','Firebolt Ember':'Firebolt','Slash Cleave':'Slash','Slam Aftershock':'Slam','Wisp Chain':'Wisp','Wisp Ember':'Wisp','Poison':'VenomFang'};if(aliases[x])return aliases[x];for(const sid of api.ids()){const n=api.get(sid)?.name||sid;if(x===sid||x===n||x.startsWith(n+' '))return sid}return null}
function altTarget(exclude){let best=null,bd=Infinity;for(const e of liveEnemies()){if(e.id===exclude)continue;const d=Math.hypot(e.x-P.x,e.y-P.y);if(d<bd){bd=d;best=e}}return best}
function scheduleRepeats(sid,t){for(const s of supportDefs(sid)){if(!s.repeat)continue;const every=s.repeat.every||1;if((castCount[sid]||0)%every)continue;for(let i=0;i<s.repeat.count;i++)repeatQ.push({sid,targetId:t?.id??null,left:s.repeat.delay*(i+1),mode:s.repeat.mode||'same'})}}
function onCast(sid){const t=now(),prev=lastStreak[sid]??-99;castCount[sid]=(castCount[sid]||0)+1;lastCast[sid]=t;delete forcedReady[sid];if(t-prev<=3)streak[sid]=Math.min(6,(streak[sid]||0)+1);else streak[sid]=0;lastStreak[sid]=t;activeType[sid]=resolveType(sid);for(const s of supportDefs(sid)){if(s.selfDamage)P.hp=Math.max(1,P.hp-P.max*s.selfDamage);if(s.healOnCast)P.hp=Math.min(P.max,P.hp+P.max*s.healOnCast)}const col={Fire:'#ff7a45',Cold:'#9eefff',Lightning:'#b5a1ff',Chaos:'#a9e866',Physical:'#e9d4b4',PurePhysical:'#fff0c2'}[activeType[sid]];if(col)try{ring(P.x,P.y,24,col,2)}catch(e){}}
const rawSkillState=skillState;skillState=function(sid,t,combo=false){const s=rawSkillState(sid,t,combo),d=api.get(sid);if(!d||!api.isOwned(sid))return s;const a=aggregate(sid),elapsed=now()-(lastCast[sid]??-999),need=supportedCooldown(sid);if(forcedReady[sid]&&forcedReady[sid]>=now())return{...s,ok:true,reason:'SUPPORT RESET'};if(elapsed<need)return{...s,ok:false,reason:`SUPPORT CD ${(need-elapsed).toFixed(1)}s`};if(s.ok){if(a.needBonus>0&&d.brain?.kind==='aoe'){const count=typeof near==='function'?near(d.area||d.range||100).length:0,req=(d.brain?.minTargets||1)+a.needBonus;if(count<req&&(s.age||0)<(brain.skillFlexAfter||2.5))return{...s,ok:false,reason:`CONCENTRATE ${count}/${req}`}}return s}const reason=String(s.reason||''),dis=t?dist(P,t):Infinity,k=d.brain?.kind||'single',r=(d.range||d.area||80)*a.range;if(/^[0-9.]+s$/.test(reason)){if(k==='single'&&t&&dis<=r)return{...s,ok:true,reason:'SUPPORT READY'};if(k==='aoe'){const count=typeof near==='function'?near(d.area||d.range||100).length:0,req=(d.brain?.minTargets||1)+a.needBonus;if(count>=req||(t&&dis<=r&&(s.age||0)>=(brain.skillFlexAfter||2.5)))return{...s,ok:true,reason:'SUPPORT READY'}}}if((reason==='OUT OF RANGE'||reason==='SEEK RANGE')&&t&&dis<=r)return{...s,ok:true,reason:'EXTENDED RANGE'};if(a.ignoreLos&&reason==='SEEK LINE OF SIGHT'&&t&&dis<=r)return{...s,ok:true,reason:'SEEKER LOCK'};return s};
const rawCast=castSkill;castSkill=function(sid,t,forced=false,combo=false){const ok=rawCast(sid,t,forced,combo);if(ok&&!supportCast){onCast(sid);scheduleRepeats(sid,t)}return ok};
function conditionalMult(sid,e){let m=1;for(const s of supportDefs(sid)){if(s.pattern==='pointblank'){const d=dist(P,e);m*=d<90?1.55:d>190?.78:1}else if(s.pattern==='farshot'){const d=dist(P,e);m*=d>180?1.48:d<85?.78:1}else if(s.pattern==='crescendo')m*=1+Math.min(.48,(streak[sid]||0)*.08);else if(s.pattern==='ruthless'&&(castCount[sid]||0)%3===0)m*=1.85;else if(s.pattern==='duelist')m*=liveEnemies().length<=1?1.55:.90;else if(s.pattern==='staccato')m*=((castCount[sid]||0)%2?1.45:.72);if(s.execute&&e.hp/e.max<=s.execute.threshold)m*=s.execute.mult}return m}
function nearby(e,r,count,exclude=new Set()){return liveEnemies().filter(x=>x!==e&&!exclude.has(x.id)).sort((a,b)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(b.x-e.x,b.y-e.y)).filter(x=>Math.hypot(x.x-e.x,x.y-e.y)<=r).slice(0,count)}
function queueDot(e,sid,damage,s){if(!e||damage<=0)return;for(let i=1;i<=s.ticks;i++)dotQ.push({e,sid,left:s.interval*i,damage:damage*s.ratio,type:s.type||'Support DoT'})}
function applyConversion(e,sid,dealt){const type=activeType[sid]||resolveType(sid),t=now();if(type.includes('Fire'))queueDot(e,sid,dealt,{ticks:3,interval:.42,ratio:.055,type:'Ignite'});if(type.includes('Cold')){e.g6SlowUntil=Math.max(e.g6SlowUntil||0,t+1.25);e.g6SlowPct=Math.max(e.g6SlowPct||0,.18)}if(type.includes('Lightning')){e.g6ShockUntil=Math.max(e.g6ShockUntil||0,t+1.4);e.g6Shock=.12}if(type.includes('Chaos'))queueDot(e,sid,dealt,{ticks:4,interval:.38,ratio:.045,type:'Poison'});if((type==='Physical'||type==='PurePhysical')&&type!=='PurePhysical'){const dx=e.x-P.x,dy=e.y-P.y,l=Math.max(1,Math.hypot(dx,dy));e.vx=(e.vx||0)+dx/l*36;e.vy=(e.vy||0)+dy/l*36}}
const rawSteer=steer;steer=function(a,dx,dy,spd,dt,turn){if(a?.g6SlowUntil>now())spd*=1-(a.g6SlowPct||.18);return rawSteer(a,dx,dy,spd,dt,turn)};
const rawHit=hit;hit=function(e,a,k,crit=false,kb=0){const sid=sourceSkill(k);if(!sid||secondary)return rawHit(e,a,k,crit,kb);const ag=aggregate(sid),before=e.hp||0;let mult=ag.damage*conditionalMult(sid,e);if((e.g6ShockUntil||0)>now())mult*=1+(e.g6Shock||.12);rawHit(e,a*mult,k,crit,kb+ag.knockback);const dealt=Math.max(0,before-Math.max(0,e.hp||0));for(const s of supportDefs(sid)){if(s.splash){secondary=true;for(const x of nearby(e,s.splash.radius,s.splash.count))rawHit(x,dealt*s.splash.ratio,api.get(sid).name,false,0);secondary=false}if(s.chain){secondary=true;for(const x of nearby(e,s.chain.radius,s.chain.count))rawHit(x,dealt*s.chain.ratio,api.get(sid).name,false,0);secondary=false}if(s.pierce){const dx=e.x-P.x,dy=e.y-P.y,l=Math.max(1,Math.hypot(dx,dy)),cand=nearby(e,s.pierce.radius,s.pierce.count).filter(x=>((x.x-e.x)*dx+(x.y-e.y)*dy)/l>0);secondary=true;for(const x of cand)rawHit(x,dealt*s.pierce.ratio,api.get(sid).name,false,0);secondary=false}if(s.pull){for(const x of nearby(e,135,5)){const dx=e.x-x.x,dy=e.y-x.y,l=Math.max(1,Math.hypot(dx,dy));x.x+=dx/l*s.pull;x.y+=dy/l*s.pull}}if(s.dot)queueDot(e,sid,dealt,s.dot);if(s.leech)P.hp=Math.min(P.max,P.hp+dealt*s.leech)}applyConversion(e,sid,dealt);const killed=before>0&&e.dead;if(killed){for(const s of supportDefs(sid)){if(s.onKill==='reset')forcedReady[sid]=now()+2.5;if(s.onKill==='burst'){secondary=true;for(const x of nearby(e,115,4))rawHit(x,dealt*.38,api.get(sid).name,false,0);secondary=false}if(s.onKill==='epidemic'){for(const x of nearby(e,125,3))queueDot(x,sid,dealt,{ticks:3,interval:.45,ratio:.18,type:'Epidemic'})}}}}
const rawStep=step;step=function(dt){rawStep(dt);for(let i=repeatQ.length-1;i>=0;i--){const r=repeatQ[i];r.left-=dt;if(r.left<=0){repeatQ.splice(i,1);if(!active)continue;let t=liveEnemies().find(e=>e.id===r.targetId)||null;if(r.mode==='alternate')t=altTarget(r.targetId)||t||pickTarget();else t=t||pickTarget();if(!t&&api.get(r.sid)?.brain?.kind!=='utility')continue;supportCast=true;try{rawCast(r.sid,t,false,false)}finally{supportCast=false}}}for(let i=dotQ.length-1;i>=0;i--){const z=dotQ[i];z.left-=dt;if(z.left<=0){dotQ.splice(i,1);if(z.e&&!z.e.dead){secondary=true;try{rawHit(z.e,z.damage,api.get(z.sid)?.name||z.type,false,0)}finally{secondary=false}}}}};
const rawBegin=beginRoom;beginRoom=function(){repeatQ.length=0;dotQ.length=0;for(const k of Object.keys(forcedReady))delete forcedReady[k];rawBegin()};
const rawFinish=finish;finish=function(win){lastRewards=win?awardStage(typeof depth==='number'?depth:1):[];rawFinish(win);if(lastRewards.length&&statsEl){statsEl.textContent=`Support drop         ${lastRewards.map(id=>defs[id].name).join(' • ')}\nSupport collection   ${ids.filter(id=>state.owned[id]).length}/${ids.length} types • ${state.drops} total drops\n`+statsEl.textContent}try{window.DopamineStageSummary?.pin(win)}catch(e){}};
function reset(){state=fresh();for(const k of Object.keys(castCount))delete castCount[k];repeatQ.length=dotQ.length=0;if(!QA)try{localStorage.removeItem(KEY)}catch(e){};return true}
function unlockAll(copies=1){for(const id of ids)state.owned[id]=Math.max(state.owned[id]||0,copies);save();return ids.length}
function preview(sid){const a=aggregate(sid);return{skill:sid,equipped:equipped(sid),damageMult:a.damage,cooldownMult:a.cooldown,rangeMult:a.range,supportedCooldown:supportedCooldown(sid),activeType:activeType[sid]||resolveType(sid),repeatQueue:repeatQ.length,dotQueue:dotQ.length}}
window.DopamineSupports=Object.freeze({version:'Support System v1.0',maxPerSkill:MAX,ids:()=>[...ids],get:id=>defs[id]||null,all:()=>ids.map(id=>defs[id]),compatible,equipped,owned:id=>state.owned[id]||0,availableCopies,equip,unequip,grant,awardStage,preview,state:()=>JSON.parse(JSON.stringify(state)),reset,debugUnlockAll:unlockAll,lastRewards:()=>[...lastRewards],compatibleCount:sid=>ids.filter(id=>compatible(sid,id)).length});
})();
