'use strict';
(()=>{
const api=window.DopamineSkills,sup=window.DopamineSupports,cat=window.DopamineSupportCatalog;if(!api||!sup||!cat)return;
const css=document.createElement('style');css.id='g6SupportCss';css.textContent=`
#g6supportToast{position:fixed;right:6px;bottom:calc(var(--g6footer-h,64px) + 8px);z-index:80;width:min(174px,44vw);padding:6px 8px;border:1px solid #75e0bd;border-radius:8px;background:#071811f2;box-shadow:0 6px 20px #000a;text-align:right;pointer-events:none;font:800 7px/1.2 system-ui}#g6supportToast small{display:block;font-size:5px;letter-spacing:.12em;color:#86f0cc}#g6supportToast b{display:block;font-size:9px;margin:1px 0}#g6supportToast span{opacity:.72}.g6supportBtn{width:100%;min-height:29px!important;margin-top:4px;font-size:7px!important;border-color:#3f806d!important;background:#0c2b22!important}.g6supportBtn.has{box-shadow:0 0 0 1px #72e0b8 inset}#g6supportPanel{position:fixed;inset:0;z-index:100;display:none;background:#03070cee;padding:8px;overflow:auto}#g6supportCard{width:min(760px,100%);margin:0 auto;background:#0b1722;border:1px solid #3e6d61;border-radius:15px;padding:12px;min-height:calc(100vh - 16px)}.g6head{display:flex;justify-content:space-between;gap:8px;align-items:center;position:sticky;top:-8px;background:#0b1722;z-index:2;padding:4px 0 8px}.g6head h2{font-size:18px;margin:0}.g6sub{font-size:8px;opacity:.7}.g6slots{display:grid;grid-template-columns:repeat(5,1fr);gap:4px;margin:7px 0}.g6slot{min-height:48px;border:1px solid #345b52;border-radius:7px;padding:5px;background:#08131b;font-size:7px}.g6slot b{display:block;font-size:8px}.g6slot button{min-height:23px;width:100%;font-size:6px;margin-top:3px}.g6grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:5px}.g6support{border:1px solid #2f4655;border-radius:8px;background:#07111a;padding:7px;font-size:7px;line-height:1.3}.g6support.locked{opacity:.38}.g6support.incompatible{opacity:.5}.g6support h3{font-size:10px;margin:0 0 2px}.g6support .meta{opacity:.68;margin:3px 0}.g6support button{width:100%;min-height:28px;font-size:7px}.g6cat{display:inline-block;padding:2px 4px;border:1px solid #3f665c;border-radius:99px;font-size:6px}.g6collection{font-size:8px;padding:7px;background:#0a211b;border:1px solid #315d50;border-radius:8px;margin:5px 0}.g6collection b{font-size:10px}.g6global{width:100%;min-height:32px!important;font-size:8px!important;background:#0d3229!important;border-color:#4f9c83!important}@media(max-width:520px){#g6supportPanel{padding:0}#g6supportCard{border-radius:0;min-height:100vh;padding:9px}.g6slots{grid-template-columns:1fr 1fr}.g6grid{grid-template-columns:1fr}#g6supportToast{right:5px;width:min(150px,42vw)}}`;
document.head.appendChild(css);
const panel=document.createElement('div');panel.id='g6supportPanel';panel.innerHTML='<div id="g6supportCard"></div>';document.body.appendChild(panel);let selected=null;
function toast(s,count){document.getElementById('g6supportToast')?.remove();const x=document.createElement('div');x.id='g6supportToast';x.innerHTML=`<small>SUPPORT DROP</small><b>${s.name}</b><span>${s.category} • owned ×${count}</span>`;document.body.appendChild(x);setTimeout(()=>x.remove(),3200)}
function render(sid=selected){selected=sid;if(!sid||!api.get(sid))return;const c=document.getElementById('g6supportCard'),eq=sup.equipped(sid),all=cat.ids(),ownedN=all.filter(id=>sup.owned(id)).length,compatN=all.filter(id=>sup.compatible(sid,id)).length;c.innerHTML=`<div class="g6head"><div><h2>${api.get(sid).name} SUPPORTS</h2><div class="g6sub">Up to ${sup.maxPerSkill} modifiers • each support copy can be allocated to one skill at a time</div></div><button id="g6close">CLOSE</button></div><div class="g6collection"><b>${eq.length}/${sup.maxPerSkill} EQUIPPED • ${ownedN}/${all.length} SUPPORT TYPES FOUND</b><br>${compatN} support types are compatible with this skill. Stage clears drop 1 support; boss depths drop 2.</div><div class="g6slots">${Array.from({length:sup.maxPerSkill},(_,i)=>{const id=eq[i],s=id?cat.get(id):null;return`<div class="g6slot"><small>SLOT ${i+1}</small>${s?`<b>${s.name}</b><span>${s.category}</span><button data-remove="${id}">REMOVE</button>`:'<b>EMPTY</b><span>Find supports in stage runs</span>'}</div>`}).join('')}</div><div class="g6grid">${all.map(id=>{const s=cat.get(id),own=sup.owned(id),comp=sup.compatible(sid,id),on=eq.includes(id),avail=sup.availableCopies(id,sid)+(on?1:0);return`<div class="g6support ${own?'':'locked'} ${comp?'':'incompatible'}"><div style="display:flex;justify-content:space-between;gap:4px"><h3>${s.name}</h3><b>×${own}</b></div><span class="g6cat">${s.category}</span><div class="meta">${s.desc}</div><div class="meta">${!own?'UNDISCOVERED':!comp?'INCOMPATIBLE':on?'EQUIPPED':avail>0?`${avail} copy available`:'ALLOCATED ELSEWHERE'}</div>${own&&comp?`<button data-${on?'remove':'equip'}="${id}" ${!on&&avail<=0?'disabled':''}>${on?'REMOVE':'EQUIP'}</button>`:''}</div>`}).join('')}</div>`;c.querySelector('#g6close').onclick=()=>{panel.style.display='none';if(document.getElementById('skillLabPanel')?.style.display!=='block')pausedForBrain=false};c.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>sup.equip(sid,b.dataset.equip));c.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>sup.unequip(sid,b.dataset.remove))}
function open(sid){if(!sid||!api.isOwned(sid))return;selected=sid;pausedForBrain=true;panel.style.display='block';render(sid)}
function decorate(){const lab=document.getElementById('skillLabPanel');if(!lab||lab.style.display!=='block')return;const toolbar=lab.querySelector('.g4toolbar');if(toolbar&&!lab.querySelector('.g6global')){const b=document.createElement('button');b.className='g6global';b.textContent=`SUPPORT COLLECTION ${cat.ids().filter(id=>sup.owned(id)).length}/${cat.count}`;b.onclick=()=>open(api.loadout().find(Boolean)||api.ownedIds()[0]);toolbar.before(b)}for(const card of lab.querySelectorAll('.g4skill')){if(card.querySelector('.g6supportBtn'))continue;const name=card.querySelector('h3')?.textContent,sid=api.ids().find(id=>api.get(id)?.name===name);if(!sid||!api.isOwned(sid))continue;const b=document.createElement('button');b.className='g6supportBtn '+(sup.equipped(sid).length?'has':'');b.textContent=`SUPPORTS ${sup.equipped(sid).length}/${sup.maxPerSkill}`;b.onclick=()=>open(sid);card.appendChild(b)}}
const mo=new MutationObserver(()=>requestAnimationFrame(decorate));mo.observe(document.getElementById('skillLabPanel')||document.body,{childList:true,subtree:true});document.getElementById('skillLabBtn')?.addEventListener('click',()=>requestAnimationFrame(decorate));
function refresh(sid=selected){if(panel.style.display==='block'&&sid)render(sid);requestAnimationFrame(decorate)}
window.DopamineSupportUI=Object.freeze({version:'Support UI v1.0',open,render,refresh,toast,selected:()=>selected,panel:()=>panel});
})();
