'use strict';
const brainPanel=document.getElementById('brainPanel'),brainSummary=document.getElementById('brainSummary'),closeBrain=document.getElementById('closeBrain'),applyBrain=document.getElementById('applyBrain'),applyReplay=document.getElementById('applyReplay');
const brainInputs={targetMode:document.getElementById('targetMode'),executePct:document.getElementById('executePct'),targetLock:document.getElementById('targetLock'),chaseLeash:document.getElementById('chaseLeash'),stance:document.getElementById('stance'),retreatHp:document.getElementById('retreatHp'),reengageHp:document.getElementById('reengageHp'),surround:document.getElementById('surround'),dangerSense:document.getElementById('dangerSense'),useCover:document.getElementById('useCover'),adaptEvasion:document.getElementById('adaptEvasion'),adaptAfter:document.getElementById('adaptAfter'),adaptMode:document.getElementById('adaptMode'),skill1:document.getElementById('skill1'),skill2:document.getElementById('skill2'),skill3:document.getElementById('skill3'),slamMin:document.getElementById('slamMin'),whirlMin:document.getElementById('whirlMin'),skillFlexAfter:document.getElementById('skillFlexAfter'),comboMode:document.getElementById('comboMode'),dodgeProjectiles:document.getElementById('dodgeProjectiles'),dodgeTelegraphs:document.getElementById('dodgeTelegraphs')};
const valueEls={executePct:document.getElementById('executeVal'),targetLock:document.getElementById('lockVal'),chaseLeash:document.getElementById('leashVal'),retreatHp:document.getElementById('retreatVal'),reengageHp:document.getElementById('reengageVal'),surround:document.getElementById('surroundVal'),adaptAfter:document.getElementById('adaptVal'),slamMin:document.getElementById('slamVal'),whirlMin:document.getElementById('whirlVal'),skillFlexAfter:document.getElementById('flexVal')};
const PRESETS={
 berserker:{name:'BERSERKER',targetMode:'lowhp',executePct:40,targetLock:2.5,chaseLeash:7,stance:'chase',retreatHp:10,reengageHp:25,surround:8,dangerSense:'low',useCover:false,adaptEvasion:true,adaptAfter:4,adaptMode:'hybrid',skills:['Slam','Whirlwind','Slash'],slamMin:3,whirlMin:3,skillFlexAfter:2,comboMode:'slamWhirl',dodgeProjectiles:true,dodgeTelegraphs:true},
 balanced:{name:'BALANCED',targetMode:'threat',executePct:20,targetLock:1.75,chaseLeash:5,stance:'balanced',retreatHp:30,reengageHp:45,surround:5,dangerSense:'medium',useCover:true,adaptEvasion:true,adaptAfter:3,adaptMode:'hybrid',skills:['Slam','Whirlwind','Slash'],slamMin:4,whirlMin:3,skillFlexAfter:2.5,comboMode:'adaptive',dodgeProjectiles:true,dodgeTelegraphs:true},
 tactician:{name:'TACTICIAN',targetMode:'support',executePct:25,targetLock:2.25,chaseLeash:4.5,stance:'balanced',retreatHp:38,reengageHp:55,surround:4,dangerSense:'high',useCover:true,adaptEvasion:true,adaptAfter:2.6,adaptMode:'switch',skills:['Whirlwind','Slam','Slash'],slamMin:5,whirlMin:3,skillFlexAfter:3,comboMode:'whirlSlam',dodgeProjectiles:true,dodgeTelegraphs:true},
 kiter:{name:'KITER',targetMode:'ranged',executePct:20,targetLock:2,chaseLeash:4,stance:'kite',retreatHp:45,reengageHp:60,surround:3,dangerSense:'high',useCover:true,adaptEvasion:true,adaptAfter:2.2,adaptMode:'intercept',skills:['Whirlwind','Slash','Slam'],slamMin:5,whirlMin:2,skillFlexAfter:2.2,comboMode:'adaptive',dodgeProjectiles:true,dodgeTelegraphs:true}
};
let brain={...PRESETS.balanced,skills:[...PRESETS.balanced.skills],custom:false};
function loadBrain(){try{const x=JSON.parse(localStorage.getItem('dopamineBrainV2'));if(x&&x.targetMode)brain={...brain,...x,skills:Array.isArray(x.skills)?x.skills:brain.skills}}catch(e){}}
function saveBrain(){try{localStorage.setItem('dopamineBrainV2',JSON.stringify(brain))}catch(e){}}
function setPreset(k,write=true){const p=PRESETS[k];brain={...p,skills:[...p.skills],custom:false};if(write){writeBrainForm();saveBrain();updateBrainTicker()}}
function readBrainForm(){const candidate={name:'CUSTOM',targetMode:brainInputs.targetMode.value,executePct:+brainInputs.executePct.value,targetLock:+brainInputs.targetLock.value,chaseLeash:+brainInputs.chaseLeash.value,stance:brainInputs.stance.value,retreatHp:+brainInputs.retreatHp.value,reengageHp:+brainInputs.reengageHp.value,surround:+brainInputs.surround.value,dangerSense:brainInputs.dangerSense.value,useCover:brainInputs.useCover.checked,adaptEvasion:brainInputs.adaptEvasion.checked,adaptAfter:+brainInputs.adaptAfter.value,adaptMode:brainInputs.adaptMode.value,skills:[brainInputs.skill1.value,brainInputs.skill2.value,brainInputs.skill3.value],slamMin:+brainInputs.slamMin.value,whirlMin:+brainInputs.whirlMin.value,skillFlexAfter:+brainInputs.skillFlexAfter.value,comboMode:brainInputs.comboMode.value,dodgeProjectiles:brainInputs.dodgeProjectiles.checked,dodgeTelegraphs:brainInputs.dodgeTelegraphs.checked,custom:true};candidate.reengageHp=Math.max(candidate.reengageHp,candidate.retreatHp+5);for(const p of Object.values(PRESETS)){const keys=['targetMode','executePct','targetLock','chaseLeash','stance','retreatHp','reengageHp','surround','dangerSense','useCover','adaptEvasion','adaptAfter','adaptMode','slamMin','whirlMin','skillFlexAfter','comboMode','dodgeProjectiles','dodgeTelegraphs'];if(keys.every(k=>p[k]===candidate[k])&&p.skills.join('|')===candidate.skills.join('|')){candidate.name=p.name;candidate.custom=false;break}}brain=candidate;saveBrain();writeBrainForm();updateBrainTicker()}
function writeBrainForm(){for(const k of ['targetMode','executePct','targetLock','chaseLeash','stance','retreatHp','reengageHp','surround','dangerSense','adaptAfter','adaptMode','slamMin','whirlMin','skillFlexAfter','comboMode'])if(brainInputs[k])brainInputs[k].value=brain[k];brainInputs.useCover.checked=brain.useCover;brainInputs.adaptEvasion.checked=brain.adaptEvasion!==false;brainInputs.skill1.value=brain.skills[0];brainInputs.skill2.value=brain.skills[1];brainInputs.skill3.value=brain.skills[2];brainInputs.dodgeProjectiles.checked=brain.dodgeProjectiles;brainInputs.dodgeTelegraphs.checked=brain.dodgeTelegraphs;refreshBrainValues()}
function refreshBrainValues(){valueEls.executePct.textContent=brainInputs.executePct.value+'%';valueEls.targetLock.textContent=brainInputs.targetLock.value+'s';valueEls.chaseLeash.textContent=brainInputs.chaseLeash.value+'s';valueEls.retreatHp.textContent=brainInputs.retreatHp.value+'%';valueEls.reengageHp.textContent=brainInputs.reengageHp.value+'%';valueEls.surround.textContent=brainInputs.surround.value;valueEls.adaptAfter.textContent=brainInputs.adaptAfter.value+'s';valueEls.slamMin.textContent=brainInputs.slamMin.value;valueEls.whirlMin.textContent=brainInputs.whirlMin.value;valueEls.skillFlexAfter.textContent=brainInputs.skillFlexAfter.value+'s';brainSummary.textContent=`${brain.name} • ${brain.targetMode.toUpperCase()} • ${brain.stance.toUpperCase()} • ${brain.comboMode.toUpperCase()}`}
Object.values(brainInputs).forEach(el=>el&&el.addEventListener('input',refreshBrainValues));document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.preset));
function openBrain(){pausedForBrain=true;writeBrainForm();brainPanel.style.display='block'}function closeBrainPanel(){brainPanel.style.display='none';pausedForBrain=false;last=performance.now()}
brainBtn.onclick=openBrain;closeBrain.onclick=closeBrainPanel;applyBrain.onclick=()=>{readBrainForm();closeBrainPanel()};applyReplay.onclick=()=>{readBrainForm();closeBrainPanel();beginRoom()};
function updateBrainTicker(){if(!brainTicker)return;const d=Math.round(localDangerScore());brainTicker.textContent=`${brain.name} • ${lastDecision} • DANGER ${d}`}
function setDecision(label){if(lastDecision!==label){lastDecision=label;brainDecisions++;updateBrainTicker()}}
function dangerThreshold(){return brain.dangerSense==='high'?38:brain.dangerSense==='low'?72:54}
function targetScore(e){const d=dist(P,e),hp=e.hp/e.max,fr=frustration.get(e.id)||0;let s=1000-d-fr*180;if(stalemateMode)s+=(1-hp)*500-d*.8;if(e.id===avoidTargetId&&roomClock<avoidUntil)s-=1800;if(brain.targetMode==='nearest')s+=340-d*.55;if(brain.targetMode==='threat'){if(e.type==='boom')s+=900;if(e.type==='necro')s+=680;if(e.type==='elite')s+=260;if(e.type==='boss')s+=190;if(e.type==='archer')s+=170}if(brain.targetMode==='ranged'){if(e.type==='archer')s+=760;if(e.type==='necro')s+=840}if(brain.targetMode==='support'){if(e.type==='necro')s+=1150;if(e.type==='archer')s+=330}if(brain.targetMode==='lowhp')s+=(1-hp)*980;if(brain.executePct>0&&hp<=brain.executePct/100)s+=950;return s}
function byId(id){return en.find(e=>!e.dead&&e.id===id)||null}
function pickTarget(force=false){let current=byId(lastTargetId),best=null,bs=-1e9;for(const e of en){if(e.dead)continue;const s=targetScore(e);if(s>bs){bs=s;best=e}}if(!best)return null;if(current&&!force&&roomClock<targetLockUntil&&current.id!==avoidTargetId){const cur=targetScore(current);if(bs-cur<520)return current;targetLockBreaks++}if(best.id!==lastTargetId){if(lastTargetId!==null)targetSwitches++;lastTargetId=best.id;targetLockUntil=roomClock+(brain.targetLock||0);chaseClock=0;pursuitTargetId=null;setDecision('TARGET '+cfg[best.type].label)}return best}
function dangerHits(e){if(e.type==='boom')return dist(P,e)<82;if(e.mode==='rupture')return dist(P,e)<160;if(e.mode==='cleave'){const dx=P.x-e.x,dy=P.y-e.y,d=len(dx,dy);if(d>102)return false;const a=Math.atan2(dy,dx),da=Math.atan2(Math.sin(a-e.facing),Math.cos(a-e.facing));return Math.abs(da)<.78}if(e.mode==='charge'&&e.chargeTarget){const dx=e.chargeTarget.x-e.x,dy=e.chargeTarget.y-e.y,l=len(dx,dy),ex=e.x+dx/l*(e.type==='elite'?155:230),ey=e.y+dy/l*(e.type==='elite'?155:230);return segmentPointDistance(P.x,P.y,e.x,e.y,ex,ey)<50}return false}
function dodgeVector(vx,vy,label){if(P.dodgeCd>0)return false;const l=len(vx,vy);P.vx+=vx/l*340;P.vy+=vy/l*340;P.dodge=.22;P.dodgeCd=1;dodges++;threatAvoids++;setDecision(label);announce(label,'#7fe9ff');ring(P.x,P.y,30,'#6adfff',3);return true}
function globalEngagementWatch(){const liveCount=en.filter(e=>!e.dead).length;if((roomClock>45||(liveCount===1&&roomClock>10))&&!hardCommit){hardCommit=true;stalemateMode=true;commitTargetId=lastTargetId;commitUntil=roomClock+999;commitEvents++;setDecision(liveCount===1?'FINISH LAST TARGET':'TIMEBOX COMMIT');announce(liveCount===1?'FINISH IT':'BRAIN GOES ALL-IN','#ffcf70')}if(roomClock<7||roomClock<globalAdaptCooldown)return;const t=byId(lastTargetId);if(!t)return;const dry=roomClock-lastMeaningfulDamageClock;if(dry<6.5)return;globalAdaptCooldown=roomClock+5.5;globalCommitCount++;commitTargetId=t.id;commitUntil=roomClock+3.6;commitEvents++;stalemateMode=true;targetLockUntil=roomClock+3.6;setDecision('GLOBAL COMMIT: NO DAMAGE');announce('BRAIN FORCES CONTACT','#ffcf70');if(globalCommitCount>=2&&dry>11){avoidTargetId=t.id;avoidUntil=roomClock+4;lastTargetId=null;switchEvents++}}
function tryEmergencyDodge(){const committed=(hardCommit||(commitTargetId!==null&&roomClock<commitUntil))&&P.hp/P.max>.055;if(brain.dodgeProjectiles&&!committed){const p=projectileThreat();if(p&&P.dodgeCd<=0){const l=len(p.vx,p.vy),side=(p.vx*(P.y-p.y)-p.vy*(P.x-p.x))>=0?1:-1;if(dodgeVector(-p.vy/l*side,p.vx/l*side,'SIDESTEP SHOT')){p.dodged=true;projectileDodges++;return true}}}if(brain.dodgeTelegraphs){const e=en.find(q=>!q.dead&&q.wind>0&&q.wind<.27&&dangerHits(q));if(e){const safe=safePointVector('RETREAT',e);if(dodgeVector(safe.x,safe.y,'EVADE TELEGRAPH'))return true}}return false}
function nearestRanged(){let best=null,bd=1e9;for(const e of en)if(!e.dead&&(e.type==='archer'||e.type==='necro')){const d=dist(P,e);if(d<bd){bd=d;best=e}}return best}
function coverVector(threat){if(!threat||!obstacles.length)return null;let best=null,bs=1e9;for(const o of obstacles){const dx=o.x-threat.x,dy=o.y-threat.y,l=len(dx,dy),px=o.x+dx/l*(o.r+P.r+14),py=o.y+dy/l*(o.r+P.r+14);if(pointBlocked(px,py))continue;const travel=Math.hypot(P.x-px,P.y-py),danger=localDangerScore(px,py);if(!hasLineOfSight(threat,{x:px,y:py},4)&&travel+danger*3<bs){bs=travel+danger*3;best={x:px-P.x,y:py-P.y}}}return best}
function moveToCover(dt,threat,label='SEEK COVER'){if(!brain.useCover||!threat||!obstacles.length||roomClock<coverCooldownUntil)return false;const cv=coverVector(threat);if(!cv||!hasLineOfSight(threat,P,3))return false;if(!covering){covering=true;coverMoves++;coverUntil=roomClock+1.15}if(roomClock>=coverUntil){covering=false;coverCooldownUntil=roomClock+1.45;return false}setDecision(label);steer(P,cv.x,cv.y,P.spd*1.06,dt,9);return true}
function shouldEnterRetreat(crowd,danger){const hp=P.hp/P.max;if(roomClock<retreatCooldownUntil&&hp>.12)return false;if((stalemateMode||hardCommit)&&hp>.055)return false;return hp<=brain.retreatHp/100||crowd.n>=brain.surround||danger>=dangerThreshold()}
function shouldExitRetreat(crowd,danger){const elapsed=roomClock-retreatSince,safe=crowd.n<=Math.max(1,brain.surround-2)&&danger<dangerThreshold()*.62;if(elapsed>4.6){retreatCooldownUntil=roomClock+1.25;return true}if(safe&&elapsed>2.0){retreatCooldownUntil=roomClock+.8;return true}if(safe&&P.hp/P.max>=brain.reengageHp/100){retreatCooldownUntil=roomClock+.65;return true}return false}
function updateRetreatState(crowd,danger,dt){if(!retreating&&shouldEnterRetreat(crowd,danger)){retreating=true;retreatSince=roomClock;retreatEvents++;setDecision(P.hp/P.max<=brain.retreatHp/100?'LOW HP RETREAT':'THREAT RETREAT')}else if(retreating&&shouldExitRetreat(crowd,danger)){retreating=false;setDecision('RE-ENGAGE');targetLockUntil=0}if(retreating){retreatTime+=dt;currentRetreatStreak+=dt;maxRetreatStreak=Math.max(maxRetreatStreak,currentRetreatStreak)}else currentRetreatStreak=0;return retreating}
function adaptTarget(t,reason='STALL'){adaptiveEvents++;const n=(frustration.get(t.id)||0)+1;frustration.set(t.id,n);const mode=brain.adaptMode||'hybrid';pursuitClock=0;pursuitBest=dist(P,t);if(mode==='switch'||(mode==='hybrid'&&n>=3)){avoidTargetId=t.id;avoidUntil=roomClock+Math.min(6,2.5+n*.8);lastTargetId=null;pursuitTargetId=null;switchEvents++;setDecision(`ADAPT SWITCH ${reason}`);announce('BRAIN SWITCHES TARGET','#ffd171');return'switch'}if(mode==='hybrid'&&n===2){flankTargetId=t.id;flankUntil=roomClock+2.8;flankEvents++;setDecision('ADAPT: FLANK');announce('BRAIN FLANKS','#ffd171');return'flank'}if((mode==='hybrid'&&n===3)||(mode==='intercept'&&n>=3)){commitTargetId=t.id;commitUntil=roomClock+3.2;commitEvents++;setDecision('ADAPT: COMMIT PURSUIT');announce('BRAIN COMMITS','#ffcf70');return'commit'}interceptTargetId=t.id;interceptUntil=roomClock+2.8;interceptEvents++;setDecision('ADAPT: INTERCEPT');announce('BRAIN INTERCEPTS','#ffd171');return'intercept'}
function observePursuit(t,dt){if(!t)return null;const d=dist(P,t),reach=Math.max(49,P.r+t.r+14);if(t.id!==pursuitTargetId){pursuitTargetId=t.id;pursuitClock=0;pursuitBest=d;chaseClock=0}if(d<=reach+12){pursuitClock=0;pursuitBest=d;chaseClock=0;return null}chaseClock+=dt;if(chaseClock>(brain.chaseLeash||5)){chaseClock=0;leashBreaks++;return adaptTarget(t,'LEASH')}if(!brain.adaptEvasion)return null;if(d<pursuitBest-14){pursuitBest=d;pursuitClock=0}else pursuitClock+=dt;if(pursuitClock<(brain.adaptAfter||3))return null;return adaptTarget(t,'STALL')}
function interceptVector(t){const lead=.95,ix=cl(t.x+t.vx*lead,55,W-55),iy=cl(t.y+t.vy*lead,70,H-65);return{x:ix-P.x,y:iy-P.y}}
function flankVector(t){const vx=t.vx,vy=t.vy,l=len(vx,vy),side=(t.id%2?1:-1),fx=cl(t.x-vy/l*85*side+t.vx*.45,55,W-55),fy=cl(t.y+vx/l*85*side+t.vy*.45,70,H-65);return{x:fx-P.x,y:fy-P.y}}
function positionForTarget(t,dt){const adaptation=observePursuit(t,dt);if(hardCommit){const dx=t.x-P.x,dy=t.y-P.y;setDecision('ALL-IN PURSUIT');steer(P,dx,dy,P.spd*1.34,dt,12);return}if(stalemateMode){const iv=interceptVector(t);setDecision('BREAK STALEMATE');steer(P,iv.x,iv.y,P.spd*1.18,dt,11);return}if(adaptation==='switch')return;const d=dist(P,t),dx=t.x-P.x,dy=t.y-P.y;if(commitTargetId===t.id&&roomClock<commitUntil){setDecision('COMMIT PURSUIT');steer(P,dx,dy,P.spd*1.32,dt,12);return}if(flankTargetId===t.id&&roomClock<flankUntil){const fv=flankVector(t);setDecision('FLANK TARGET');steer(P,fv.x,fv.y,P.spd*1.08,dt,10);return}if(interceptTargetId===t.id&&roomClock<interceptUntil){const iv=interceptVector(t);setDecision('CUT OFF TARGET');steer(P,iv.x,iv.y,P.spd*1.12,dt,10);return}const r=nearestRanged();if((retreating||localDangerScore()>dangerThreshold()*.72)&&moveToCover(dt,r,'SEEK COVER'))return;else if(roomClock>=coverUntil)covering=false;if(brain.stance==='kite'&&P.atk>.18&&d<128){const sv=safePointVector('RETREAT',t);setDecision('KITE SAFE ARC');steer(P,sv.x,sv.y,P.spd*1.04,dt,9);return}if(brain.stance==='balanced'&&P.atk>.28&&d<76){const sv=safePointVector('RETREAT',t);setDecision('RESET SPACING');steer(P,sv.x,sv.y,P.spd*.78,dt,7);return}setDecision('ENGAGE');steer(P,dx,dy,P.spd,dt,8)}
function updateSkillAges(dt){skillReadyAge.Slam=P.slam<=0?skillReadyAge.Slam+dt:0;skillReadyAge.Whirlwind=P.ww<=0?skillReadyAge.Whirlwind+dt:0}
function skillState(name,t,comboBoost=false){if(name==='Slash'){const ok=t&&P.atk<=0&&dist(P,t)<=Math.max(49,P.r+t.r+14);return{ok,reason:ok?'READY':'OUT OF RANGE'}}const range=name==='Slam'?105:69,cd=name==='Slam'?P.slam:P.ww,need=name==='Slam'?brain.slamMin:brain.whirlMin,count=near(range).length,age=skillReadyAge[name],flex=(brain.skillFlexAfter||2.5)*((stalemateMode||hardCommit)?.5:1),targetIn=t&&dist(P,t)<=range,priority=t&&(t.type==='boss'||t.type==='elite'),softNeed=Math.max(1,need-(comboBoost?1:0));if(cd>0)return{ok:false,reason:cd.toFixed(1)+'s',count,need:softNeed,age};if(count>=softNeed)return{ok:true,reason:'READY',count,need:softNeed,age};if(priority&&targetIn&&age>=flex*.45)return{ok:true,forced:true,reason:'ELITE OVERRIDE',count,need:softNeed,age};if(age>=flex&&count>=1)return{ok:true,forced:true,reason:'FLEX CAST',count,need:softNeed,age};return{ok:false,reason:`WAIT ${count}/${softNeed}`,count,need:softNeed,age}}
function nextComboFor(skill){if(brain.comboMode==='none')return null;if(brain.comboMode==='slamWhirl')return skill==='Slam'?'Whirlwind':null;if(brain.comboMode==='whirlSlam')return skill==='Whirlwind'?'Slam':null;if(brain.comboMode==='adaptive'){const density=near(105).length;if(skill==='Slam'&&density>=3)return'Whirlwind';if(skill==='Whirlwind'&&density<4)return'Slam'}return null}
function castSkill(name,t,forced=false,fromCombo=false){if(name==='Slam'){P.slam=7;P.wind=.52;skillReadyAge.Slam=0;skillCasts.Slam++;setDecision(forced?'FLEX CAST SLAM':'CAST SLAM');announce('SLAM WINDUP','#ffc056')}else if(name==='Whirlwind'){P.ww=5;P.spin=1.45;P.spinTick=0;skillReadyAge.Whirlwind=0;skillCasts.Whirlwind++;setDecision(forced?'FLEX WHIRLWIND':'CAST WHIRLWIND');announce('WHIRLWIND','#7edcff')}else if(name==='Slash'){P.atk=.78;const crit=rng()<.07;skillCasts.Slash++;setDecision('HEAVY SLASH');hit(t,R(36,46)*(crit?1.8:1),'Slash',crit,crit?17:7)}else return false;if(forced)forcedSkillCasts++;if(fromCombo)comboCasts++;const next=nextComboFor(name);if(next){comboPending=next;comboUntil=roomClock+2.1}else if(fromCombo){comboPending=null;comboUntil=0}return true}
function tryScheduledSkills(t,aoeOnly=false){if(comboPending&&roomClock<comboUntil){const st=skillState(comboPending,t,true);if(st.ok&&(!aoeOnly||comboPending!=='Slash'))return castSkill(comboPending,t,!!st.forced,true)}else if(comboPending){comboPending=null;comboUntil=0}for(const skill of brain.skills){if(aoeOnly&&skill==='Slash')continue;const st=skillState(skill,t,false);if(st.ok)return castSkill(skill,t,!!st.forced,false);if(skill!=='Slash'&&st.age>(brain.skillFlexAfter||2.5)+1.5)skillReadyWaste+=.035}return false}
loadBrain();writeBrainForm();updateBrainTicker();
