'use strict';
const brainPanel=document.getElementById('brainPanel'),brainSummary=document.getElementById('brainSummary'),closeBrain=document.getElementById('closeBrain'),applyBrain=document.getElementById('applyBrain'),applyReplay=document.getElementById('applyReplay');
const brainInputs={targetMode:document.getElementById('targetMode'),executePct:document.getElementById('executePct'),stance:document.getElementById('stance'),retreatHp:document.getElementById('retreatHp'),surround:document.getElementById('surround'),useCover:document.getElementById('useCover'),skill1:document.getElementById('skill1'),skill2:document.getElementById('skill2'),skill3:document.getElementById('skill3'),slamMin:document.getElementById('slamMin'),whirlMin:document.getElementById('whirlMin'),dodgeProjectiles:document.getElementById('dodgeProjectiles'),dodgeTelegraphs:document.getElementById('dodgeTelegraphs')};
const valueEls={executePct:document.getElementById('executeVal'),retreatHp:document.getElementById('retreatVal'),surround:document.getElementById('surroundVal'),slamMin:document.getElementById('slamVal'),whirlMin:document.getElementById('whirlVal')};
const PRESETS={berserker:{name:'BERSERKER',targetMode:'lowhp',executePct:35,stance:'chase',retreatHp:10,surround:8,useCover:false,skills:['Slam','Whirlwind','Slash'],slamMin:3,whirlMin:3,dodgeProjectiles:true,dodgeTelegraphs:true},balanced:{name:'BALANCED',targetMode:'threat',executePct:20,stance:'balanced',retreatHp:30,surround:5,useCover:true,skills:['Slam','Whirlwind','Slash'],slamMin:4,whirlMin:3,dodgeProjectiles:true,dodgeTelegraphs:true},tactician:{name:'TACTICIAN',targetMode:'support',executePct:25,stance:'balanced',retreatHp:40,surround:4,useCover:true,skills:['Whirlwind','Slam','Slash'],slamMin:5,whirlMin:3,dodgeProjectiles:true,dodgeTelegraphs:true},kiter:{name:'KITER',targetMode:'ranged',executePct:20,stance:'kite',retreatHp:50,surround:3,useCover:true,skills:['Whirlwind','Slash','Slam'],slamMin:5,whirlMin:2,dodgeProjectiles:true,dodgeTelegraphs:true}};
let brain={...PRESETS.balanced,skills:[...PRESETS.balanced.skills],custom:false};
function loadBrain(){try{const x=JSON.parse(localStorage.getItem('dopamineBrainV1'));if(x&&x.targetMode)brain={...brain,...x,skills:Array.isArray(x.skills)?x.skills:brain.skills}}catch(e){}}
function saveBrain(){try{localStorage.setItem('dopamineBrainV1',JSON.stringify(brain))}catch(e){}}
function setPreset(k,write=true){const p=PRESETS[k];brain={...p,skills:[...p.skills],custom:false};if(write){writeBrainForm();saveBrain();updateBrainTicker()}}
function readBrainForm(){const candidate={name:'CUSTOM',targetMode:brainInputs.targetMode.value,executePct:+brainInputs.executePct.value,stance:brainInputs.stance.value,retreatHp:+brainInputs.retreatHp.value,surround:+brainInputs.surround.value,useCover:brainInputs.useCover.checked,skills:[brainInputs.skill1.value,brainInputs.skill2.value,brainInputs.skill3.value],slamMin:+brainInputs.slamMin.value,whirlMin:+brainInputs.whirlMin.value,dodgeProjectiles:brainInputs.dodgeProjectiles.checked,dodgeTelegraphs:brainInputs.dodgeTelegraphs.checked,custom:true};for(const p of Object.values(PRESETS)){if(p.targetMode===candidate.targetMode&&p.executePct===candidate.executePct&&p.stance===candidate.stance&&p.retreatHp===candidate.retreatHp&&p.surround===candidate.surround&&p.useCover===candidate.useCover&&p.slamMin===candidate.slamMin&&p.whirlMin===candidate.whirlMin&&p.dodgeProjectiles===candidate.dodgeProjectiles&&p.dodgeTelegraphs===candidate.dodgeTelegraphs&&p.skills.join('|')===candidate.skills.join('|')){candidate.name=p.name;candidate.custom=false;break}}brain=candidate;saveBrain();updateBrainTicker()}
function writeBrainForm(){brainInputs.targetMode.value=brain.targetMode;brainInputs.executePct.value=brain.executePct;brainInputs.stance.value=brain.stance;brainInputs.retreatHp.value=brain.retreatHp;brainInputs.surround.value=brain.surround;brainInputs.useCover.checked=brain.useCover;brainInputs.skill1.value=brain.skills[0];brainInputs.skill2.value=brain.skills[1];brainInputs.skill3.value=brain.skills[2];brainInputs.slamMin.value=brain.slamMin;brainInputs.whirlMin.value=brain.whirlMin;brainInputs.dodgeProjectiles.checked=brain.dodgeProjectiles;brainInputs.dodgeTelegraphs.checked=brain.dodgeTelegraphs;refreshBrainValues()}
function refreshBrainValues(){valueEls.executePct.textContent=brainInputs.executePct.value+'%';valueEls.retreatHp.textContent=brainInputs.retreatHp.value+'%';valueEls.surround.textContent=brainInputs.surround.value;valueEls.slamMin.textContent=brainInputs.slamMin.value;valueEls.whirlMin.textContent=brainInputs.whirlMin.value;brainSummary.textContent=`${brain.name} • ${brain.targetMode.toUpperCase()} targeting • ${brain.stance.toUpperCase()} stance`}
Object.values(brainInputs).forEach(el=>el.addEventListener('input',refreshBrainValues));document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.preset));
function openBrain(){pausedForBrain=true;writeBrainForm();brainPanel.style.display='block'}function closeBrainPanel(){brainPanel.style.display='none';pausedForBrain=false;last=performance.now()}
brainBtn.onclick=openBrain;closeBrain.onclick=closeBrainPanel;applyBrain.onclick=()=>{readBrainForm();closeBrainPanel()};applyReplay.onclick=()=>{readBrainForm();closeBrainPanel();beginRoom()};
function updateBrainTicker(){if(!brainTicker)return;brainTicker.textContent=`BRAIN: ${brain.name} • ${brain.targetMode.toUpperCase()} • ${brain.stance.toUpperCase()} • ${lastDecision}`}
function setDecision(label){if(lastDecision!==label){lastDecision=label;brainDecisions++;updateBrainTicker()}}
function targetScore(e){const d=dist(P,e),hp=e.hp/e.max;let s=1000-d;if(brain.targetMode==='nearest')s+=300-d*.5;if(brain.targetMode==='threat'){if(e.type==='boom')s+=850;if(e.type==='necro')s+=640;if(e.type==='elite')s+=240;if(e.type==='boss')s+=170;if(e.type==='archer')s+=150}if(brain.targetMode==='ranged'){if(e.type==='archer')s+=700;if(e.type==='necro')s+=800}if(brain.targetMode==='support'){if(e.type==='necro')s+=1100;if(e.type==='archer')s+=300}if(brain.targetMode==='lowhp')s+=(1-hp)*900;if(brain.executePct>0&&hp<=brain.executePct/100)s+=900;return s}
function pickTarget(){let best=null,bs=-1e9;for(const e of en){if(e.dead)continue;const s=targetScore(e);if(s>bs){bs=s;best=e}}if(best&&best.id!==lastTargetId){if(lastTargetId!==null)targetSwitches++;lastTargetId=best.id;setDecision('TARGET '+cfg[best.type].label)}return best}
function dangerHits(e){if(e.type==='boom')return dist(P,e)<82;if(e.mode==='rupture')return dist(P,e)<160;if(e.mode==='cleave'){const dx=P.x-e.x,dy=P.y-e.y,d=len(dx,dy);if(d>102)return false;const a=Math.atan2(dy,dx),da=Math.atan2(Math.sin(a-e.facing),Math.cos(a-e.facing));return Math.abs(da)<.78}if(e.mode==='charge'&&e.chargeTarget){const dx=e.chargeTarget.x-e.x,dy=e.chargeTarget.y-e.y,l=len(dx,dy),ex=e.x+dx/l*(e.type==='elite'?155:230),ey=e.y+dy/l*(e.type==='elite'?155:230);return segmentPointDistance(P.x,P.y,e.x,e.y,ex,ey)<50}return false}
function dodgeVector(vx,vy,label){if(P.dodgeCd>0)return false;const l=len(vx,vy);P.vx+=vx/l*340;P.vy+=vy/l*340;P.dodge=.22;P.dodgeCd=1;dodges++;setDecision(label);announce(label,'#7fe9ff');ring(P.x,P.y,30,'#6adfff',3);return true}
function tryEmergencyDodge(){if(brain.dodgeProjectiles){const p=projectileThreat();if(p&&P.dodgeCd<=0){const l=len(p.vx,p.vy),side=(p.vx*(P.y-p.y)-p.vy*(P.x-p.x))>=0?1:-1;if(dodgeVector(-p.vy/l*side,p.vx/l*side,'SIDESTEP SHOT')){p.dodged=true;projectileDodges++;return true}}}if(brain.dodgeTelegraphs){const e=en.find(q=>!q.dead&&q.wind>0&&q.wind<.23&&dangerHits(q));if(e){let dx=P.x-e.x,dy=P.y-e.y;if(e.mode==='charge'){const l=len(dx,dy),side=rng()<.5?-1:1;dx=-dy/l*side;dy=(P.x-e.x)/l*side}if(dodgeVector(dx,dy,'EVADE TELEGRAPH'))return true}}return false}
function nearestRanged(){let best=null,bd=1e9;for(const e of en)if(!e.dead&&(e.type==='archer'||e.type==='necro')){const d=dist(P,e);if(d<bd){bd=d;best=e}}return best}
function coverVector(threat){if(!threat||!obstacles.length)return null;let best=null,bs=1e9;for(const o of obstacles){const dx=o.x-threat.x,dy=o.y-threat.y,l=len(dx,dy),px=o.x+dx/l*(o.r+P.r+12),py=o.y+dy/l*(o.r+P.r+12),travel=Math.hypot(P.x-px,P.y-py);if(travel<bs){bs=travel;best={x:px-P.x,y:py-P.y}}}return best}
function shouldRetreat(crowd){return P.hp/P.max<=brain.retreatHp/100||crowd.n>=brain.surround}
function positionForTarget(t,dt){const d=dist(P,t),dx=t.x-P.x,dy=t.y-P.y;if(brain.useCover&&(brain.stance==='kite'||P.hp/P.max<brain.retreatHp/100)){const r=nearestRanged(),cv=coverVector(r);if(cv&&r&&hasLineOfSight(r,P,3)){if(!covering)coverMoves++;covering=true;setDecision('SEEK COVER');steer(P,cv.x,cv.y,P.spd*1.05,dt,9);return}else covering=false}if(brain.stance==='kite'&&P.atk>.18&&d<115){setDecision('KITE WINDOW');steer(P,-dx,-dy,P.spd*1.05,dt,9);return}if(brain.stance==='balanced'&&P.atk>.28&&d<72){setDecision('RESET SPACING');steer(P,-dx,-dy,P.spd*.72,dt,7);return}setDecision('ENGAGE');steer(P,dx,dy,P.spd,dt,8)}
function canSkill(name,t){if(name==='Slam')return P.slam<=0&&near(105).length>=brain.slamMin;if(name==='Whirlwind')return P.ww<=0&&near(69).length>=brain.whirlMin;if(name==='Slash')return t&&P.atk<=0&&dist(P,t)<=Math.max(49,P.r+t.r+14);return false}
function castSkill(name,t){if(name==='Slam'){P.slam=7;P.wind=.52;skillCasts.Slam++;setDecision('CAST SLAM');announce('SLAM WINDUP','#ffc056');return true}if(name==='Whirlwind'){P.ww=5;P.spin=1.45;P.spinTick=0;skillCasts.Whirlwind++;setDecision('CAST WHIRLWIND');announce('WHIRLWIND','#7edcff');return true}if(name==='Slash'){P.atk=.78;const crit=rng()<.07;skillCasts.Slash++;setDecision('HEAVY SLASH');hit(t,R(36,46)*(crit?1.8:1),'Slash',crit,crit?17:7);return true}return false}
loadBrain();writeBrainForm();updateBrainTicker();