function dodgeVector(vx,vy,label='DODGE'){if(P.dodgeCd>0)return false;const l=len(vx,vy);P.vx+=vx/l*340;P.vy+=vy/l*340;P.dodge=.22;P.dodgeCd=1.0;dodges++;announce(label,'#7fe9ff');ring(P.x,P.y,30,'#6adfff',3);return true}
function dodgeFromEntity(e){let dx=P.x-e.x,dy=P.y-e.y;if((e.type==='boss'||e.type==='elite')&&e.mode==='charge'){const l=len(dx,dy),side=rng()<.5?-1:1;return dodgeVector(-dy/l*side,dx/l*side,'SIDESTEP')}return dodgeVector(dx,dy,'DODGE')}
function dodgeProjectile(p){if(P.dodgeCd>0)return false;const l=len(p.vx,p.vy),side=(p.vx*(P.y-p.y)-p.vy*(P.x-p.x))>=0?1:-1;const ok=dodgeVector(-p.vy/l*side,p.vx/l*side,'SIDESTEP');if(ok){p.dodged=true;projectileDodges++}return ok}
function bossHazardHits(e){if(e.mode==='rupture')return dist(P,e)<160;if(e.mode==='cleave'){const dx=P.x-e.x,dy=P.y-e.y,d=len(dx,dy);if(d>102)return false;const a=Math.atan2(dy,dx),da=Math.atan2(Math.sin(a-e.facing),Math.cos(a-e.facing));return Math.abs(da)<.78}if(e.mode==='charge'&&e.chargeTarget){const dx=e.chargeTarget.x-e.x,dy=e.chargeTarget.y-e.y,l=len(dx,dy),ex=e.x+dx/l*230,ey=e.y+dy/l*230;return segmentPointDistance(P.x,P.y,e.x,e.y,ex,ey)<50}return false}
function upP(dt){P.hp=Math.min(P.max,P.hp+2.2*dt);P.atk=Math.max(0,P.atk-dt);P.ww=Math.max(0,P.ww-dt);P.slam=Math.max(0,P.slam-dt);P.dodge=Math.max(0,P.dodge-dt);P.dodgeCd=Math.max(0,P.dodgeCd-dt);P.retreat=Math.max(0,P.retreat-dt);if(P.dead)return;
 const pThreat=projectileThreat();if(pThreat&&dodgeProjectile(pThreat))return;
 const threat=en.find(e=>!e.dead&&e.wind>0&&e.wind<.23&&((e.type==='boom'&&dist(P,e)<82)||(e.type==='boss'&&bossHazardHits(e))||(e.type==='elite'&&e.mode==='charge'&&bossHazardHits(e))));if(threat&&dodgeFromEntity(threat))return;
 if(P.wind>0){P.wind-=dt;if(P.wind<=0){announce('GROUND SLAM','#ffc056');ring(P.x,P.y,105,'#ffc056',7);for(const e of near(105))hit(e,175,'Ground Slam',false,36)}return}
 if(P.spin>0){P.spin-=dt;P.spinTick-=dt;const t=target();if(t)steer(P,t.x-P.x,t.y-P.y,P.spd*.72,dt,10);if(P.spinTick<=0){P.spinTick=.24;for(const e of near(69))hit(e,30,'Whirlwind',false,9)}return}
 const crowd=crowdVector();maxSurround=Math.max(maxSurround,crowd.n);if(crowd.n>=5&&P.ww>1.15&&P.slam>1.15){P.retreat=.52;kiteTime+=dt;steer(P,P.x-crowd.x,P.y-crowd.y,P.spd*1.08,dt,10);return}
 const t=target();if(!t)return;if(P.slam<=0&&near(105).length>=4){P.slam=7;P.wind=.52;announce('SLAM WINDUP','#ffc056');return}if(P.ww<=0&&near(69).length>=3){P.ww=5;P.spin=1.45;P.spinTick=0;announce('WHIRLWIND','#7edcff');return}
 const d=dist(P,t),dx=t.x-P.x,dy=t.y-P.y,l=len(dx,dy);P.facing=Math.atan2(dy,dx);if(d<=Math.max(49,P.r+t.r+14)&&P.atk<=0){P.atk=.78;const crit=rng()<.07;hit(t,R(36,46)*(crit?1.8:1),'Slash',crit,crit?17:7)}else steer(P,dx,dy,P.spd,dt,8)}
function resolveBoss(e){if(e.mode==='cleave'){ring(e.x,e.y,102,'#ff653a',7);if(bossHazardHits(e))takeDamage(110,true)}else if(e.mode==='rupture'){ring(e.x,e.y,160,'#ff9d3d',7);if(dist(P,e)<160)takeDamage(86,true)}else if(e.mode==='charge'){const sx=e.x,sy=e.y,tx=e.chargeTarget?.x??P.x,ty=e.chargeTarget?.y??P.y,dx=tx-sx,dy=ty-sy,l=len(dx,dy),ex=sx+dx/l*230,ey=sy+dy/l*230;e.vx+=dx/l*540;e.vy+=dy/l*540;arcs.push({charge:true,x:sx,y:sy,x2:ex,y2:ey,life:.22,max:.22,col:'#ff4f3f',w:12});if(segmentPointDistance(P.x,P.y,sx,sy,ex,ey)<48)takeDamage(125,true)}e.mode='';e.chargeTarget=null;threatEl.textContent=roomName+(roomMod?' • '+roomMod:'')+` • threat ${roomBudget.toFixed(0)}`}
function startBossMove(e){const r=rng();if(r<.34)e.mode='cleave';else if(r<.68)e.mode='rupture';else e.mode='charge';e.wind=e.mode==='rupture'?.92:.74;e.special=R(2.9,4.2);e.facing=Math.atan2(P.y-e.y,P.x-e.x);if(e.mode==='charge')e.chargeTarget={x:P.x,y:P.y};threatEl.textContent='Goremaw: '+e.mode.toUpperCase()}
function startEliteCharge(e){e.mode='charge';e.wind=.58;e.special=R(4.4,5.8);e.chargeTarget={x:P.x,y:P.y};e.facing=Math.atan2(P.y-e.y,P.x-e.x);threatEl.textContent='Frenzied Elite: BULL RUSH'}
function resolveEliteCharge(e){const sx=e.x,sy=e.y,tx=e.chargeTarget?.x??P.x,ty=e.chargeTarget?.y??P.y,dx=tx-sx,dy=ty-sy,l=len(dx,dy),ex=sx+dx/l*155,ey=sy+dy/l*155;e.vx+=dx/l*430;e.vy+=dy/l*430;arcs.push({charge:true,x:sx,y:sy,x2:ex,y2:ey,life:.18,max:.18,col:'#ffb03e',w:9});if(segmentPointDistance(P.x,P.y,sx,sy,ex,ey)<42)takeDamage(72,true);e.mode='';e.chargeTarget=null}
function upE(e,dt){if(e.dead||P.dead)return;e.atk=Math.max(0,e.atk-dt);e.special=Math.max(0,e.special-dt);let d=dist(e,P);
 if(e.type==='boom'){if(e.wind>0){e.wind-=dt;if(e.wind<=0){ring(e.x,e.y,80,'#ff3d25',7);if(d<80)takeDamage(e.dmg,true);e.dead=true;burst(e.x,e.y,'#ff4d2d',12)}return}if(d<e.range+5){e.wind=.82;return}}
 if(e.type==='necro'&&e.special<=0){e.special=5.4;if(en.filter(q=>!q.dead).length<35){spawn('rot',cl(e.x+R(-55,55),25,W-25),cl(e.y+R(-55,55),45,H-30));announce('RAISE DEAD','#b887f2');ring(e.x,e.y,120,'#9b6fd3',2)}}
 if(e.type==='boss'){if(!e.enraged&&e.hp/e.max<=.3){e.enraged=true;e.spd*=1.22;e.period*=.78;announce('GOREMAW ENRAGED','#ff4b4b')}if(e.wind>0){e.wind-=dt;if(e.wind<=0)resolveBoss(e);return}if(e.special<=0){startBossMove(e);return}}
 if(e.type==='elite'){const k=Math.floor((1-e.hp/e.max)/.2),m=1+k*.08;e.spd=e.baseSpd*m;e.period=e.basePeriod/m;if(k>=3&&!e.enraged){e.enraged=true;announce('ELITE FRENZY','#ff9d35')}if(e.wind>0){e.wind-=dt;if(e.wind<=0)resolveEliteCharge(e);return}if(e.special<=0&&d<230){startEliteCharge(e);return}}
 if(e.type==='archer'||e.type==='necro'){const pref=e.type==='archer'?168:152,min=e.type==='archer'?116:106,dx=P.x-e.x,dy=P.y-e.y,l=len(dx,dy),los=hasLineOfSight(e,P,3);if(!los){const side=e.strafe;steer(e,-dy/l*side,dx/l*side,e.spd*.95,dt,8)}else if(d<min)steer(e,-dx,-dy,e.spd*1.1,dt,8);else if(d>pref+34)steer(e,dx,dy,e.spd,dt,7);else{steer(e,-dy/l*e.strafe,dx/l*e.strafe,e.spd*.72,dt,5)}if(los&&d<=e.range&&e.atk<=0){e.atk=e.period*(roomMod==='SHARPSHOOTERS'?.82:1);fireProjectile(e,roomMod==='SHARPSHOOTERS'?290:(e.type==='necro'?195:238))}return}
 const dx=P.x-e.x,dy=P.y-e.y;e.facing=Math.atan2(dy,dx);if(d>e.range)steer(e,dx,dy,e.spd,dt,7);if(d<=e.range&&e.atk<=0){e.atk=e.period;takeDamage(e.dmg,false)}}
function updateProjectiles(dt){for(const p of projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;for(const o of obstacles)if(Math.hypot(p.x-o.x,p.y-o.y)<o.r+p.r){p.life=0;burst(p.x,p.y,p.col,3);break}if(p.life>0&&Math.hypot(p.x-P.x,p.y-P.y)<p.r+P.r){takeDamage(p.damage,false);p.life=0;ring(p.x,p.y,15,p.col,2)}}projectiles=projectiles.filter(p=>p.life>0&&p.x>-25&&p.x<W+25&&p.y>-25&&p.y<H+25)}
function roomGrade(win,sec){if(!win)return'RUN ENDED';let score=100;score-=Math.min(35,taken/14);score-=Math.max(0,sec-18)*.65;score+=Math.min(8,dodges*1.4);if(firstKillSec!==null&&firstKillSec>3)score-=8;return score>=92?'S':score>=82?'A':score>=70?'B':'C'}
function finish(win){active=false;const sec=roomClock,total=Object.values(dmg).reduce((a,b)=>a+b,0),grade=roomGrade(win,sec),lines=[`Depth             ${depth}`,`Room              ${roomName}${roomMod?' / '+roomMod:''}`,`Threat budget     ${roomBudget.toFixed(0)}`,`Duration          ${sec.toFixed(1)}s`,`First kill        ${firstKillSec===null?'—':firstKillSec.toFixed(1)+'s'}`,`Damage dealt      ${total|0}`,`Damage taken      ${taken|0}`,`Kills             ${kills}`,`Danger dodges     ${dodges}`,`Projectile dodges ${projectileDodges}`,`Kite time         ${kiteTime.toFixed(1)}s`,`Max surround      ${maxSurround}`,`Biggest hit       ${biggest|0}`,''];Object.entries(dmg).sort((a,b)=>b[1]-a[1]).forEach(([k,v])=>lines.push(`${k.padEnd(17)} ${total?(v/total*100).toFixed(1):0}%`));resultEl.textContent=win?'ROOM CLEARED':'DEFEAT';resultEl.className='result '+(win?'win':'loss');gradeEl.textContent=win?`COMBAT GRADE ${grade}`:'THE DEPTH WON';statsEl.textContent=lines.join('\n');goBtn.textContent=win?'DESCEND TO '+(depth+1):'RETRY DEPTH '+depth;overlayEl.style.display=SELFTEST?'none':'flex';nextBtn.disabled=false;if(SOAK&&win){depth++;setTimeout(beginRoom,5)}}
