'use strict';
const C=document.getElementById('c'),X=C.getContext('2d'),stage=document.getElementById('stage');
const depthEl=document.getElementById('depth'),threatEl=document.getElementById('threat'),hpEl=document.getElementById('hp'),spdEl=document.getElementById('spd'),eventEl=document.getElementById('event'),overlayEl=document.getElementById('overlay'),resultEl=document.getElementById('result'),statsEl=document.getElementById('stats'),goBtn=document.getElementById('go'),nextBtn=document.getElementById('next');
const skillEls={Slash:document.getElementById('sSlash'),Whirlwind:document.getElementById('sWhirl'),Slam:document.getElementById('sSlam')};
const params=new URLSearchParams(location.search),SELFTEST=params.has('selftest'),SOAK=params.has('soak');
let W=0,H=0,DPR=1,speed=SOAK?12:1,depth=1,active=false,last=performance.now(),en=[],projectiles=[],obstacles=[],fx=[],nums=[],arcs=[],freeze=0,eventTimer=0,shake=0,kills=0,taken=0,dodges=0,start=0,dmg={},biggest=0,roomName='',roomMod='';
let runtimeErrors=[];window.addEventListener('error',e=>{runtimeErrors.push(e.message);threatEl.textContent='Runtime error: '+e.message;threatEl.style.color='#ff7b83'});
const P={x:0,y:0,vx:0,vy:0,hp:500,max:500,r:17,spd:128,atk:0,ww:0,slam:0,spin:0,spinTick:0,wind:0,dead:false,dodge:0,dodgeCd:0,facing:0,retreat:0};
const cfg={
 rot:{hp:55,dmg:10,spd:92,r:10,col:'#76c44e',range:39,period:.68,cost:1,unlock:1,label:'SWARMER'},
 guard:{hp:225,dmg:26,spd:50,r:17,col:'#c8c5ba',range:46,period:1.22,cost:3,unlock:1,label:'BONEGUARD'},
 archer:{hp:82,dmg:16,spd:72,r:12,col:'#d3568e',range:180,period:1.5,cost:2.5,unlock:2,label:'ARCHER'},
 boom:{hp:50,dmg:105,spd:118,r:11,col:'#ff5838',range:40,period:9,cost:2,unlock:3,label:'EXPLODER'},
 necro:{hp:160,dmg:13,spd:58,r:14,col:'#9460d1',range:165,period:1.9,cost:4.5,unlock:4,label:'NECROMANCER'},
 elite:{hp:780,dmg:28,spd:64,r:23,col:'#efa333',range:52,period:1.15,cost:9,unlock:5,label:'FRENZIED ELITE'},
 boss:{hp:1800,dmg:16,spd:56,r:34,col:'#b5262a',range:62,period:1.48,cost:18,unlock:10,label:'GOREMAW'}
};
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=Math.max(320,stage.clientWidth);H=Math.max(360,stage.clientHeight);C.width=Math.max(1,W*DPR);C.height=Math.max(1,H*DPR);X.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const R=(a,b)=>a+Math.random()*(b-a),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),len=(x,y)=>Math.hypot(x,y)||1;
function announce(t,c='#fff'){eventEl.textContent=t;eventEl.style.color=c;eventEl.classList.add('show');eventTimer=.48}
function difficultyScale(){return{hp:1+Math.max(0,depth-1)*.055,dmg:1+Math.max(0,depth-1)*.035,spd:1+Math.min(.28,Math.max(0,depth-1)*.008)}}
function spawn(type,x,y){const c=cfg[type],s=difficultyScale(),e={type,x,y,vx:0,vy:0,hp:c.hp*s.hp,max:c.hp*s.hp,dmg:c.dmg*s.dmg,spd:c.spd*s.spd,baseSpd:c.spd*s.spd,r:c.r,col:c.col,range:c.range,period:c.period,basePeriod:c.period,atk:R(0,.45),special:R(2.4,4.2),wind:0,mode:'',dead:false,enraged:false,strafe:Math.random()<.5?-1:1,chargeTarget:null};en.push(e);return e}
function randomRoomMod(){if(depth<4)return'';const r=Math.random();if(r<.22)return'SWARMING';if(r<.42)return'FRENZY';if(r<.60)return'SHARPSHOOTERS';if(r<.76)return'ARMORED';return''}
function generateRoom(){roomMod=randomRoomMod();const bossRoom=depth%10===0;const budget=8+depth*2.0+Math.pow(depth,.75)*1.8;const types=[];if(bossRoom){if(depth<20)roomMod='';types.push('boss');let left=depth>=20?Math.max(0,(budget-18)*.45):0;while(left>=1){const pool=['rot','guard',depth>=20?'archer':'rot'];const t=pool[(Math.random()*pool.length)|0],cost=cfg[t].cost;if(cost>left)break;types.push(t);left-=cost}roomName='BOSS DEPTH';}
 else{let left=budget;const allowed=Object.keys(cfg).filter(t=>t!=='boss'&&cfg[t].unlock<=depth);if(depth>=5&&Math.random()<Math.min(.45,.08+depth*.015)){types.push('elite');left-=cfg.elite.cost}let guard=0;while(left>=1&&guard++<80){let pool=allowed.filter(t=>t!=='elite'&&cfg[t].cost<=left);if(roomMod==='SWARMING'&&Math.random()<.5)pool=['rot'];if(roomMod==='SHARPSHOOTERS'&&depth>=2&&Math.random()<.5)pool=['archer'];if(!pool.length)break;const t=pool[(Math.random()*pool.length)|0];types.push(t);left-=cfg[t].cost}roomName=['CHOKED HALL','BROKEN COURT','KILLING FLOOR','ASHEN VAULT','IRON RING'][(Math.random()*5)|0];}
 if(roomMod==='ARMORED')for(const t of types){} return types}
function makeObstacles(){obstacles=[];const count=depth<3?1:Math.min(5,1+((depth/4)|0));for(let i=0;i<count;i++){for(let tries=0;tries<30;tries++){const o={x:R(80,W-80),y:R(80,H-105),r:R(24,42)};if(Math.hypot(o.x-W/2,o.y-H*.52)>100&&obstacles.every(q=>dist(o,q)>o.r+q.r+45)){obstacles.push(o);break}}}}
function placeTypes(types){const groups=Math.min(5,2+((types.length/7)|0));for(let i=0;i<types.length;i++){const g=i%groups,a=g/groups*Math.PI*2+R(-.35,.35),rr=R(Math.min(W,H)*.34,Math.min(W,H)*.48),cx=W*.5+Math.cos(a)*rr,cy=H*.5+Math.sin(a)*rr;spawn(types[i],cl(cx+R(-45,45),35,W-35),cl(cy+R(-45,45),50,H-50))}}
function beginRoom(){en=[];projectiles=[];fx=[];nums=[];arcs=[];P.x=W*.5;P.y=H*.52;P.vx=P.vy=0;P.hp=P.max;P.dead=false;P.atk=P.ww=P.slam=P.spin=P.wind=P.dodge=P.dodgeCd=P.retreat=0;kills=taken=dodges=0;biggest=0;dmg={Slash:0,Whirlwind:0,'Ground Slam':0};freeze=shake=0;makeObstacles();const types=generateRoom();placeTypes(types);if(roomMod==='FRENZY')for(const e of en)e.spd*=1.13;if(roomMod==='ARMORED')for(const e of en){e.hp*=1.28;e.max=e.hp}active=true;start=performance.now();overlayEl.style.display='none';nextBtn.disabled=true;announce('DEPTH '+depth,'#9bd7ff');threatEl.textContent=roomName+(roomMod?' • '+roomMod:'')+' • threat '+types.length;hud()}
function target(){let best=null,bs=-1e9;for(const e of en){if(e.dead)continue;let s=1000-dist(P,e)+(e.type==='boom'?760:e.type==='necro'?590:e.type==='archer'?160:e.type==='boss'?100:e.type==='elite'?85:0);if(s>bs){bs=s;best=e}}return best}
function near(r){return en.filter(e=>!e.dead&&dist(P,e)<=r)}
function ring(x,y,m,c,w=5){fx.push({kind:'ring',x,y,r:0,m,life:.32,max:.32,col:c,w})}function burst(x,y,c,n=5){for(let i=0;i<n;i++)fx.push({kind:'p',x,y,vx:R(-110,110),vy:R(-110,110),life:R(.18,.4),max:.4,col:c})}
function heal(a){P.hp=Math.min(P.max,P.hp+a)}function kill(e){if(e.dead)return;e.dead=true;kills++;heal(5);burst(e.x,e.y,e.col,9);ring(e.x,e.y,28,e.col,2)}
function hit(e,a,k,crit=false,kb=0){if(!e||e.dead)return;dmg[k]+=a;biggest=Math.max(biggest,a);e.hp-=a;nums.push({x:e.x,y:e.y-e.r-8,t:(a|0)+(crit?'!':''),life:.6,col:crit?'#ffd46a':'#fff',big:crit||a>150});burst(e.x,e.y,e.col,crit?8:4);if(k==='Slash'){arcs.push({x:P.x,y:P.y,a:P.facing,life:.13,max:.13,col:crit?'#ffe273':'#d9efff',w:crit?8:5});if(crit){freeze=.04;shake=4}}if(k==='Ground Slam'){freeze=.07;shake=8}if(k==='Whirlwind')shake=Math.max(shake,1.6);if(kb){const dx=e.x-P.x,dy=e.y-P.y,l=len(dx,dy);e.vx+=dx/l*kb*6;e.vy+=dy/l*kb*6}if(e.hp<=0)kill(e)}
function takeDamage(a,special=false){if(P.dead||P.dodge>0)return;const dealt=a*(special?.90:.80);P.hp-=dealt;taken+=dealt;nums.push({x:P.x,y:P.y-25,t:'-'+(dealt|0),life:.6,col:'#ff727b',big:true});burst(P.x,P.y,'#ff6372',5);shake=Math.max(shake,special?6:3);if(P.hp<=0){P.dead=true;active=false;finish(false)}}
function fireProjectile(e,speedP=225){const dx=P.x-e.x,dy=P.y-e.y,l=len(dx,dy),lead=.15;projectiles.push({x:e.x,y:e.y,vx:(dx/l)*speedP+P.vx*lead,vy:(dy/l)*speedP+P.vy*lead,r:e.type==='necro'?6:4,life:3,damage:e.dmg,col:e.col,owner:e.type,type:e.type==='necro'?'orb':'arrow'})}
function collideObstacle(body){for(const o of obstacles){const dx=body.x-o.x,dy=body.y-o.y,l=Math.hypot(dx,dy)||.001,min=o.r+body.r+3;if(l<min){const nx=dx/l,ny=dy/l,p=min-l;body.x+=nx*p;body.y+=ny*p;const vn=body.vx*nx+body.vy*ny;if(vn<0){body.vx-=vn*1.4*nx;body.vy-=vn*1.4*ny}}}}
function applyWorldPhysics(dt){const live=en.filter(e=>!e.dead);for(const e of live){e.x+=e.vx*dt;e.y+=e.vy*dt;e.vx*=Math.pow(.07,dt);e.vy*=Math.pow(.07,dt)}P.x+=P.vx*dt;P.y+=P.vy*dt;P.vx*=Math.pow(.05,dt);P.vy*=Math.pow(.05,dt);for(let pass=0;pass<6;pass++){for(let i=0;i<live.length;i++){const a=live[i];for(let j=i+1;j<live.length;j++){const b=live[j],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||.001,min=a.r+b.r+12;if(l<min){const nx=dx/l,ny=dy/l,p=min-l,ma=a.type==='boss'?4:a.type==='elite'?2:1,mb=b.type==='boss'?4:b.type==='elite'?2:1,total=ma+mb,moveA=mb/total,moveB=ma/total;a.x-=nx*p*moveA;b.x+=nx*p*moveB;a.y-=ny*p*moveA;b.y+=ny*p*moveB;a.vx-=nx*24*moveA;b.vx+=nx*24*moveB;a.vy-=ny*24*moveA;b.vy+=ny*24*moveB}}const dx=a.x-P.x,dy=a.y-P.y,l=Math.hypot(dx,dy)||.001,min=a.r+P.r+9;if(l<min){const nx=dx/l,ny=dy/l,p=min-l,m=a.type==='boss'?4:a.type==='elite'?2:1;a.x+=nx*p*(1/(1+m));a.y+=ny*p*(1/(1+m));P.x-=nx*p*(m/(1+m));P.y-=ny*p*(m/(1+m))}}}for(const e of live){collideObstacle(e);e.x=cl(e.x,e.r+3,W-e.r-3);e.y=cl(e.y,e.r+30,H-e.r-26)}collideObstacle(P);P.x=cl(P.x,P.r+3,W-P.r-3);P.y=cl(P.y,P.r+30,H-P.r-26)}
function steer(body,dx,dy,spd,dt,weight=7){let l=len(dx,dy),ux=dx/l,uy=dy/l;for(const o of obstacles){const ox=o.x-body.x,oy=o.y-body.y,ol=Math.hypot(ox,oy)||1,look=o.r+body.r+52,dot=ux*(ox/ol)+uy*(oy/ol);if(ol<look&&dot>.2){const cross=ux*(oy/ol)-uy*(ox/ol),side=Math.abs(cross)<.08?(body.strafe||1):(cross>0?-1:1),strength=(1-ol/look)*1.9;ux+=(-oy/ol)*side*strength;uy+=(ox/ol)*side*strength}}l=len(ux,uy);ux/=l;uy/=l;const tx=ux*spd,ty=uy*spd;body.vx+=(tx-body.vx)*Math.min(1,weight*dt);body.vy+=(ty-body.vy)*Math.min(1,weight*dt)}
function crowdVector(){let x=0,y=0,n=0;for(const e of near(115)){x+=e.x;y+=e.y;n++}if(!n)return{x:0,y:0,n:0};return{x:x/n,y:y/n,n}}
