'use strict';
const VERSION='Goal 01 Final';
const C=document.getElementById('c'),X=C.getContext('2d'),stage=document.getElementById('stage');
const depthEl=document.getElementById('depth'),threatEl=document.getElementById('threat'),hpEl=document.getElementById('hp'),spdEl=document.getElementById('spd'),eventEl=document.getElementById('event'),overlayEl=document.getElementById('overlay'),resultEl=document.getElementById('result'),gradeEl=document.getElementById('grade'),statsEl=document.getElementById('stats'),goBtn=document.getElementById('go'),nextBtn=document.getElementById('next');
const skillEls={Slash:document.getElementById('sSlash'),Whirlwind:document.getElementById('sWhirl'),Slam:document.getElementById('sSlam')};
const params=new URLSearchParams(location.search),SELFTEST=params.has('selftest'),SMOKE=params.has('smoke'),SOAK=params.has('soak');
let seed=(+(params.get('seed')||0)>>>0)||0; if(SELFTEST&&!seed)seed=0xD0A61E;
function rng(){if(!seed)return Math.random();seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return (seed>>>0)/4294967296}
const R=(a,b)=>a+rng()*(b-a),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),len=(x,y)=>Math.hypot(x,y)||1;
let W=0,H=0,DPR=1,speed=SOAK?12:1,depth=1,active=false,last=performance.now(),en=[],projectiles=[],obstacles=[],fx=[],nums=[],arcs=[],freeze=0,eventTimer=0,shake=0,kills=0,taken=0,dodges=0,projectileDodges=0,start=0,dmg={},biggest=0,roomName='',roomMod='',roomBudget=0,firstKillSec=null,maxSurround=0,kiteTime=0,roomClock=0;
let runtimeErrors=[];window.addEventListener('error',e=>{runtimeErrors.push(e.message);threatEl.textContent='Runtime error: '+e.message;threatEl.style.color='#ff7b83'});
const P={x:0,y:0,vx:0,vy:0,hp:500,max:500,r:17,spd:130,atk:0,ww:0,slam:0,spin:0,spinTick:0,wind:0,dead:false,dodge:0,dodgeCd:0,facing:0,retreat:0};
const cfg={
 rot:{hp:55,dmg:10,spd:94,r:10,col:'#77c94f',range:39,period:.68,cost:1,unlock:1,label:'SWARMER'},
 guard:{hp:225,dmg:26,spd:51,r:17,col:'#c8c5ba',range:46,period:1.22,cost:3,unlock:1,label:'BONEGUARD'},
 archer:{hp:82,dmg:16,spd:74,r:12,col:'#d85b94',range:182,period:1.5,cost:2.5,unlock:2,label:'ARCHER'},
 boom:{hp:50,dmg:105,spd:120,r:11,col:'#ff5d3d',range:40,period:9,cost:2,unlock:3,label:'EXPLODER'},
 necro:{hp:160,dmg:13,spd:60,r:14,col:'#9865d8',range:168,period:1.9,cost:4.5,unlock:4,label:'NECROMANCER'},
 elite:{hp:760,dmg:27,spd:66,r:23,col:'#efa438',range:52,period:1.18,cost:9,unlock:5,label:'FRENZIED ELITE'},
 boss:{hp:1780,dmg:16,spd:57,r:34,col:'#ba2b31',range:62,period:1.5,cost:18,unlock:10,label:'GOREMAW'}
};
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=Math.max(320,stage.clientWidth);H=Math.max(360,stage.clientHeight);C.width=Math.max(1,W*DPR);C.height=Math.max(1,H*DPR);X.setTransform(DPR,0,0,DPR,0,0)} addEventListener('resize',resize);resize();
function announce(t,c='#fff'){eventEl.textContent=t;eventEl.style.color=c;eventEl.classList.add('show');eventTimer=.48}
function difficultyScale(){return{hp:1+Math.max(0,depth-1)*.052,dmg:1+Math.max(0,depth-1)*.033,spd:1+Math.min(.28,Math.max(0,depth-1)*.008)}}
function spawn(type,x,y){const c=cfg[type],s=difficultyScale(),e={type,x,y,vx:0,vy:0,hp:c.hp*s.hp,max:c.hp*s.hp,dmg:c.dmg*s.dmg,spd:c.spd*s.spd,baseSpd:c.spd*s.spd,r:c.r,col:c.col,range:c.range,period:c.period,basePeriod:c.period,atk:R(0,.45),special:R(2.4,4.4),wind:0,mode:'',dead:false,enraged:false,strafe:rng()<.5?-1:1,chargeTarget:null,facing:0};en.push(e);return e}
function randomRoomMod(){if(depth<4)return'';const r=rng();if(r<.20)return'SWARMING';if(r<.38)return'FRENZY';if(r<.56)return'SHARPSHOOTERS';if(r<.73)return'ARMORED';return''}
function generateRoom(){roomMod=randomRoomMod();const bossRoom=depth%10===0;roomBudget=8+depth*2+Math.pow(depth,.75)*1.8;const types=[];if(bossRoom){if(depth<20)roomMod='';types.push('boss');let left=depth>=20?Math.max(0,(roomBudget-18)*.45):0;while(left>=1){const pool=['rot','guard',depth>=20?'archer':'rot'];const t=pool[(rng()*pool.length)|0],cost=cfg[t].cost;if(cost>left)break;types.push(t);left-=cost}roomName='GOREMAW DEPTH'}else{let left=roomBudget;const allowed=Object.keys(cfg).filter(t=>t!=='boss'&&cfg[t].unlock<=depth);if(depth>=5&&rng()<Math.min(.46,.08+depth*.015)){types.push('elite');left-=cfg.elite.cost}let guard=0;while(left>=1&&guard++<90){let pool=allowed.filter(t=>t!=='elite'&&cfg[t].cost<=left);if(roomMod==='SWARMING'&&rng()<.55)pool=['rot'];if(roomMod==='SHARPSHOOTERS'&&depth>=2&&rng()<.52)pool=['archer'];if(!pool.length)break;const t=pool[(rng()*pool.length)|0];types.push(t);left-=cfg[t].cost}roomName=['BROKEN COURT','KILLING FLOOR','ASHEN VAULT','IRON RING','FALLEN NAVE'][(rng()*5)|0]}return types}
function makeObstacles(){obstacles=[];const count=depth<3?0:Math.min(5,1+((depth/4)|0));for(let i=0;i<count;i++){for(let tries=0;tries<35;tries++){const o={x:R(80,W-80),y:R(85,H-110),r:R(23,40)};if(Math.hypot(o.x-W/2,o.y-H*.52)>105&&obstacles.every(q=>dist(o,q)>o.r+q.r+48)){obstacles.push(o);break}}}}
function placeTypes(types){const groups=Math.min(6,2+((types.length/7)|0)),meleeIndex=types.findIndex(t=>['rot','guard','boom','elite'].includes(t));for(let i=0;i<types.length;i++){let a,rr;if(i===meleeIndex&&depth%10!==0){a=R(0,Math.PI*2);rr=R(92,112)}else{const g=i%groups;a=g/groups*Math.PI*2+R(-.34,.34);rr=R(Math.min(W,H)*.31,Math.min(W,H)*.44)}const cx=W*.5+Math.cos(a)*rr,cy=H*.5+Math.sin(a)*rr;spawn(types[i],cl(cx+R(-38,38),35,W-35),cl(cy+R(-38,38),50,H-50))}}
function beginRoom(){en=[];projectiles=[];fx=[];nums=[];arcs=[];P.x=W*.5;P.y=H*.52;P.vx=P.vy=0;P.hp=P.max;P.dead=false;P.atk=P.ww=P.slam=P.spin=P.wind=P.dodge=P.dodgeCd=P.retreat=0;kills=taken=dodges=projectileDodges=0;firstKillSec=null;maxSurround=0;kiteTime=0;roomClock=0;biggest=0;dmg={Slash:0,Whirlwind:0,'Ground Slam':0};freeze=shake=0;makeObstacles();const types=generateRoom();placeTypes(types);if(roomMod==='FRENZY')for(const e of en)e.spd*=1.13;if(roomMod==='ARMORED')for(const e of en){e.hp*=1.28;e.max=e.hp}active=true;start=performance.now();overlayEl.style.display='none';nextBtn.disabled=true;announce('DEPTH '+depth,'#9bd7ff');threatEl.style.color='';threatEl.textContent=roomName+(roomMod?' • '+roomMod:'')+` • threat ${roomBudget.toFixed(0)}`;hud()}
function target(){let best=null,bs=-1e9;for(const e of en){if(e.dead)continue;let s=1000-dist(P,e)+(e.type==='boom'?780:e.type==='necro'?610:e.type==='archer'?170:e.type==='boss'?100:e.type==='elite'?95:0);if(s>bs){bs=s;best=e}}return best}
function near(r){return en.filter(e=>!e.dead&&dist(P,e)<=r)}
function ring(x,y,m,c,w=5){fx.push({kind:'ring',x,y,r:0,m,life:.32,max:.32,col:c,w})} function burst(x,y,c,n=5){for(let i=0;i<n;i++)fx.push({kind:'p',x,y,vx:R(-115,115),vy:R(-115,115),life:R(.18,.4),max:.4,col:c})}
function heal(a){P.hp=Math.min(P.max,P.hp+a)} function kill(e){if(e.dead)return;e.dead=true;kills++;if(firstKillSec===null)firstKillSec=roomClock;heal(5);burst(e.x,e.y,e.col,9);ring(e.x,e.y,28,e.col,2)}
function hit(e,a,k,crit=false,kb=0){if(!e||e.dead)return;dmg[k]+=a;biggest=Math.max(biggest,a);e.hp-=a;nums.push({x:e.x,y:e.y-e.r-8,t:(a|0)+(crit?'!':''),life:.6,col:crit?'#ffd46a':'#fff',big:crit||a>150});burst(e.x,e.y,e.col,crit?9:4);if(k==='Slash'){arcs.push({x:P.x,y:P.y,a:P.facing,life:.13,max:.13,col:crit?'#ffe273':'#d9efff',w:crit?9:5});shake=Math.max(shake,crit?4.5:1.5);if(crit)freeze=.045}if(k==='Ground Slam'){freeze=.075;shake=9}if(k==='Whirlwind')shake=Math.max(shake,1.8);if(kb){const dx=e.x-P.x,dy=e.y-P.y,l=len(dx,dy);e.vx+=dx/l*kb*6;e.vy+=dy/l*kb*6}if(e.hp<=0)kill(e)}
function takeDamage(a,special=false){if(P.dead||P.dodge>0)return;const dealt=a*(special?.90:.80);P.hp-=dealt;taken+=dealt;nums.push({x:P.x,y:P.y-25,t:'-'+(dealt|0),life:.6,col:'#ff727b',big:true});burst(P.x,P.y,'#ff6372',5);shake=Math.max(shake,special?6:3);if(P.hp<=0){P.dead=true;active=false;finish(false)}}
function fireProjectile(e,speedP=225){const dx=P.x-e.x,dy=P.y-e.y,l=len(dx,dy),lead=.18;projectiles.push({x:e.x,y:e.y,vx:(dx/l)*speedP+P.vx*lead,vy:(dy/l)*speedP+P.vy*lead,r:e.type==='necro'?6:4,life:3,damage:e.dmg,col:e.col,owner:e.type,type:e.type==='necro'?'orb':'arrow',dodged:false})}
function segmentPointDistance(px,py,x1,y1,x2,y2){const vx=x2-x1,vy=y2-y1,wx=px-x1,wy=py-y1,c1=wx*vx+wy*vy;if(c1<=0)return Math.hypot(px-x1,py-y1);const c2=vx*vx+vy*vy;if(c2<=c1)return Math.hypot(px-x2,py-y2);const b=c1/c2;return Math.hypot(px-(x1+b*vx),py-(y1+b*vy))}
function hasLineOfSight(a,b,pad=0){for(const o of obstacles){if(segmentPointDistance(o.x,o.y,a.x,a.y,b.x,b.y)<o.r+pad)return false}return true}
function collideObstacle(body){for(const o of obstacles){const dx=body.x-o.x,dy=body.y-o.y,l=Math.hypot(dx,dy)||.001,min=o.r+body.r+3;if(l<min){const nx=dx/l,ny=dy/l,p=min-l;body.x+=nx*p;body.y+=ny*p;const vn=body.vx*nx+body.vy*ny;if(vn<0){body.vx-=vn*1.4*nx;body.vy-=vn*1.4*ny}}}}
function applyWorldPhysics(dt){const live=en.filter(e=>!e.dead);for(const e of live){e.x+=e.vx*dt;e.y+=e.vy*dt;e.vx*=Math.pow(.07,dt);e.vy*=Math.pow(.07,dt)}P.x+=P.vx*dt;P.y+=P.vy*dt;P.vx*=Math.pow(.05,dt);P.vy*=Math.pow(.05,dt);for(let pass=0;pass<9;pass++){for(let i=0;i<live.length;i++){const a=live[i];for(let j=i+1;j<live.length;j++){const b=live[j],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||.001,min=a.r+b.r+14;if(l<min){const nx=dx/l,ny=dy/l,p=min-l,ma=a.type==='boss'?4:a.type==='elite'?2:1,mb=b.type==='boss'?4:b.type==='elite'?2:1,total=ma+mb;a.x-=nx*p*(mb/total);b.x+=nx*p*(ma/total);a.y-=ny*p*(mb/total);b.y+=ny*p*(ma/total);a.vx-=nx*24*(mb/total);b.vx+=nx*24*(ma/total);a.vy-=ny*24*(mb/total);b.vy+=ny*24*(ma/total)}}const dx=a.x-P.x,dy=a.y-P.y,l=Math.hypot(dx,dy)||.001,min=a.r+P.r+10;if(l<min){const nx=dx/l,ny=dy/l,p=min-l,m=a.type==='boss'?4:a.type==='elite'?2:1;a.x+=nx*p*(1/(1+m));a.y+=ny*p*(1/(1+m));P.x-=nx*p*(m/(1+m));P.y-=ny*p*(m/(1+m))}}}for(const e of live){collideObstacle(e);e.x=cl(e.x,e.r+3,W-e.r-3);e.y=cl(e.y,e.r+30,H-e.r-26)}collideObstacle(P);P.x=cl(P.x,P.r+3,W-P.r-3);P.y=cl(P.y,P.r+30,H-P.r-26);for(let pass=0;pass<5;pass++){for(let i=0;i<live.length;i++){const a=live[i];for(let j=i+1;j<live.length;j++){const b=live[j],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||.001,min=a.r+b.r+12;if(l<min){const nx=dx/l,ny=dy/l,p=(min-l)*.51;a.x-=nx*p;b.x+=nx*p;a.y-=ny*p;b.y+=ny*p}}const dx=a.x-P.x,dy=a.y-P.y,l=Math.hypot(dx,dy)||.001,min=a.r+P.r+8;if(l<min){const nx=dx/l,ny=dy/l,p=(min-l)*.55;a.x+=nx*p;P.x-=nx*p;a.y+=ny*p;P.y-=ny*p}}}for(const e of live){e.x=cl(e.x,e.r+3,W-e.r-3);e.y=cl(e.y,e.r+30,H-e.r-26)}P.x=cl(P.x,P.r+3,W-P.r-3);P.y=cl(P.y,P.r+30,H-P.r-26)}
function steer(body,dx,dy,spd,dt,weight=7){let l=len(dx,dy),ux=dx/l,uy=dy/l;for(const o of obstacles){const ox=o.x-body.x,oy=o.y-body.y,ol=Math.hypot(ox,oy)||1,look=o.r+body.r+56,dot=ux*(ox/ol)+uy*(oy/ol);if(ol<look&&dot>.18){const cross=ux*(oy/ol)-uy*(ox/ol),side=Math.abs(cross)<.08?(body.strafe||1):(cross>0?-1:1),strength=(1-ol/look)*2;ux+=(-oy/ol)*side*strength;uy+=(ox/ol)*side*strength}}l=len(ux,uy);ux/=l;uy/=l;body.vx+=(ux*spd-body.vx)*Math.min(1,weight*dt);body.vy+=(uy*spd-body.vy)*Math.min(1,weight*dt)}
function crowdVector(){let x=0,y=0,n=0;for(const e of near(118)){x+=e.x;y+=e.y;n++}if(!n)return{x:0,y:0,n:0};return{x:x/n,y:y/n,n}}
function projectileThreat(){let best=null,bestT=99;for(const p of projectiles){if(p.life<=0)continue;const rx=P.x-p.x,ry=P.y-p.y,v2=p.vx*p.vx+p.vy*p.vy||1,t=(rx*p.vx+ry*p.vy)/v2;if(t<0||t>.52)continue;const cx=p.x+p.vx*t,cy=p.y+p.vy*t,d=Math.hypot(P.x-cx,P.y-cy);if(d<P.r+p.r+8&&t<bestT){bestT=t;best=p}}return best}
