'use strict';
const VERSION='Goal 02 Brain Lab v1.2';
const C=document.getElementById('c'),X=C.getContext('2d'),stage=document.getElementById('stage');
const depthEl=document.getElementById('depth'),threatEl=document.getElementById('threat'),hpEl=document.getElementById('hp'),spdEl=document.getElementById('spd'),eventEl=document.getElementById('event'),brainTicker=document.getElementById('brainTicker'),overlayEl=document.getElementById('overlay'),resultEl=document.getElementById('result'),gradeEl=document.getElementById('grade'),insightEl=document.getElementById('insight'),statsEl=document.getElementById('stats'),goBtn=document.getElementById('go'),replayBtn=document.getElementById('replay'),nextBtn=document.getElementById('next'),brainBtn=document.getElementById('brainBtn');
const skillEls={Slash:document.getElementById('sSlash'),Whirlwind:document.getElementById('sWhirl'),Slam:document.getElementById('sSlam')};
const params=new URLSearchParams(location.search),SELFTEST=params.has('selftest'),SMOKE=params.has('smoke'),SOAK=params.has('soak');
let baseSeed=(+(params.get('seed')||13371337)>>>0)||13371337,seedState=1;
function seedRoom(d=depth,salt=0){seedState=(baseSeed ^ Math.imul(d+salt,0x9e3779b1))>>>0||1}
function rng(){seedState^=seedState<<13;seedState^=seedState>>>17;seedState^=seedState<<5;return(seedState>>>0)/4294967296}
const R=(a,b)=>a+rng()*(b-a),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),len=(x,y)=>Math.hypot(x,y)||1;
let W=0,H=0,DPR=1,speed=1,depth=1,active=false,pausedForBrain=false,last=performance.now(),en=[],projectiles=[],obstacles=[],fx=[],nums=[],arcs=[],freeze=0,eventTimer=0,shake=0,roomName='',roomMod='',roomBudget=0,roomClock=0,roomFingerprint='';
let kills=0,taken=0,dodges=0,projectileDodges=0,firstKillSec=null,maxSurround=0,biggest=0,dmg={},targetSwitches=0,retreatEvents=0,coverMoves=0,brainDecisions=0,adaptiveEvents=0,interceptEvents=0,switchEvents=0,flankEvents=0,commitEvents=0,unstuckEvents=0,safePlanEvents=0,leashBreaks=0,targetLockBreaks=0,forcedSkillCasts=0,comboCasts=0,threatAvoids=0,wallPressureTime=0,dangerTime=0,retreatTime=0,maxRetreatStreak=0,currentRetreatStreak=0,skillReadyWaste=0,skillCasts={Slash:0,Whirlwind:0,Slam:0},skillReadyAge={Slam:0,Whirlwind:0},lastTargetId=null,lastDecision='OPENING',retreating=false,covering=false;
let targetLockUntil=0,chaseClock=0,pursuitTargetId=null,pursuitClock=0,pursuitBest=Infinity,avoidTargetId=null,avoidUntil=0,interceptTargetId=null,interceptUntil=0,flankTargetId=null,flankUntil=0,commitTargetId=null,commitUntil=0,comboPending=null,comboUntil=0,retreatSince=0,retreatCooldownUntil=0,coverUntil=0,coverCooldownUntil=0,lastKillClock=0,lastMeaningfulDamageClock=0,globalAdaptCooldown=0,globalCommitCount=0,stalemateMode=false,hardCommit=false,frustration=new Map();
let runtimeErrors=[];window.addEventListener('error',e=>{runtimeErrors.push(e.message);threatEl.textContent='Runtime error: '+e.message;threatEl.style.color='#ff7b83'});
const P={x:0,y:0,vx:0,vy:0,hp:500,max:500,r:17,spd:130,atk:0,ww:0,slam:0,spin:0,spinTick:0,wind:0,dead:false,dodge:0,dodgeCd:0,facing:0,retreat:0,prevX:0,prevY:0,stuckClock:0,intentX:0,intentY:0};
let nextEnemyId=1;
const cfg={rot:{hp:55,dmg:10,spd:94,r:10,col:'#77c94f',range:39,period:.68,cost:1,unlock:1,label:'SWARMER'},guard:{hp:225,dmg:26,spd:51,r:17,col:'#c8c5ba',range:46,period:1.22,cost:3,unlock:1,label:'BONEGUARD'},archer:{hp:82,dmg:16,spd:74,r:12,col:'#d85b94',range:182,period:1.5,cost:2.5,unlock:2,label:'ARCHER'},boom:{hp:50,dmg:105,spd:120,r:11,col:'#ff5d3d',range:40,period:9,cost:2,unlock:3,label:'EXPLODER'},necro:{hp:160,dmg:13,spd:60,r:14,col:'#9865d8',range:168,period:1.9,cost:4.5,unlock:4,label:'NECROMANCER'},elite:{hp:760,dmg:27,spd:66,r:23,col:'#efa438',range:52,period:1.18,cost:9,unlock:5,label:'FRENZIED ELITE'},boss:{hp:1780,dmg:16,spd:57,r:34,col:'#ba2b31',range:62,period:1.5,cost:18,unlock:10,label:'GOREMAW'}};
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=Math.max(320,stage.clientWidth);H=Math.max(360,stage.clientHeight);C.width=Math.max(1,W*DPR);C.height=Math.max(1,H*DPR);X.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
function announce(t,c='#fff'){eventEl.textContent=t;eventEl.style.color=c;eventEl.classList.add('show');eventTimer=.48}
function difficultyScale(){return{hp:1+Math.max(0,depth-1)*.052,dmg:1+Math.max(0,depth-1)*.033,spd:1+Math.min(.28,Math.max(0,depth-1)*.008)}}
function spawn(type,x,y){const c=cfg[type],s=difficultyScale(),e={id:nextEnemyId++,type,x,y,vx:0,vy:0,hp:c.hp*s.hp,max:c.hp*s.hp,dmg:c.dmg*s.dmg,spd:c.spd*s.spd,baseSpd:c.spd*s.spd,r:c.r,col:c.col,range:c.range,period:c.period,basePeriod:c.period,atk:R(0,.45),special:R(2.4,4.4),wind:0,mode:'',dead:false,enraged:false,strafe:rng()<.5?-1:1,chargeTarget:null,facing:0};en.push(e);return e}
function randomRoomMod(){if(depth<4)return'';const r=rng();if(r<.20)return'SWARMING';if(r<.38)return'FRENZY';if(r<.56)return'SHARPSHOOTERS';if(r<.73)return'ARMORED';return''}
function generateRoom(){roomMod=randomRoomMod();const bossRoom=depth%10===0;roomBudget=8+depth*2+Math.pow(depth,.75)*1.8;const types=[];if(bossRoom){if(depth<20)roomMod='';types.push('boss');let left=depth>=20?Math.max(0,(roomBudget-18)*.45):0;while(left>=1){const pool=['rot','guard',depth>=20?'archer':'rot'];const t=pool[(rng()*pool.length)|0],cost=cfg[t].cost;if(cost>left)break;types.push(t);left-=cost}roomName='GOREMAW DEPTH'}else{let left=roomBudget;const allowed=Object.keys(cfg).filter(t=>t!=='boss'&&cfg[t].unlock<=depth);if(depth>=5&&rng()<Math.min(.46,.08+depth*.015)){types.push('elite');left-=cfg.elite.cost}let guard=0;while(left>=1&&guard++<90){let pool=allowed.filter(t=>t!=='elite'&&cfg[t].cost<=left);if(roomMod==='SWARMING'&&rng()<.55)pool=['rot'];if(roomMod==='SHARPSHOOTERS'&&depth>=2&&rng()<.52)pool=['archer'];if(!pool.length)break;const t=pool[(rng()*pool.length)|0];types.push(t);left-=cfg[t].cost}roomName=['BROKEN COURT','KILLING FLOOR','ASHEN VAULT','IRON RING','FALLEN NAVE'][(rng()*5)|0]}return types}
function makeObstacles(){obstacles=[];const count=depth<3?0:Math.min(5,1+((depth/4)|0));for(let i=0;i<count;i++)for(let tries=0;tries<35;tries++){const o={x:R(80,W-80),y:R(85,H-110),r:R(23,40)};if(Math.hypot(o.x-W/2,o.y-H*.52)>105&&obstacles.every(q=>dist(o,q)>o.r+q.r+48)){obstacles.push(o);break}}}
function placeTypes(types){const groups=Math.min(6,2+((types.length/7)|0)),meleeIndex=types.findIndex(t=>['rot','guard','boom','elite'].includes(t));for(let i=0;i<types.length;i++){let a,rr;if(i===meleeIndex&&depth%10!==0){a=R(0,Math.PI*2);rr=R(92,112)}else{const g=i%groups;a=g/groups*Math.PI*2+R(-.34,.34);rr=R(Math.min(W,H)*.31,Math.min(W,H)*.44)}spawn(types[i],cl(W*.5+Math.cos(a)*rr+R(-38,38),35,W-35),cl(H*.5+Math.sin(a)*rr+R(-38,38),50,H-50))}}
function resetMetrics(){kills=taken=dodges=projectileDodges=0;firstKillSec=null;maxSurround=biggest=0;targetSwitches=retreatEvents=coverMoves=brainDecisions=adaptiveEvents=interceptEvents=switchEvents=flankEvents=commitEvents=unstuckEvents=safePlanEvents=leashBreaks=targetLockBreaks=forcedSkillCasts=comboCasts=threatAvoids=0;wallPressureTime=dangerTime=retreatTime=maxRetreatStreak=currentRetreatStreak=skillReadyWaste=0;skillCasts={Slash:0,Whirlwind:0,Slam:0};skillReadyAge={Slam:0,Whirlwind:0};lastTargetId=null;lastDecision='OPENING';retreating=false;covering=false;targetLockUntil=chaseClock=pursuitClock=avoidUntil=interceptUntil=flankUntil=commitUntil=comboUntil=retreatSince=retreatCooldownUntil=coverUntil=coverCooldownUntil=lastKillClock=lastMeaningfulDamageClock=globalAdaptCooldown=globalCommitCount=0;stalemateMode=false;hardCommit=false;pursuitTargetId=avoidTargetId=interceptTargetId=flankTargetId=commitTargetId=null;pursuitBest=Infinity;comboPending=null;frustration=new Map()}
function beginRoom(){seedRoom(depth);nextEnemyId=1;en=[];projectiles=[];fx=[];nums=[];arcs=[];P.x=W*.5;P.y=H*.52;P.vx=P.vy=0;P.prevX=P.x;P.prevY=P.y;P.stuckClock=0;P.intentX=P.intentY=0;P.hp=P.max;P.dead=false;P.atk=P.ww=P.slam=P.spin=P.wind=P.dodge=P.dodgeCd=P.retreat=0;resetMetrics();dmg={Slash:0,Whirlwind:0,'Ground Slam':0};freeze=shake=0;roomClock=0;makeObstacles();const types=generateRoom();placeTypes(types);roomFingerprint=types.join(',')+'|'+obstacles.map(o=>Math.round(o.x)+':'+Math.round(o.y)+':'+Math.round(o.r)).join(',');if(roomMod==='FRENZY')for(const e of en)e.spd*=1.13;if(roomMod==='ARMORED')for(const e of en){e.hp*=1.28;e.max=e.hp}active=true;overlayEl.style.display='none';nextBtn.disabled=true;announce('DEPTH '+depth,'#9bd7ff');threatEl.style.color='';threatEl.textContent=roomName+(roomMod?' • '+roomMod:'')+` • threat ${roomBudget.toFixed(0)}`;hud();updateBrainTicker()}
function near(r){return en.filter(e=>!e.dead&&dist(P,e)<=r)}
function ring(x,y,m,c,w=5){fx.push({kind:'ring',x,y,r:0,m,life:.32,max:.32,col:c,w})}function burst(x,y,c,n=5){for(let i=0;i<n;i++)fx.push({kind:'p',x,y,vx:R(-115,115),vy:R(-115,115),life:R(.18,.4),max:.4,col:c})}
function heal(a){P.hp=Math.min(P.max,P.hp+a)}function kill(e){if(e.dead)return;e.dead=true;kills++;lastKillClock=roomClock;stalemateMode=false;if(firstKillSec===null)firstKillSec=roomClock;heal(5);burst(e.x,e.y,e.col,9);ring(e.x,e.y,28,e.col,2);frustration.delete(e.id)}
function hit(e,a,k,crit=false,kb=0){if(!e||e.dead)return;if(e.type!=='rot')lastMeaningfulDamageClock=roomClock;dmg[k]=(dmg[k]||0)+a;biggest=Math.max(biggest,a);e.hp-=a;nums.push({x:e.x,y:e.y-e.r-8,t:(a|0)+(crit?'!':''),life:.6,col:crit?'#ffd46a':'#fff',big:crit||a>150});burst(e.x,e.y,e.col,crit?9:4);if(k==='Slash'){arcs.push({x:P.x,y:P.y,a:P.facing,life:.13,max:.13,col:crit?'#ffe273':'#d9efff',w:crit?9:5});shake=Math.max(shake,crit?4.5:1.5);if(crit)freeze=.045}if(k==='Ground Slam'){freeze=.075;shake=9}if(k==='Whirlwind')shake=Math.max(shake,1.8);if(kb){const dx=e.x-P.x,dy=e.y-P.y,l=len(dx,dy);e.vx+=dx/l*kb*6;e.vy+=dy/l*kb*6}if(e.hp<=0)kill(e)}
function takeDamage(a,special=false){if(P.dead||P.dodge>0)return;const dealt=a*(special?.90:.80);P.hp-=dealt;taken+=dealt;nums.push({x:P.x,y:P.y-25,t:'-'+(dealt|0),life:.6,col:'#ff727b',big:true});burst(P.x,P.y,'#ff6372',5);shake=Math.max(shake,special?6:3);if(P.hp<=0){P.dead=true;active=false;finish(false)}}
function fireProjectile(e,speedP=225){const dx=P.x-e.x,dy=P.y-e.y,l=len(dx,dy),lead=.18;projectiles.push({x:e.x,y:e.y,vx:(dx/l)*speedP+P.vx*lead,vy:(dy/l)*speedP+P.vy*lead,r:e.type==='necro'?6:4,life:3,damage:e.dmg,col:e.col,owner:e.type,type:e.type==='necro'?'orb':'arrow',dodged:false})}
function segmentPointDistance(px,py,x1,y1,x2,y2){const vx=x2-x1,vy=y2-y1,wx=px-x1,wy=py-y1,c1=wx*vx+wy*vy;if(c1<=0)return Math.hypot(px-x1,py-y1);const c2=vx*vx+vy*vy;if(c2<=c1)return Math.hypot(px-x2,py-y2);const b=c1/c2;return Math.hypot(px-(x1+b*vx),py-(y1+b*vy))}
function hasLineOfSight(a,b,pad=0){for(const o of obstacles)if(segmentPointDistance(o.x,o.y,a.x,a.y,b.x,b.y)<o.r+pad)return false;return true}
function collideObstacle(body){for(const o of obstacles){const dx=body.x-o.x,dy=body.y-o.y,l=Math.hypot(dx,dy)||.001,min=o.r+body.r+3;if(l<min){const nx=dx/l,ny=dy/l,p=min-l;body.x+=nx*p;body.y+=ny*p;const vn=body.vx*nx+body.vy*ny;if(vn<0){body.vx-=vn*1.45*nx;body.vy-=vn*1.45*ny}}}}
function edgePressure(x,y,r=P.r){const mx=Math.min(x-(r+5),W-(r+5)-x),my=Math.min(y-(r+32),H-(r+28)-y),m=Math.min(mx,my);return cl((80-m)/80,0,1)}
function pointBlocked(x,y,r=P.r){if(x<r+10||x>W-r-10||y<r+38||y>H-r-34)return true;for(const o of obstacles)if(Math.hypot(x-o.x,y-o.y)<o.r+r+8)return true;return false}
function predictedProjectileDanger(x,y){let score=0;for(const p of projectiles){if(p.life<=0)continue;const v2=p.vx*p.vx+p.vy*p.vy||1,t=cl(((x-p.x)*p.vx+(y-p.y)*p.vy)/v2,0,.65),cx=p.x+p.vx*t,cy=p.y+p.vy*t,d=Math.hypot(x-cx,y-cy);if(d<70)score+=(70-d)/70*22}return score}
function hazardDangerAt(x,y){let score=0;for(const e of en){if(e.dead)continue;const d=Math.hypot(x-e.x,y-e.y);if(e.type==='boom'&&e.wind>0&&d<90)score+=45*(1-d/90);if(e.type==='boss'&&e.wind>0){if(e.mode==='rupture'&&d<170)score+=35*(1-d/170);if(e.mode==='cleave'&&d<115){const a=Math.atan2(y-e.y,x-e.x),da=Math.atan2(Math.sin(a-e.facing),Math.cos(a-e.facing));if(Math.abs(da)<.9)score+=38*(1-d/115)}if(e.mode==='charge'&&e.chargeTarget){const dx=e.chargeTarget.x-e.x,dy=e.chargeTarget.y-e.y,l=len(dx,dy),ex=e.x+dx/l*240,ey=e.y+dy/l*240;if(segmentPointDistance(x,y,e.x,e.y,ex,ey)<55)score+=44}}if(e.type==='elite'&&e.wind>0&&e.mode==='charge'&&e.chargeTarget){const dx=e.chargeTarget.x-e.x,dy=e.chargeTarget.y-e.y,l=len(dx,dy),ex=e.x+dx/l*165,ey=e.y+dy/l*165;if(segmentPointDistance(x,y,e.x,e.y,ex,ey)<48)score+=32}}return score}
function localDangerScore(x=P.x,y=P.y){let score=edgePressure(x,y)*28+predictedProjectileDanger(x,y)+hazardDangerAt(x,y);for(const e of en){if(e.dead)continue;const d=Math.hypot(x-e.x,y-e.y),melee=e.type==='archer'||e.type==='necro'?0:1;if(melee&&d<125)score+=(125-d)/125*(e.type==='boss'?25:e.type==='elite'?18:e.type==='boom'?20:9);if(!melee&&hasLineOfSight(e,{x,y},2)&&d<230)score+=(230-d)/230*(e.type==='necro'?10:7)}return cl(score,0,100)}
function safePointVector(reason='SAFE',threat=null){const radii=[78,130,178],angles=16;let best={x:W*.5,y:H*.52,score:1e9};const consider=(x,y)=>{if(pointBlocked(x,y))return;let s=localDangerScore(x,y)*2.6+Math.hypot(x-P.x,y-P.y)*.055+edgePressure(x,y)*42;if(reason==='ENGAGE'&&threat)s+=Math.hypot(x-threat.x,y-threat.y)*.12;if(reason==='RETREAT'&&threat)s-=Math.min(70,Math.hypot(x-threat.x,y-threat.y))*.07;if(brain?.useCover&&threat&&(threat.type==='archer'||threat.type==='necro')){const test={x,y};if(!hasLineOfSight(threat,test,4))s-=24}if(s<best.score)best={x,y,score:s}};for(const r of radii)for(let i=0;i<angles;i++){const a=i/angles*Math.PI*2;consider(cl(P.x+Math.cos(a)*r,35,W-35),cl(P.y+Math.sin(a)*r,52,H-45))}consider(W*.5,H*.52);safePlanEvents++;return{x:best.x-P.x,y:best.y-P.y,score:best.score}}
function applyWorldPhysics(dt){const live=en.filter(e=>!e.dead);for(const e of live){e.x+=e.vx*dt;e.y+=e.vy*dt;e.vx*=Math.pow(.07,dt);e.vy*=Math.pow(.07,dt)}P.x+=P.vx*dt;P.y+=P.vy*dt;P.vx*=Math.pow(.05,dt);P.vy*=Math.pow(.05,dt);for(let pass=0;pass<12;pass++){for(let i=0;i<live.length;i++){const a=live[i];for(let j=i+1;j<live.length;j++){const b=live[j],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||.001,min=a.r+b.r+13;if(l<min){const nx=dx/l,ny=dy/l,p=min-l,ma=a.type==='boss'?4:a.type==='elite'?2:1,mb=b.type==='boss'?4:b.type==='elite'?2:1,total=ma+mb;a.x-=nx*p*(mb/total);b.x+=nx*p*(ma/total);a.y-=ny*p*(mb/total);b.y+=ny*p*(ma/total)}}const dx=a.x-P.x,dy=a.y-P.y,l=Math.hypot(dx,dy)||.001,min=a.r+P.r+9;if(l<min){const nx=dx/l,ny=dy/l,p=min-l,m=a.type==='boss'?4:a.type==='elite'?2:1;a.x+=nx*p/(1+m);a.y+=ny*p/(1+m);P.x-=nx*p*m/(1+m);P.y-=ny*p*m/(1+m)}}}for(const e of live){collideObstacle(e);e.x=cl(e.x,e.r+3,W-e.r-3);e.y=cl(e.y,e.r+30,H-e.r-26)}collideObstacle(P);const minX=P.r+8,maxX=W-P.r-8,minY=P.r+38,maxY=H-P.r-34;if(P.x<=minX+.5&&P.vx<0)P.vx=Math.abs(P.vx)*.38;if(P.x>=maxX-.5&&P.vx>0)P.vx=-Math.abs(P.vx)*.38;if(P.y<=minY+.5&&P.vy<0)P.vy=Math.abs(P.vy)*.38;if(P.y>=maxY-.5&&P.vy>0)P.vy=-Math.abs(P.vy)*.38;P.x=cl(P.x,minX,maxX);P.y=cl(P.y,minY,maxY);for(let pass=0;pass<5;pass++){for(let i=0;i<live.length;i++){const a=live[i];for(let j=i+1;j<live.length;j++){const b=live[j],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||.001,min=a.r+b.r+10;if(l<min){const nx=dx/l,ny=dy/l,p=(min-l)*.52;a.x-=nx*p;b.x+=nx*p;a.y-=ny*p;b.y+=ny*p}}}}for(const e of live){e.x=cl(e.x,e.r+3,W-e.r-3);e.y=cl(e.y,e.r+30,H-e.r-26)}}
function steer(body,dx,dy,spd,dt,weight=7){let l=len(dx,dy),ux=dx/l,uy=dy/l;for(const o of obstacles){const ox=o.x-body.x,oy=o.y-body.y,ol=Math.hypot(ox,oy)||1,look=o.r+body.r+62,dot=ux*(ox/ol)+uy*(oy/ol);if(ol<look&&dot>.12){const cross=ux*(oy/ol)-uy*(ox/ol),side=Math.abs(cross)<.08?(body.strafe||1):(cross>0?-1:1),strength=(1-ol/look)*2.4;ux+=(-oy/ol)*side*strength;uy+=(ox/ol)*side*strength}}const margin=body===P?92:52,left=body.r+8,right=W-body.r-8,top=body.r+38,bottom=H-body.r-34;if(body.x<left+margin)ux+=((left+margin-body.x)/margin)*2.8;if(body.x>right-margin)ux-=((body.x-(right-margin))/margin)*2.8;if(body.y<top+margin)uy+=((top+margin-body.y)/margin)*2.8;if(body.y>bottom-margin)uy-=((body.y-(bottom-margin))/margin)*2.8;l=len(ux,uy);if(body===P){P.intentX=ux/l;P.intentY=uy/l}body.vx+=(ux/l*spd-body.vx)*Math.min(1,weight*dt);body.vy+=(uy/l*spd-body.vy)*Math.min(1,weight*dt)}
function updatePlayerStuck(dt){const moved=Math.hypot(P.x-P.prevX,P.y-P.prevY),intent=Math.hypot(P.intentX,P.intentY),v=Math.hypot(P.vx,P.vy);if(intent>.5&&v>18&&moved<.24)P.stuckClock+=dt;else P.stuckClock=Math.max(0,P.stuckClock-dt*2.4);P.prevX=P.x;P.prevY=P.y;if(edgePressure(P.x,P.y)>.72)wallPressureTime+=dt;if(P.stuckClock<.48)return;const sv=safePointVector('UNSTUCK',nearestRanged());const l=len(sv.x,sv.y);P.vx=sv.x/l*315;P.vy=sv.y/l*315;P.x=cl(P.x,P.r+16,W-P.r-16);P.y=cl(P.y,P.r+44,H-P.r-40);P.stuckClock=0;unstuckEvents++;setDecision('UNSTUCK: SAFE ROUTE');announce('UNSTUCK','#8edcff')}
function crowdVector(){let x=0,y=0,n=0;for(const e of near(118)){x+=e.x;y+=e.y;n++}if(!n)return{x:0,y:0,n:0};return{x:x/n,y:y/n,n}}
function projectileThreat(){let best=null,bestT=99;for(const p of projectiles){if(p.life<=0)continue;const rx=P.x-p.x,ry=P.y-p.y,v2=p.vx*p.vx+p.vy*p.vy||1,t=(rx*p.vx+ry*p.vy)/v2;if(t<0||t>.55)continue;const cx=p.x+p.vx*t,cy=p.y+p.vy*t,d=Math.hypot(P.x-cx,P.y-cy);if(d<P.r+p.r+10&&t<bestT){bestT=t;best=p}}return best}
