function hud(){depthEl.textContent=`DOPAMINE • DEPTH ${depth}`;hpEl.textContent=`HP ${Math.max(0,P.hp|0)}/500`;hpEl.classList.toggle('low',P.hp<150);spdEl.textContent=(SOAK?'12':speed)+'×';[[skillEls.Slash,P.atk],[skillEls.Whirlwind,P.ww],[skillEls.Slam,P.slam]].forEach(([el,cd])=>{el.classList.toggle('ready',cd<=0);el.querySelector('.cd').textContent=cd<=0?'READY':cd.toFixed(1)+'s'})}
function poly(points,fill,stroke='#020509',w=2){X.beginPath();points.forEach((p,i)=>i?X.lineTo(p[0],p[1]):X.moveTo(p[0],p[1]));X.closePath();X.fillStyle=fill;X.fill();X.strokeStyle=stroke;X.lineWidth=w;X.stroke()}
function circ(o,r,c){X.beginPath();X.arc(o.x,o.y,r,0,6.283);X.fillStyle=c;X.fill();X.strokeStyle='#020509';X.lineWidth=2;X.stroke()}
function drawEnemy(e){if(e.type==='guard')poly([[e.x-e.r,e.y-e.r],[e.x+e.r,e.y-e.r],[e.x+e.r,e.y+e.r],[e.x-e.r,e.y+e.r]],e.col);else if(e.type==='archer')poly([[e.x,e.y-e.r-3],[e.x+e.r+2,e.y+e.r],[e.x-e.r-2,e.y+e.r]],e.col);else if(e.type==='necro')poly([[e.x,e.y-e.r-4],[e.x+e.r+3,e.y],[e.x,e.y+e.r+4],[e.x-e.r-3,e.y]],e.col);else if(e.type==='elite')poly([[e.x,e.y-e.r-4],[e.x+e.r,e.y-e.r/2],[e.x+e.r,e.y+e.r/2],[e.x,e.y+e.r+4],[e.x-e.r,e.y+e.r/2],[e.x-e.r,e.y-e.r/2]],e.col);else circ(e,e.r,e.col);
 if(e.type==='rot'){for(let i=0;i<4;i++){const a=i*Math.PI/2+.4;X.strokeStyle='#b8f58b';X.lineWidth=2;X.beginPath();X.moveTo(e.x+Math.cos(a)*e.r*.5,e.y+Math.sin(a)*e.r*.5);X.lineTo(e.x+Math.cos(a)*(e.r+5),e.y+Math.sin(a)*(e.r+5));X.stroke()}}if(e.type==='guard'){X.strokeStyle='#f3f0e8';X.lineWidth=3;X.strokeRect(e.x-8,e.y-10,7,20)}if(e.type==='archer'){X.strokeStyle='#ffe8f3';X.lineWidth=2;X.beginPath();X.arc(e.x,e.y,7,-1.1,1.1);X.stroke()}if(e.type==='boom'){X.fillStyle='#300909';X.font='900 16px system-ui';X.textAlign='center';X.fillText('!',e.x,e.y+5)}if(e.type==='necro'){X.strokeStyle='#ead7ff';X.lineWidth=2;X.beginPath();X.arc(e.x,e.y,e.r+5,0,6.283);X.stroke()}if(e.type==='elite'||e.type==='boss'){X.strokeStyle=e.type==='boss'?'#ff625e':'#ffad3f';X.lineWidth=4;X.beginPath();X.arc(e.x,e.y,e.r+7,0,6.283);X.stroke()}if(e.type==='boss'){X.fillStyle='#fff';X.font='900 10px system-ui';X.textAlign='center';X.fillText('GOREMAW',e.x,e.y-e.r-16)}
 X.fillStyle='#301014';X.fillRect(e.x-e.r,e.y-e.r-9,e.r*2,3);X.fillStyle=e.type==='boss'?'#ff4b4f':'#55df6c';X.fillRect(e.x-e.r,e.y-e.r-9,e.r*2*Math.max(0,e.hp/e.max),3);drawTelegraph(e)}
function drawTelegraph(e){if(e.wind<=0)return;X.save();X.globalAlpha=.2+.12*Math.sin(performance.now()/80);if(e.type==='boom'){X.fillStyle='#ff3d25';X.beginPath();X.arc(e.x,e.y,80,0,6.283);X.fill();X.globalAlpha=.9;X.strokeStyle='#ff5b40';X.lineWidth=4;X.stroke()}else if(e.type==='boss'){if(e.mode==='rupture'){X.fillStyle='#ff9d3d';X.beginPath();X.arc(e.x,e.y,160,0,6.283);X.fill();X.globalAlpha=.9;X.strokeStyle='#ffb057';X.lineWidth=4;X.stroke()}else if(e.mode==='cleave'){X.fillStyle='#ff653a';X.beginPath();X.moveTo(e.x,e.y);X.arc(e.x,e.y,102,e.facing-.78,e.facing+.78);X.closePath();X.fill();X.globalAlpha=.9;X.strokeStyle='#ff8059';X.lineWidth=4;X.stroke()}else if(e.mode==='charge'&&e.chargeTarget){const dx=e.chargeTarget.x-e.x,dy=e.chargeTarget.y-e.y,l=len(dx,dy),ex=e.x+dx/l*230,ey=e.y+dy/l*230;X.globalAlpha=.25;X.strokeStyle='#ff3440';X.lineWidth=52;X.beginPath();X.moveTo(e.x,e.y);X.lineTo(ex,ey);X.stroke();X.globalAlpha=.95;X.lineWidth=4;X.stroke()}}else if(e.type==='elite'&&e.mode==='charge'&&e.chargeTarget){const dx=e.chargeTarget.x-e.x,dy=e.chargeTarget.y-e.y,l=len(dx,dy),ex=e.x+dx/l*155,ey=e.y+dy/l*155;X.strokeStyle='#ffb03e';X.lineWidth=40;X.globalAlpha=.22;X.beginPath();X.moveTo(e.x,e.y);X.lineTo(ex,ey);X.stroke();X.globalAlpha=.95;X.lineWidth=3;X.stroke()}X.restore()}
function draw(){X.save();if(shake>0)X.translate(R(-shake,shake),R(-shake,shake));X.fillStyle='#09121d';X.fillRect(-12,-12,W+24,H+24);X.strokeStyle='#17283c';X.lineWidth=1;for(let gx=0;gx<W;gx+=48){X.beginPath();X.moveTo(gx,0);X.lineTo(gx,H);X.stroke()}for(let gy=0;gy<H;gy+=48){X.beginPath();X.moveTo(0,gy);X.lineTo(W,gy);X.stroke()}
 for(const o of obstacles){X.beginPath();X.arc(o.x,o.y,o.r,0,6.283);X.fillStyle='#202d39';X.fill();X.strokeStyle='#465c70';X.lineWidth=3;X.stroke();X.beginPath();X.arc(o.x-5,o.y-7,o.r*.62,0,6.283);X.fillStyle='#2a3c4b';X.fill()}
 for(const p of projectiles){const l=len(p.vx,p.vy),tx=p.x-p.vx/l*12,ty=p.y-p.vy/l*12;X.strokeStyle=p.col;X.globalAlpha=.35;X.lineWidth=p.r*1.5;X.beginPath();X.moveTo(tx,ty);X.lineTo(p.x,p.y);X.stroke();X.globalAlpha=1;X.beginPath();X.arc(p.x,p.y,p.r,0,6.283);X.fillStyle=p.col;X.fill();X.strokeStyle='#fff9';X.stroke()}
 for(const f of fx){X.globalAlpha=Math.max(0,f.life/f.max);if(f.kind==='ring'){X.beginPath();X.arc(f.x,f.y,f.r,0,6.283);X.strokeStyle=f.col;X.lineWidth=f.w;X.stroke()}else{X.fillStyle=f.col;X.fillRect(f.x,f.y,3,3)}X.globalAlpha=1}
 for(const a of arcs){X.globalAlpha=Math.max(0,a.life/a.max);X.strokeStyle=a.col;X.lineWidth=a.w;X.beginPath();if(a.charge){X.moveTo(a.x,a.y);X.lineTo(a.x2,a.y2)}else X.arc(a.x,a.y,32,a.a-.7,a.a+.7);X.stroke();X.globalAlpha=1}
 for(const e of en)if(!e.dead)drawEnemy(e);
 circ(P,P.r,P.dodge>0?'#7ee9ff':P.retreat>0?'#73bbff':'#469cff');X.strokeStyle='#d9efff';X.lineWidth=5;X.beginPath();X.moveTo(P.x+Math.cos(P.facing)*10,P.y+Math.sin(P.facing)*10);X.lineTo(P.x+Math.cos(P.facing)*31,P.y+Math.sin(P.facing)*31);X.stroke();if(P.spin>0){X.strokeStyle='#72d9ff';X.lineWidth=5;X.beginPath();X.arc(P.x,P.y,69,0,6.283);X.stroke()}if(P.wind>0){X.strokeStyle='#ffc055';X.lineWidth=6;X.beginPath();X.arc(P.x,P.y,105*(1-P.wind/.52),0,6.283);X.stroke()}
 for(const n of nums){X.globalAlpha=Math.max(0,n.life/.6);X.fillStyle=n.col;X.textAlign='center';X.font=`900 ${n.big?21:15}px system-ui`;X.fillText(n.t,n.x,n.y);X.globalAlpha=1}
 if(P.hp<150){X.globalAlpha=(150-P.hp)/450;X.fillStyle='#8a0f21';X.fillRect(0,0,W,H);X.globalAlpha=1}X.restore()}
function updateFx(dt){for(const f of fx){if(f.kind==='ring')f.r+=(f.m-f.r)*13*dt;else{f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.96;f.vy*=.96}f.life-=dt}fx=fx.filter(f=>f.life>0);for(const n of nums){n.y-=30*dt;n.life-=dt}nums=nums.filter(n=>n.life>0);for(const a of arcs)a.life-=dt;arcs=arcs.filter(a=>a.life>0)}
function step(dt){if(!active)return;roomClock+=dt;upP(dt);for(const e of en)upE(e,dt);applyWorldPhysics(dt);updateProjectiles(dt);updateFx(dt);shake=Math.max(0,shake-20*dt);if(!P.dead&&!en.some(e=>!e.dead))finish(true);hud()}
function runSelfTest(){const depths=[1,2,3,4,5,7,10,12,15,20];let rooms=0,steps=0,maxOverlap=0,bossSeen=false,eliteSeen=false,projectileSeen=false,lateDepthSeen=false,firstKills=[];speed=12;for(const testDepth of depths){depth=testDepth;beginRoom();if(testDepth===5&&!en.some(e=>e.type==='elite'))spawn('elite',cl(P.x+150,40,W-40),P.y);let local=0;while(active&&local<4200&&!runtimeErrors.length){step(.035);local++;steps++;const live=en.filter(e=>!e.dead);bossSeen ||= live.some(e=>e.type==='boss');eliteSeen ||= live.some(e=>e.type==='elite');projectileSeen ||= projectiles.length>0;lateDepthSeen ||= depth>=15;for(let i=0;i<live.length;i++)for(let j=i+1;j<live.length;j++){const a=live[i],b=live[j],ov=a.r+b.r-dist(a,b);if(ov>maxOverlap)maxOverlap=ov}}if(firstKillSec!==null&&testDepth<=7)firstKills.push(firstKillSec);rooms++}const sorted=firstKills.sort((a,b)=>a-b),firstKillP90=sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.9))]||99;const ok=runtimeErrors.length===0&&rooms===depths.length&&maxOverlap<8&&bossSeen&&eliteSeen&&projectileSeen&&lateDepthSeen&&firstKillP90<=3.2;document.body.innerHTML=`<pre id="selftest">SELFTEST_OK=${ok}\nROOMS=${rooms}\nSTEPS=${steps}\nMAX_OVERLAP=${maxOverlap.toFixed(2)}\nFIRST_KILL_P90=${firstKillP90.toFixed(2)}\nBOSS_SEEN=${bossSeen}\nELITE_SEEN=${eliteSeen}\nPROJECTILES_SEEN=${projectileSeen}\nLATE_DEPTH_SEEN=${lateDepthSeen}\nERRORS=${runtimeErrors.join('|')}</pre>`;window.__DOPAMINE={ok,rooms,steps,maxOverlap,firstKillP90,bossSeen,eliteSeen,projectileSeen,lateDepthSeen,errors:runtimeErrors}}
function runSmokeTest(){depth=3;beginRoom();for(let i=0;i<450&&!runtimeErrors.length&&active;i++)step(.035);draw();const ok=runtimeErrors.length===0&&C.width>0&&C.height>0&&en.length>0;document.body.innerHTML=`<pre id="smoke">SMOKE_OK=${ok}\nCANVAS=${C.width}x${C.height}\nENEMIES=${en.length}\nPROJECTILES=${projectiles.length}\nERRORS=${runtimeErrors.join('|')}</pre>`;window.__DOPAMINE_SMOKE={ok,errors:runtimeErrors}}
function loop(t){let dt=Math.min(.035,(t-last)/1000)*(SOAK?12:speed);last=t;if(freeze>0){freeze=Math.max(0,freeze-dt);dt=0}if(eventTimer>0){eventTimer-=.016;if(eventTimer<=0)eventEl.classList.remove('show')}if(active&&dt>0)step(dt);else if(dt>0)updateFx(dt);if(!SELFTEST){draw();requestAnimationFrame(loop)}}
document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{speed=+b.dataset.s;document.querySelectorAll('[data-s]').forEach(q=>q.classList.toggle('on',q===b));hud()});function descend(){if(active)return;if(P.dead)beginRoom();else{depth++;beginRoom()}}nextBtn.onclick=descend;goBtn.onclick=descend;if(SELFTEST)runSelfTest();else if(SMOKE)runSmokeTest();else{beginRoom();requestAnimationFrame(loop)};
