'use strict';
(()=>{
const skills={
 FrostLance:{id:'FrostLance',name:'Frost Lance',tags:['Cold','Projectile','Spell'],delivery:'g4_projectile',behavior:'pierce_chill',baseDamage:82,effectiveness:.88,castTime:.22,cooldown:1.35,range:285,projectileSpeed:390,projectileRadius:5,color:'#9fe9ff',brain:{kind:'single'},unlock:16,growth:.069,role:'Ranged pierce/control',identity:'Pierces a line of enemies and chills everything it passes through.'},
 ChainLightning:{id:'ChainLightning',name:'Chain Lightning',tags:['Lightning','Spell'],delivery:'g4_chain',behavior:'chain',baseDamage:66,effectiveness:.82,castTime:.27,cooldown:2.2,range:250,chainRange:115,chains:4,color:'#aeb8ff',brain:{kind:'single'},unlock:18,growth:.067,role:'Ranged chain clear',identity:'Jumps between separated targets, rewarding spread-out packs.'},
 Meteor:{id:'Meteor',name:'Meteor',tags:['Fire','Spell','AoE'],delivery:'g4_delay_aoe',behavior:'meteor',baseDamage:220,effectiveness:1.15,castTime:.55,cooldown:7.6,range:265,area:105,delay:.82,color:'#ff8455',brain:{kind:'aoe',minTargets:2},unlock:20,growth:.073,role:'Delayed burst AoE',identity:'Marks a target zone, then lands a huge delayed impact.'},
 Orbit:{id:'Orbit',name:'Arcane Orbit',tags:['Spell','AoE'],delivery:'g4_orbit',behavior:'orbit',baseDamage:31,effectiveness:.72,castTime:.15,cooldown:6.4,duration:5.2,tickRate:.22,area:70,color:'#d2a4ff',brain:{kind:'utility'},unlock:22,growth:.062,role:'Close orbit damage',identity:'Summons rotating blades that turn proximity into sustained damage.'},
 ChainHook:{id:'ChainHook',name:'Chain Hook',tags:['Melee','Physical','Control'],delivery:'g4_hook',behavior:'hook',baseDamage:74,effectiveness:1.0,castTime:.14,cooldown:3.2,range:215,color:'#c7d1db',brain:{kind:'single'},unlock:24,growth:.07,role:'Melee pull/setup',identity:'Yanks a distant enemy into melee range before striking.'},
 ShieldCharge:{id:'ShieldCharge',name:'Shield Charge',tags:['Melee','Movement','Physical'],delivery:'g4_charge',behavior:'charge',baseDamage:68,effectiveness:1.0,castTime:.08,cooldown:3.9,range:190,area:42,knockback:24,color:'#8bd2ff',brain:{kind:'single'},unlock:26,growth:.068,role:'Line mobility/knockback',identity:'Charges through a line and scatters enemies along the route.'},
 BladeStorm:{id:'BladeStorm',name:'Blade Storm',tags:['Melee','Physical','DoT','AoE'],delivery:'g4_zone',behavior:'moving_zone',baseDamage:23,effectiveness:.76,castTime:.23,cooldown:6.2,duration:4.6,tickRate:.34,area:72,range:180,color:'#d9e6ef',brain:{kind:'aoe',minTargets:2},unlock:28,growth:.064,role:'Persistent moving melee zone',identity:'Creates a roaming blade storm that drifts toward enemies.'},
 Riposte:{id:'Riposte',name:'Riposte',tags:['Melee','Physical','Reactive'],delivery:'g4_counter',behavior:'counter',baseDamage:145,effectiveness:1.05,castTime:0,cooldown:4.5,range:78,color:'#ffe49a',brain:{kind:'counter'},unlock:30,growth:.075,role:'Reactive counterattack',identity:'Only becomes ready after taking damage, then punishes the nearest threat.'},
 FrostNova:{id:'FrostNova',name:'Frost Nova',tags:['Cold','Spell','AoE','Control'],delivery:'g4_nova',behavior:'freeze_nova',baseDamage:74,effectiveness:.84,castTime:.25,cooldown:5.5,area:105,color:'#b8f2ff',brain:{kind:'aoe',minTargets:2},unlock:32,growth:.066,role:'Defensive freeze nova',identity:'Freezes nearby enemies and creates breathing room when surrounded.'},
 FrozenOrb:{id:'FrozenOrb',name:'Frozen Orb',tags:['Cold','Projectile','Spell','AoE'],delivery:'g4_projectile',behavior:'orb_pulse',baseDamage:34,effectiveness:.72,castTime:.31,cooldown:4.6,range:285,projectileSpeed:135,projectileRadius:10,duration:2.5,tickRate:.26,area:58,color:'#7fdcff',brain:{kind:'single'},unlock:34,growth:.063,role:'Slow projectile pulsing AoE',identity:'A slow orb repeatedly pulses shards while travelling through a pack.'},
 Glacier:{id:'Glacier',name:'Glacier Wall',tags:['Cold','Spell','Control','AoE'],delivery:'g4_line',behavior:'glacier_line',baseDamage:58,effectiveness:.72,castTime:.35,cooldown:6.8,range:210,area:130,color:'#d6fbff',brain:{kind:'aoe',minTargets:2},unlock:36,growth:.061,role:'Line control/barrier',identity:'Raises a damaging ice line that slows enemies crossing it.'},
 Thunderstep:{id:'Thunderstep',name:'Thunderstep',tags:['Lightning','Spell','Movement'],delivery:'g4_teleport',behavior:'tele_chain',baseDamage:93,effectiveness:.96,castTime:.08,cooldown:4.2,range:240,chainRange:95,color:'#c3b2ff',brain:{kind:'single'},unlock:38,growth:.071,role:'Teleport strike/chain',identity:'Teleports onto a target and arcs lightning into nearby enemies.'},
 StormTotem:{id:'StormTotem',name:'Storm Totem',tags:['Lightning','Spell','Minion'],delivery:'g4_summon',behavior:'turret',baseDamage:29,effectiveness:.68,castTime:.38,cooldown:8.5,duration:8,tickRate:.48,range:260,color:'#bcb7ff',brain:{kind:'utility'},unlock:40,growth:.061,role:'Stationary ranged summon',identity:'Plants a turret that repeatedly zaps targets from a fixed position.'},
 BallLightning:{id:'BallLightning',name:'Ball Lightning',tags:['Lightning','Projectile','Spell','AoE'],delivery:'g4_projectile',behavior:'ball_pulse',baseDamage:27,effectiveness:.64,castTime:.29,cooldown:3.9,range:290,projectileSpeed:105,projectileRadius:11,duration:2.8,tickRate:.22,area:64,color:'#9e8cff',brain:{kind:'single'},unlock:42,growth:.06,role:'Slow pulsing lightning projectile',identity:'Moves slowly while repeatedly shocking enemies around the orb.'},
 VenomFang:{id:'VenomFang',name:'Venom Fang',tags:['Melee','Chaos','DoT'],delivery:'g4_melee',behavior:'poison',baseDamage:58,effectiveness:.92,castTime:.11,cooldown:1.0,range:62,color:'#8ee06b',brain:{kind:'single'},unlock:44,growth:.068,role:'Fast poison melee',identity:'Rapid melee strikes stack poison for escalating single-target pressure.'},
 PlagueBurst:{id:'PlagueBurst',name:'Plague Burst',tags:['Chaos','Spell','AoE'],delivery:'g4_nova',behavior:'poison_detonate',baseDamage:48,effectiveness:.78,castTime:.32,cooldown:5.2,area:130,color:'#b5ed77',brain:{kind:'aoe',minTargets:1},unlock:46,growth:.066,role:'Poison detonation',identity:'Consumes poison stacks nearby and turns setup into explosive payoff.'},
 AcidPool:{id:'AcidPool',name:'Acid Pool',tags:['Chaos','Spell','DoT','AoE'],delivery:'g4_ground',behavior:'shred_pool',baseDamage:21,effectiveness:.68,castTime:.28,cooldown:5.8,duration:5,tickRate:.42,area:84,range:220,color:'#a9dc4f',brain:{kind:'aoe',minTargets:2},unlock:48,growth:.061,role:'Ground DoT/debuff',identity:'Leaves corrosive ground that ramps damage taken on enemies standing inside.'},
 ShadowKnives:{id:'ShadowKnives',name:'Shadow Knives',tags:['Physical','Projectile','Spell'],delivery:'g4_fan',behavior:'fan',baseDamage:42,effectiveness:.78,castTime:.17,cooldown:1.9,range:215,projectileSpeed:330,color:'#b5a8c9',brain:{kind:'single'},unlock:50,growth:.066,role:'Close fan projectile',identity:'Throws a five-knife fan that excels at close spread and shotgun angles.'},
 Ricochet:{id:'Ricochet',name:'Ricochet Shot',tags:['Physical','Projectile'],delivery:'g4_projectile',behavior:'bounce',baseDamage:61,effectiveness:.9,castTime:.18,cooldown:1.65,range:275,projectileSpeed:365,projectileRadius:5,bounces:3,chainRange:120,color:'#f1d7a8',brain:{kind:'single'},unlock:52,growth:.068,role:'Bouncing ranged clear',identity:'Bounces between targets after impact, rewarding dense clusters.'},
 Barrage:{id:'Barrage',name:'Barrage',tags:['Physical','Projectile','Channeled'],delivery:'g4_channel',behavior:'barrage',baseDamage:31,effectiveness:.58,castTime:.18,cooldown:4.4,range:285,projectileSpeed:390,shots:7,interval:.11,color:'#e7d7bd',brain:{kind:'single'},unlock:54,growth:.063,role:'Burst projectile channel',identity:'Locks into a rapid multi-shot channel for focused ranged burst.'},
 BoneGolem:{id:'BoneGolem',name:'Bone Golem',tags:['Physical','Minion'],delivery:'g4_summon',behavior:'bruiser',baseDamage:44,effectiveness:.82,castTime:.48,cooldown:10,duration:11,tickRate:.62,range:95,color:'#d9d2bf',brain:{kind:'utility'},unlock:56,growth:.062,role:'Durable melee summon',identity:'Summons a slow bruiser that chases and body-checks nearby enemies.'},
 RavenSwarm:{id:'RavenSwarm',name:'Raven Swarm',tags:['Chaos','Minion','AoE'],delivery:'g4_summon',behavior:'swarm',baseDamage:19,effectiveness:.56,castTime:.4,cooldown:8.7,duration:7.5,tickRate:.32,range:225,color:'#9c8baa',brain:{kind:'utility'},unlock:58,growth:.059,role:'Multi-target swarm summon',identity:'Releases several ravens that independently harass different targets.'},
 GravityWell:{id:'GravityWell',name:'Gravity Well',tags:['Spell','AoE','Control'],delivery:'g4_ground',behavior:'pull',baseDamage:18,effectiveness:.5,castTime:.4,cooldown:8.2,duration:4.2,tickRate:.2,area:118,range:235,color:'#ba8cff',brain:{kind:'aoe',minTargets:2},unlock:60,growth:.058,role:'Hard grouping control',identity:'Pulls enemies inward over time so other AoE skills can collapse a pack.'}
};
const ids=Object.keys(skills);
const roles={melee:['ChainHook','ShieldCharge','BladeStorm','Riposte','VenomFang'],ranged:['FrostLance','ChainLightning','FrozenOrb','BallLightning','ShadowKnives','Ricochet','Barrage'],control:['Meteor','FrostNova','Glacier','GravityWell','AcidPool'],summon:['Orbit','StormTotem','BoneGolem','RavenSwarm'],mobility:['ShieldCharge','Thunderstep','ChainHook'],combo:['VenomFang','PlagueBurst','GravityWell','Meteor']};
window.DopamineGoal4Catalog=Object.freeze({version:'Goal 04 Catalog v1.0',ids:()=>[...ids],get:id=>skills[id]||null,all:()=>ids.map(id=>skills[id]),roles:Object.freeze(Object.fromEntries(Object.entries(roles).map(([k,v])=>[k,Object.freeze([...v])])))});
})();
