'use strict';
(()=>{
const q=new URLSearchParams(location.search);if(!q.has('goal4audit'))return;const api=window.DopamineSkills,g4=window.DopamineGoal4Catalog,rt=window.DopamineGoal4,fun=window.DopamineGoal4Fun,gap=window.DopamineGoal4GapPass,p=window.DopamineSkillProgression;
function report(rows,obj){active=false;pausedForBrain=true;document.body.innerHTML=`<pre id="__DOPAMINE_GOAL4_AUDIT" style="white-space:pre-wrap;background:#07101a;color:#eaf3ff;padding:18px;font:13px/1.5 ui-monospace,monospace">${rows.join('\n')}</pre>`;window.__DOPAMINE_GOAL4_AUDIT=obj}
function unlockAll(lv=16){p.reset();for(const id of ['Firebolt','Whirlwind','Dash','Slam','Scorch','Wisp'])p.grantDrop(id,lv,60);rt.debugUnlockAll(lv)}
unlockAll(16);const ids=api.ids(),newIds=rt.newIds(),builds=[['Slash','Whirlwind','Slam'],['Firebolt','Dash','Scorch'],['Wisp','FrostLance','ChainLightning'],['Meteor','Orbit','ChainHook'],['ShieldCharge','BladeStorm','Riposte'],['FrostNova','FrozenOrb','Glacier'],['Thunderstep','StormTotem','BallLightning'],['VenomFang','PlagueBurst','AcidPool'],['ShadowKnives','Ricochet','Barrage'],['BoneGolem','RavenSwarm','GravityWell']],originalSeed=baseSeed;
const matrix=builds.map((load,i)=>({i,load:load.join('>'),wins:0,losses:0,stalls:0,casts:Object.fromEntries(load.map(id=>[id,0]))}));let totalSteps=0,totalStalls=0;
for(const b of matrix){for(let d=1;d<=30&&!runtimeErrors.length;d++){depth=d;baseSeed=(originalSeed+Math.imul(d,104729))>>>0;brain.skills=b.load.split('>');saveBrain();beginRoom();let local=0;while(active&&local<2600&&!runtimeErrors.length){step(.035);local++;totalSteps++}for(const id of Object.keys(b.casts))b.casts[id]+=(skillCasts[id]||0);const live=en.filter(e=>!e.dead);if(active&&local>=2600){b.stalls++;totalStalls++;active=false}else if(P.dead||live.length)b.losses++;else b.wins++}}
baseSeed=originalSeed;const rates=matrix.map(x=>x.wins/30),minRate=Math.min(...rates),maxRate=Math.max(...rates),castCoverage=matrix.every(x=>Object.values(x.casts).every(n=>n>0));
const catalog=ids.length===30&&newIds.length===23&&new Set(newIds.map(id=>api.get(id).behavior)).size===23;const roles=['Melee','Projectile','Spell','Minion','Movement','DoT'].every(t=>ids.some(id=>api.hasTag(id,t)))&&ids.some(id=>String(api.get(id).role||'').toLowerCase().includes('control'));const masteries=fun?.improvements===20&&Object.keys(fun.masteries||{}).length===23&&gap?.improvements===10;const geo=gap?.dropGeometry?.()||{},ui=!!geo.bottomRight&&!!geo.compact;const fairBalance=totalStalls===0&&minRate>=.20&&maxRate<=.88&&castCoverage;const progression=newIds.every(id=>api.unlockDepth(id)>=16&&api.unlockDepth(id)<=60)&&new Set(newIds.map(id=>api.unlockDepth(id))).size===23&&api.effective('FrostLance').baseDamage>api.get('FrostLance').baseDamage;const stable=runtimeErrors.length===0&&totalStalls===0&&castCoverage;
const visual=!!window.DopamineGoal4FinalPolish?.visualFamilies&&window.DopamineGoal4FinalPolish.visualFamilies>=6;const ux=!!window.DopamineGoal4FinalPolish?.smartPresets&&!!window.DopamineGoal4FinalPolish?.search;const persistence=!!window.DopamineGoal4FinalPolish?.saveBackup;const discovery=!!window.DopamineGoal4FinalPolish?.smartDiscovery;
let score=0;score+=catalog?1.5:0;score+=roles?.75:0;score+=masteries?1.0:0;score+=ui?.75:0;score+=fairBalance?1.75:0;score+=progression?.75:0;score+=stable?1.0:0;score+=visual?.9:0;score+=ux?.8:0;score+=(persistence&&discovery)?.8:0;score=Math.round(score*10)/10;const ok=score>=9&&catalog&&fairBalance&&stable&&ui;
report([`GOAL4_AUDIT_OK=${ok}`,`COMPLETENESS_SCORE=${score.toFixed(1)}/10`,`CATALOG=${catalog}`,`ROLE_COVERAGE=${roles}`,`MASTERY_DEPTH=${masteries}`,`COMPACT_DROP_UI=${ui}`,`FAIR_BALANCE=${fairBalance}`,`PROGRESSION=${progression}`,`STABLE=${stable}`,`VISUAL_IDENTITY=${visual}`,`ARSENAL_UX=${ux}`,`PERSISTENCE_AND_DISCOVERY=${persistence&&discovery}`,`FAIR_MATRIX_STEPS=${totalSteps}`,`FAIR_MATRIX_STALLS=${totalStalls}`,`MIN_FAIR_WIN_RATE=${(minRate*100).toFixed(1)}%`,`MAX_FAIR_WIN_RATE=${(maxRate*100).toFixed(1)}%`,`CAST_COVERAGE=${castCoverage}`,...matrix.map((x,i)=>`BUILD${i+1}=${x.load};W${x.wins};L${x.losses};S${x.stalls};RATE=${(rates[i]*100).toFixed(1)}%;CASTS=${Object.entries(x.casts).map(([k,v])=>k+':'+v).join(',')}`),`ERRORS=${runtimeErrors.join('|')}`],{ok,score,catalog,roles,masteries,ui,fairBalance,progression,stable,visual,ux,persistence,discovery,totalSteps,totalStalls,minRate,maxRate,castCoverage,matrix,errors:runtimeErrors});
})();
