'use strict';
(()=>{
const q=new URLSearchParams(location.search),ui=q.has('goal4phase4ui'),soak=q.has('goal4phase4');if(!ui&&!soak)return;const api=window.DopamineSkills,g4=window.DopamineGoal4,fun=window.DopamineGoal4Fun,p=window.DopamineSkillProgression;
function report(id,rows,obj){active=false;pausedForBrain=true;document.body.innerHTML=`<pre id="${id}" style="white-space:pre-wrap;background:#07101a;color:#eaf3ff;padding:18px;font:13px/1.5 ui-monospace,monospace">${rows.join('\n')}</pre>`;window[id]=obj}
function unlockAll(lv=16){p.reset();for(const id of ['Firebolt','Whirlwind','Dash','Slam','Scorch','Wisp'])p.grantDrop(id,lv,60);g4.debugUnlockAll(lv);brain.skills=['Slash','Whirlwind','Slam'];saveBrain()}
if(ui){let err='';let cards=0,corner=false,tiny=false;try{unlockAll(16);g4.renderLab();cards=document.querySelectorAll('.g4skill').length;const loot=document.getElementById('g3loot'),css=loot&&getComputedStyle(loot);corner=!!css&&css.right!=='auto'&&css.top==='auto'&&parseFloat(css.width)<=190;tiny=!!css&&parseFloat(getComputedStyle(loot.querySelector('b')).fontSize)<=9}catch(e){err=e.message}const masteryCount=fun?Object.keys(fun.masteries).length:0,ok=cards===30&&corner&&tiny&&fun?.improvements===20&&masteryCount===23&&!err&&runtimeErrors.length===0;report('__DOPAMINE_GOAL4_PHASE4_UI',[`GOAL4_PHASE4_UI_OK=${ok}`,`ARSENAL_CARDS=${cards}`,`DROP_BOTTOM_RIGHT=${corner}`,`DROP_TEXT_COMPACT=${tiny}`,`FUN_IMPROVEMENTS=${fun?.improvements||0}`,`MASTERY_TRACKS=${masteryCount}`,`EXCEPTION=${err}`,`ERRORS=${runtimeErrors.join('|')}`],{ok,cards,corner,tiny,masteryCount,err,errors:runtimeErrors});return}
unlockAll(16);pausedForBrain=false;active=false;const ids=api.ids(),originalSeed=baseSeed,builds=[['Slash','Whirlwind','Slam'],['Firebolt','Dash','Scorch'],['Wisp','FrostLance','ChainLightning'],['Meteor','Orbit','ChainHook'],['ShieldCharge','BladeStorm','Riposte'],['FrostNova','FrozenOrb','Glacier'],['Thunderstep','StormTotem','BallLightning'],['VenomFang','PlagueBurst','AcidPool'],['ShadowKnives','Ricochet','Barrage'],['BoneGolem','RavenSwarm','GravityWell']];const agg={sim:0,steps:0,rooms:0,wins:0,losses:0,stalls:0,truncated:0,casts:Object.fromEntries(ids.map(id=>[id,0])),byBuild:builds.map((b,i)=>({i,load:b.join('>'),wins:0,losses:0,stalls:0})),stallInfo:[]};let stop=false;
while(!stop&&agg.sim<3600&&agg.steps<155000&&!runtimeErrors.length){depth=1+(agg.rooms%30);baseSeed=(originalSeed+Math.imul(agg.rooms+1,104729))>>>0;const bi=agg.rooms%builds.length;brain.skills=[...builds[bi]];saveBrain();beginRoom();let local=0,ended=false;while(active&&local<2600&&!runtimeErrors.length){if(agg.sim>=3600){ended=true;break}step(.035);local++;agg.steps++;agg.sim+=.035}for(const id of ids)agg.casts[id]+=(skillCasts[id]||0);const live=en.filter(e=>!e.dead);if(ended&&active){agg.truncated++;active=false;stop=true}else if(active&&local>=2600){agg.stalls++;agg.byBuild[bi].stalls++;agg.stallInfo.push({room:agg.rooms,depth,build:builds[bi],clock:+roomClock.toFixed(1),live:live.length,decision:lastDecision});active=false}else if(P.dead||live.length){agg.losses++;agg.byBuild[bi].losses++}else{agg.wins++;agg.byBuild[bi].wins++}agg.rooms++}
baseSeed=originalSeed;const rates=agg.byBuild.map(x=>x.wins/Math.max(1,x.wins+x.losses)),minRate=Math.min(...rates),maxRate=Math.max(...rates),overall=agg.wins/Math.max(1,agg.wins+agg.losses),castCoverage=ids.every(id=>agg.casts[id]>0),balanced=minRate>=.15&&overall>=.42,ok=agg.sim>=3599&&agg.stalls===0&&castCoverage&&balanced&&runtimeErrors.length===0;report('__DOPAMINE_GOAL4_PHASE4',[`GOAL4_PHASE4_OK=${ok}`,`SIM_SECONDS=${agg.sim.toFixed(1)}`,`STEPS=${agg.steps}`,`ROOMS=${agg.rooms}`,`WINS=${agg.wins}`,`LOSSES=${agg.losses}`,`OVERALL_WIN_RATE=${(overall*100).toFixed(1)}%`,`MIN_BUILD_WIN_RATE=${(minRate*100).toFixed(1)}%`,`MAX_BUILD_WIN_RATE=${(maxRate*100).toFixed(1)}%`,`STALLS=${agg.stalls}`,`CAST_COVERAGE=${castCoverage}`,`CASTS=${ids.map(id=>id+':'+agg.casts[id]).join(',')}`,...agg.byBuild.map((x,i)=>`BUILD${i+1}=${x.load};W${x.wins};L${x.losses};S${x.stalls};RATE=${(rates[i]*100).toFixed(1)}%`),`STALL_INFO=${JSON.stringify(agg.stallInfo)}`,`ERRORS=${runtimeErrors.join('|')}`],{ok,...agg,overall,minRate,maxRate,castCoverage,balanced,errors:runtimeErrors});
})();
