'use strict';
(()=>{
const q=new URLSearchParams(location.search),final=q.has('goal4final'),prog=q.has('goal4finalprogression');if(!final&&!prog)return;const api=window.DopamineSkills,cat=window.DopamineGoal4Catalog,g4=window.DopamineGoal4,fun=window.DopamineGoal4Fun,gap=window.DopamineGoal4GapPass,polish=window.DopamineGoal4FinalPolish,p=window.DopamineSkillProgression;
function report(id,rows,obj){active=false;pausedForBrain=true;document.body.innerHTML=`<pre id="${id}" style="white-space:pre-wrap;background:#07101a;color:#eaf3ff;padding:18px;font:13px/1.5 ui-monospace,monospace">${rows.join('\n')}</pre>`;window[id]=obj}
function unlockAll(lv=16){p.reset();for(const id of ['Firebolt','Whirlwind','Dash','Slam','Scorch','Wisp'])p.grantDrop(id,lv,60);g4.debugUnlockAll(lv)}
if(prog){p.reset();g4.debugReset();brain.skills=['Slash',null,null];saveBrain();pausedForBrain=false;active=false;const startOwned=api.ownedIds().length,unlockAt={},start=0;for(const id of api.ownedIds())unlockAt[id]=0;let sim=0,steps=0,rooms=0,stalls=0,maxDepth=1;while(sim<2400&&api.ownedIds().length<30&&!runtimeErrors.length){depth=Math.min(72,1+Math.floor(rooms/2));maxDepth=Math.max(maxDepth,depth);baseSeed=(4477331+Math.imul(rooms+1,7919))>>>0;beginRoom();let local=0;while(active&&local<2600&&sim<2400&&!runtimeErrors.length){step(.035);local++;steps++;sim+=.035;for(const id of api.ownedIds())if(unlockAt[id]===undefined)unlockAt[id]=sim}if(active&&local>=2600){stalls++;active=false}rooms++}const owned=api.ownedIds().length,all=owned===30,last=Math.max(...Object.values(unlockAt)),newAfter16=g4.newIds().every(id=>unlockAt[id]!==undefined&&api.unlockDepth(id)>=16),drySafe=all&&last<=2100,ok=all&&newAfter16&&drySafe&&stalls===0&&runtimeErrors.length===0;report('__DOPAMINE_GOAL4_FINAL_PROGRESSION',[`GOAL4_FINAL_PROGRESSION_OK=${ok}`,`START_OWNED=${startOwned}`,`DISCOVERED=${owned}/30`,`SIM_SECONDS=${sim.toFixed(1)}`,`STEPS=${steps}`,`ROOMS=${rooms}`,`MAX_DEPTH=${maxDepth}`,`ALL_UNLOCK_SECONDS=${all?last.toFixed(1):'NONE'}`,`STALLS=${stalls}`,`UNLOCK_TIMES=${api.ids().map(id=>id+':'+(unlockAt[id]===undefined?'NONE':unlockAt[id].toFixed(1))).join(',')}`,`ERRORS=${runtimeErrors.join('|')}`],{ok,startOwned,owned,sim,steps,rooms,maxDepth,last,stalls,unlockAt,errors:runtimeErrors});return}
unlockAll(16);const ids=api.ids(),newIds=g4.newIds(),builds=[['Slash','Whirlwind','Slam'],['Firebolt','Dash','Scorch'],['Wisp','FrostLance','ChainLightning'],['Meteor','Orbit','ChainHook'],['ShieldCharge','BladeStorm','Riposte'],['FrostNova','FrozenOrb','Glacier'],['Thunderstep','StormTotem','BallLightning'],['VenomFang','PlagueBurst','AcidPool'],['ShadowKnives','Ricochet','Barrage'],['BoneGolem','RavenSwarm','GravityWell']],originalSeed=baseSeed;
// Verify the five Phase 6 improvements as user-visible behavior, not marker strings only.
g4.renderLab();document.getElementById('skillLabBtn')?.click();
const reps=['FrostLance','ChainLightning','Meteor','ShadowKnives','VenomFang','BoneGolem','GravityWell'];forceRoom(['boss','elite','guard','archer']);for(const id of reps){brain.skills=[id,null,null];castSkill(id,pickTarget(),false,false)}draw();const visual=polish?.visualFamilies>=7&&polish.fxCount()>0,smart=polish?.smartPresets===true&&Object.keys(polish.presets||{}).length>=5,search=polish?.search===true&&polish?.favorites===true&&polish?.buildLibrary===true,persist=polish?.saveBackup===true,discovery=polish?.smartDiscovery===true;
const loot=document.getElementById('g3loot'),cs=loot&&getComputedStyle(loot),br=loot?.getBoundingClientRect(),font=loot?.querySelector('b')&&parseFloat(getComputedStyle(loot.querySelector('b')).fontSize),compact=!!cs&&parseFloat(cs.right)<=12&&parseFloat(cs.bottom)<=14&&(br?.width||999)<=190&&font<=9;
const matrix=builds.map((load,i)=>({i,load:load.join('>'),wins:0,losses:0,stalls:0,casts:Object.fromEntries(load.map(id=>[id,0]))}));let totalSteps=0,totalStalls=0;for(const b of matrix){for(let d=1;d<=30&&!runtimeErrors.length;d++){depth=d;baseSeed=(originalSeed+Math.imul(d,104729))>>>0;brain.skills=b.load.split('>');saveBrain();beginRoom();let local=0;while(active&&local<2600&&!runtimeErrors.length){step(.035);local++;totalSteps++}for(const id of Object.keys(b.casts))b.casts[id]+=(skillCasts[id]||0);const live=en.filter(e=>!e.dead);if(active&&local>=2600){b.stalls++;totalStalls++;active=false}else if(P.dead||live.length)b.losses++;else b.wins++}}
baseSeed=originalSeed;const rates=matrix.map(x=>x.wins/30),minRate=Math.min(...rates),maxRate=Math.max(...rates),castCoverage=matrix.every(x=>Object.values(x.casts).every(n=>n>0));const catalog=ids.length===30&&newIds.length===23&&new Set(newIds.map(id=>api.get(id).behavior)).size===23,roles=['Melee','Projectile','Spell','Minion','Movement','DoT'].every(t=>ids.some(id=>api.hasTag(id,t)))&&ids.some(id=>String(api.get(id).role||'').toLowerCase().includes('control')),masteries=fun?.improvements===20&&Object.keys(fun.masteries||{}).length===23&&gap?.improvements===10,fair=totalStalls===0&&minRate>=.20&&maxRate<=.88&&castCoverage,progression=newIds.every(id=>api.unlockDepth(id)>=16&&api.unlockDepth(id)<=60)&&new Set(newIds.map(id=>api.unlockDepth(id))).size===23&&api.effective('FrostLance').baseDamage>api.get('FrostLance').baseDamage,stable=runtimeErrors.length===0&&totalStalls===0&&castCoverage;
let score=0;score+=catalog?1.5:0;score+=roles?.75:0;score+=masteries?1:0;score+=compact?.75:0;score+=fair?1.75:0;score+=progression?.75:0;score+=stable?1:0;score+=visual?.9:0;score+=(smart&&search)?.8:0;score+=(persist&&discovery)?.8:0;score=Math.round(score*10)/10;const ok=score>=9&&catalog&&compact&&fair&&stable&&visual&&smart&&search&&persist&&discovery;
report('__DOPAMINE_GOAL4_FINAL',[`GOAL4_FINAL_OK=${ok}`,`COMPLETENESS_SCORE=${score.toFixed(1)}/10`,`SKILL_COUNT=${ids.length}`,`DISTINCT_NEW_BEHAVIORS=${new Set(newIds.map(id=>api.get(id).behavior)).size}`,`CATALOG=${catalog}`,`ROLE_COVERAGE=${roles}`,`MASTERY_AND_FUN_PASSES=${masteries}`,`COMPACT_BOTTOM_RIGHT_DROP=${compact}`,`VISUAL_FAMILIES=${polish?.visualFamilies||0}`,`VISUAL_ACTIVE=${visual}`,`SMART_PRESETS=${smart}`,`SEARCH_FAVORITES_BUILD_LIBRARY=${search}`,`SAVE_BACKUP=${persist}`,`SMART_DISCOVERY=${discovery}`,`FAIR_BALANCE=${fair}`,`FAIR_MATRIX_STEPS=${totalSteps}`,`FAIR_MATRIX_STALLS=${totalStalls}`,`MIN_FAIR_WIN_RATE=${(minRate*100).toFixed(1)}%`,`MAX_FAIR_WIN_RATE=${(maxRate*100).toFixed(1)}%`,`CAST_COVERAGE=${castCoverage}`,...matrix.map((x,i)=>`BUILD${i+1}=${x.load};W${x.wins};L${x.losses};S${x.stalls};RATE=${(rates[i]*100).toFixed(1)}%;CASTS=${Object.entries(x.casts).map(([k,v])=>k+':'+v).join(',')}`),`ERRORS=${runtimeErrors.join('|')}`],{ok,score,catalog,roles,masteries,compact,visual,smart,search,persist,discovery,fair,totalSteps,totalStalls,minRate,maxRate,castCoverage,matrix,errors:runtimeErrors});
})();
