'use strict';
(()=>{
const q=new URLSearchParams(location.search),smoke=q.has('goal4test'),soak=q.has('goal4soak');if(!smoke&&!soak)return;
const api=window.DopamineSkills,g4=window.DopamineGoal4,p=window.DopamineSkillProgression;if(!api||!g4||!p)return;
function report(id,rows,obj){active=false;pausedForBrain=true;document.body.innerHTML=`<pre id="${id}" style="white-space:pre-wrap;background:#07101a;color:#eaf3ff;padding:18px;font:13px/1.5 ui-monospace,monospace">${rows.join('\n')}</pre>`;window[id]=obj}
function unlockAll(lv=14){p.reset();for(const id of ['Firebolt','Whirlwind','Dash','Slam','Scorch','Wisp'])p.grantDrop(id,lv,60);g4.debugUnlockAll(lv);brain.skills=['Slash','Whirlwind','Slam'];saveBrain()}
if(smoke){unlockAll(14);const ids=api.ids(),casts={},damage={};let castOk=true;for(const id of ids){forceRoom(['boss','elite','guard','rot','archer','necro']);brain.skills=[id,null,null];const t=pickTarget(),ok=castSkill(id,t,false,false);casts[id]=!!ok;castOk=castOk&&!!ok;for(let i=0;i<130&&active;i++)step(.035);damage[id]=+(dmg[api.get(id).name]||dmg[id]||0).toFixed(1);active=false}
 document.getElementById('skillLabBtn')?.click();const uiCards=document.querySelectorAll('.g4skill').length,distinct=new Set(g4.newIds().map(id=>api.get(id).behavior)).size,allNamed=new Set(ids.map(id=>api.get(id).name)).size===30,roles=['Melee','Projectile','Spell','Minion','Control','Movement','DoT'].every(tag=>ids.some(id=>api.hasTag(id,tag)||String(api.get(id).role||'').includes(tag))),loot=document.getElementById('g3loot'),css=loot?getComputedStyle(loot):null,corner=!!css&&css.right!=='auto'&&css.top==='auto'&&parseFloat(css.width)<=190,tiny=!!css&&parseFloat(css.fontSize||'8')<=10;
 const ok=ids.length===30&&g4.newIds().length===23&&distinct===23&&allNamed&&roles&&castOk&&uiCards===30&&corner&&tiny&&runtimeErrors.length===0;
 report('__DOPAMINE_GOAL4_TEST',[`GOAL4_TEST_OK=${ok}`,`SKILL_COUNT=${ids.length}`,`NEW_SKILLS=${g4.newIds().length}`,`DISTINCT_NEW_BEHAVIORS=${distinct}`,`UNIQUE_NAMES=${allNamed}`,`ROLE_COVERAGE=${roles}`,`ALL_DIRECT_CASTS=${castOk}`,`ARSENAL_CARDS=${uiCards}`,`DROP_BOTTOM_RIGHT=${corner}`,`DROP_TEXT_COMPACT=${tiny}`,`CASTS=${ids.map(id=>id+':'+casts[id]).join(',')}`,`DAMAGE=${ids.map(id=>id+':'+damage[id]).join(',')}`,`ERRORS=${runtimeErrors.join('|')}`],{ok,ids,casts,damage,uiCards,distinct,allNamed,roles,corner,tiny,errors:runtimeErrors});return}
unlockAll(16);pausedForBrain=false;active=false;const ids=api.ids(),originalSeed=baseSeed,builds=[['Slash','Whirlwind','Slam'],['Firebolt','Dash','Scorch'],['Wisp','FrostLance','ChainLightning'],['Meteor','Orbit','ChainHook'],['ShieldCharge','BladeStorm','Riposte'],['FrostNova','FrozenOrb','Glacier'],['Thunderstep','StormTotem','BallLightning'],['VenomFang','PlagueBurst','AcidPool'],['ShadowKnives','Ricochet','Barrage'],['BoneGolem','RavenSwarm','GravityWell']];
const agg={sim:0,steps:0,rooms:0,wins:0,losses:0,stalls:0,truncated:0,casts:Object.fromEntries(ids.map(id=>[id,0])),byBuild:builds.map((b,i)=>({i,load:b.join('>'),wins:0,losses:0,stalls:0})),stallInfo:[]};let stop=false;
while(!stop&&agg.sim<3600&&agg.steps<155000&&!runtimeErrors.length){depth=1+(agg.rooms%30);baseSeed=(originalSeed+Math.imul(agg.rooms+1,104729))>>>0;const bi=agg.rooms%builds.length;brain.skills=[...builds[bi]];saveBrain();beginRoom();let local=0,ended=false;while(active&&local<2600&&!runtimeErrors.length){if(agg.sim>=3600){ended=true;break}step(.035);local++;agg.steps++;agg.sim+=.035}for(const id of ids)agg.casts[id]+=(skillCasts[id]||0);const live=en.filter(e=>!e.dead);if(ended&&active){agg.truncated++;active=false;stop=true}else if(active&&local>=2600){agg.stalls++;agg.byBuild[bi].stalls++;agg.stallInfo.push({room:agg.rooms,depth,build:builds[bi],clock:+roomClock.toFixed(1),live:live.length,decision:lastDecision});active=false}else if(P.dead||live.length){agg.losses++;agg.byBuild[bi].losses++}else{agg.wins++;agg.byBuild[bi].wins++}agg.rooms++}
baseSeed=originalSeed;const castCoverage=ids.every(id=>agg.casts[id]>0),buildCoverage=agg.byBuild.every(x=>x.wins+x.losses+x.stalls>0),clockOk=agg.sim>=3599,noErrors=runtimeErrors.length===0,ok=clockOk&&agg.stalls===0&&castCoverage&&buildCoverage&&noErrors;
report('__DOPAMINE_GOAL4_SOAK',[`GOAL4_SOAK_OK=${ok}`,`SIM_SECONDS=${agg.sim.toFixed(1)}`,`STEPS=${agg.steps}`,`ROOMS=${agg.rooms}`,`WINS=${agg.wins}`,`LOSSES=${agg.losses}`,`STALLS=${agg.stalls}`,`TRUNCATED_FINAL_ROOMS=${agg.truncated}`,`CAST_COVERAGE=${castCoverage}`,`BUILD_COVERAGE=${buildCoverage}`,`CASTS=${ids.map(id=>id+':'+agg.casts[id]).join(',')}`,...agg.byBuild.map(x=>`BUILD${x.i+1}=${x.load};W${x.wins};L${x.losses};S${x.stalls}`),`STALL_INFO=${JSON.stringify(agg.stallInfo)}`,`ERRORS=${runtimeErrors.join('|')}`],{ok,...agg,castCoverage,buildCoverage,errors:runtimeErrors});
})();
