'use strict';
(()=>{
const q=new URLSearchParams(location.search),goal4Mode=['goal4test','goal4soak','goal4phase4','goal4final','goal4progression'].some(k=>q.has(k));
const legacyGate=!goal4Mode&&['selftest','goal3test','goal3mobiletest','goal3soak','goal3progressiontest','goal3progressionsoak','goal3loadoutuitest','goal3skillsoak','goal3signofftest','goal3freshbenchmark','goal3multisoak','goal3diversity'].some(k=>q.has(k));
if(legacyGate)return;
const base=window.DopamineSkills,cat=window.DopamineGoal4Catalog;if(!base||!cat)return;
const baseIds=base.ids(),newIds=cat.ids(),allIds=[...baseIds,...newIds],KEY='dopamineGoal4ProgressV10';
const fresh=()=>({schema:10,owned:{},resonance:{},drops:0,upgrades:0,pity:0,lastDrop:null,history:[],totalCasts:{},totalDamage:{}});let state=fresh();
if(!goal4Mode){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.owned)state={...fresh(),...x,owned:{...x.owned},resonance:{...(x.resonance||{})},totalCasts:{...(x.totalCasts||{})},totalDamage:{...(x.totalDamage||{})}}}catch(e){}}
const save=()=>{if(goal4Mode)return;try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const oldDef=id=>base.get(id),custom=id=>cat.get(id),get=id=>custom(id)||oldDef(id),isNew=id=>newIds.includes(id);
const oldOwned=id=>base.isOwned?base.isOwned(id):true,oldLevel=id=>base.getLevel?base.getLevel(id):1;
function owned(id){return isNew(id)?(state.owned[id]||0)>0:oldOwned(id)}function level(id){return isNew(id)?clamp(state.owned[id]|0,0,20):oldLevel(id)}
function capForMonster(ml){return clamp(1+Math.floor((Math.max(1,ml)-1)/2),1,20)}
function effectiveNew(id,lv=level(id)||1){const d=custom(id),n=Math.max(0,lv-1),g=d.growth||.065;return{...d,level:lv,baseDamage:d.baseDamage*(1+g*n),cooldown:d.cooldown*(1-Math.min(.14,n*.006)),area:d.area?d.area*(1+Math.min(.2,n*.009)):d.area,range:d.range?d.range*(1+Math.min(.13,n*.006)):d.range,duration:d.duration?d.duration*(1+Math.min(.16,n*.007)):d.duration,tickRate:d.tickRate?d.tickRate*(1-Math.min(.12,n*.0055)):d.tickRate,projectileSpeed:d.projectileSpeed?d.projectileSpeed*(1+Math.min(.15,n*.007)):d.projectileSpeed};}
function effective(id){return isNew(id)?effectiveNew(id):base.effective?base.effective(id):get(id)}
function unlockDepth(id){return isNew(id)?custom(id).unlock:(base.unlockDepth?base.unlockDepth(id):1)}
function ownedIds(){return allIds.filter(owned)}function nextUnlock(){const id=allIds.filter(id=>!owned(id)).sort((a,b)=>unlockDepth(a)-unlockDepth(b))[0];return id?{id,monsterLevel:unlockDepth(id)}:null}
function syncBrain(){const load=Array.isArray(brain.skills)?brain.skills.slice(0,3):[];while(load.length<3)load.push(null);const seen=new Set();brain.skills=load.map(id=>{if(!id||!owned(id)||seen.has(id))return null;seen.add(id);return id});if(!brain.skills.some(Boolean)&&owned('Slash'))brain.skills[0]='Slash';brain.name='CUSTOM';brain.custom=true;for(const [i,el] of [brainInputs?.skill1,brainInputs?.skill2,brainInputs?.skill3].entries()){if(!el)continue;el.innerHTML='<option value="">— EMPTY —</option>'+ownedIds().map(id=>`<option value="${id}">${get(id).name} • Lv ${level(id)}</option>`).join('');el.value=brain.skills[i]||'';el.onchange=()=>{const vals=[brainInputs.skill1.value||null,brainInputs.skill2.value||null,brainInputs.skill3.value||null],u=[];brain.skills=vals.map(x=>x&&!u.includes(x)&&owned(x)?(u.push(x),x):null);saveBrain();syncBrain();renderLab();hud()}}
 try{saveBrain();updateBrainTicker()}catch(e){}
 return brain.skills;
}
function equip(id,slot){slot=clamp(slot|0,0,2);if(id&&!owned(id)){toast(`${get(id)?.name||id} is locked`);return false}const load=syncBrain().slice(),from=id?load.indexOf(id):-1,repl=load[slot];if(from>=0&&from!==slot)load[from]=repl||null;load[slot]=id||null;brain.skills=load;saveBrain();syncBrain();renderLab();hud();return true}
function progress(){const old=base.progress?base.progress():{};return{...old,goal4:{...state,owned:{...state.owned},resonance:{...state.resonance}},drops:(old.drops||0)+state.drops,upgrades:(old.upgrades||0)+state.upgrades,unlocks:ownedIds().length,lastDrop:state.lastDrop||old.lastDrop||null}}
const extended=Object.freeze({...base,version:'Goal 04 30-Skill Runtime v1.0',ids:()=>[...allIds],get,hasTag:(id,tag)=>!!get(id)?.tags?.includes(tag),byTag:tag=>allIds.filter(id=>get(id)?.tags?.includes(tag)),isOwned:owned,getLevel:level,unlockDepth,effective,ownedIds,nextUnlock,equip,loadout:()=>syncBrain().slice(),progress});window.DopamineSkills=extended;

const sty=document.createElement('style');sty.id='g4styles';sty.textContent=`
#skillDropFeed{right:8px!important;left:auto!important;top:auto!important;bottom:62px!important;width:min(176px,44vw)!important;gap:3px!important}#skillDropFeed div{font:800 6px/1.2 system-ui!important;padding:4px 6px!important;border-radius:6px!important;text-align:right!important}#g3loot{left:auto!important;right:8px!important;top:auto!important;bottom:10px!important;transform:translateY(6px) scale(.96)!important;min-width:0!important;width:min(176px,44vw)!important;text-align:right!important;padding:5px 7px!important;border-radius:7px!important}#g3loot.show{transform:none!important}#g3loot small{font:900 5px/1.1 system-ui!important}#g3loot b{font:1000 8px/1.15 system-ui!important;margin:1px 0!important}#g3loot span{font:800 6px/1.1 system-ui!important}#g3worldloot .g3drop{font-size:6px!important}#g3worldloot .g3drop i{width:4px!important;height:18px!important}#g3worldloot .g3drop b{font-size:6px!important;padding:2px 4px!important;max-width:118px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
.g4collection{font:800 9px/1.35 system-ui;background:#0a1725;border:1px solid #29435e;border-radius:9px;padding:8px;margin:8px 0}.g4toolbar{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.g4toolbar button{min-height:34px;font-size:8px}.g4load{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:8px 0}.g4slot{border:1px solid #405b7e;border-radius:9px;padding:7px;min-height:64px;background:#091421;display:grid;gap:3px}.g4slot small{font-size:7px;opacity:.6}.g4slot b{font-size:10px}.g4grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(185px,1fr));gap:6px}.g4skill{border:1px solid #30445f;border-radius:9px;padding:8px;background:#08131f}.g4skill.locked{opacity:.45}.g4skill h3{font-size:11px;margin:0}.g4skill .g4meta{font-size:7px;line-height:1.35;opacity:.76;margin:5px 0}.g4skill .g4identity{font-size:8px;line-height:1.3;min-height:31px}.g4equip{display:grid;grid-template-columns:repeat(3,1fr);gap:3px}.g4equip button{min-height:30px;font-size:7px}.g4equip button.on{outline:2px solid #9fe7ff}.g4tag{display:inline-block;font-size:6px;padding:2px 4px;border:1px solid #405876;border-radius:99px;margin:2px 2px 0 0}.g4new{color:#c8a4ff}.g4dropmini{position:fixed;right:8px;bottom:10px;z-index:40;width:min(176px,44vw);background:#07111eef;border:1px solid #7750a8;border-radius:7px;padding:5px 7px;text-align:right;font:800 6px/1.2 system-ui;box-shadow:0 5px 16px #000a;pointer-events:none}.g4dropmini b{font-size:8px;display:block}.g4dropmini span{opacity:.7}.g4filter.on{outline:2px solid #b8ddff}@media(max-width:520px){.g4load{grid-template-columns:1fr}.g4grid{grid-template-columns:1fr}.g4dropmini{right:5px;bottom:7px;width:min(150px,42vw)}}`;
document.head.appendChild(sty);
function toast(text,color='#cda7ff'){try{announce(text.toUpperCase(),color)}catch(e){}const old=document.querySelector('.g4dropmini');if(old)old.remove();const x=document.createElement('div');x.className='g4dropmini';x.innerHTML=`<b>${text}</b><span>Goal 04 skill progression</span>`;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}

function dropLevel(ml,e){let x=capForMonster(ml)+(e?.type==='elite'?1:e?.type==='boss'?2:0)+(rng()<.15?1:0);return clamp(x,1,20)}
function grant(id,lv,ml=1,quiet=false){if(!isNew(id)||unlockDepth(id)>ml)return{accepted:false};lv=clamp(lv|0,1,20);state.drops++;state.lastDrop={id,level:lv,monsterLevel:ml};const old=level(id);let kind='resonance',next=old;if(!old){state.owned[id]=lv;kind='unlock';next=lv}else if(lv>old){state.owned[id]=lv;state.upgrades++;kind='upgrade';next=lv;state.resonance[id]=0}else{state.resonance[id]=(state.resonance[id]||0)+1;if(state.resonance[id]>=3&&old<capForMonster(ml)){state.owned[id]=old+1;state.upgrades++;state.resonance[id]=0;kind='upgrade';next=old+1}}
 state.pity=0;state.history.unshift({id,level:lv,monsterLevel:ml,kind,t:Date.now()});state.history=state.history.slice(0,30);save();if(kind==='unlock'){const empty=syncBrain().findIndex(x=>!x);if(empty>=0)equip(id,empty)}syncBrain();renderLab();if(!quiet)toast(kind==='unlock'?`NEW • ${get(id).name} Lv ${next}`:kind==='upgrade'?`${get(id).name} ${old} → ${next}`:`${get(id).name} resonance +1`);return{accepted:true,kind,oldLevel:old,newLevel:next}}
function monsterLevel(e){return Math.max(1,(depth|0)+(e?.type==='elite'?1:e?.type==='boss'?3:0))}
function maybeDrop(e){if(!e)return;const ml=monsterLevel(e),eligible=newIds.filter(id=>unlockDepth(id)<=ml),locked=eligible.filter(id=>!owned(id)).sort((a,b)=>unlockDepth(a)-unlockDepth(b));if(!eligible.length)return;state.pity++;const boss=e.type==='boss',elite=e.type==='elite',guaranteed=locked.length&&state.pity>=10;let chance=boss?.72:elite?.24:.055+Math.min(.045,ml*.0012);if(!guaranteed&&rng()>=chance)return;let id;if(guaranteed)id=locked[0];else if(boss&&locked.length&&rng()<.78)id=locked[0];else{const weighted=eligible.flatMap(x=>owned(x)?[x]:[x,x,x,x]);id=weighted[(rng()*weighted.length)|0]}grant(id,dropLevel(ml,e),ml,false)}
const oldKill=kill;kill=function(e){const dead=e?.dead;oldKill(e);if(e&&!dead&&e.dead)maybeDrop(e)};

const cd=Object.create(null),age=Object.create(null),shots=[],zones=[],delays=[],summons=[],channels=[],poisons=new Map(),slows=new Map(),shreds=new Map();let lastHitAt=-999;
const oldTake=takeDamage;takeDamage=function(a,s=false){const hp=P.hp;oldTake(a,s);if(P.hp<hp)lastHitAt=roomClock};
function roll(d,m=1){return(d.baseDamage||0)*(.92+rng()*.16)*m}function alive(){return en.filter(e=>!e.dead)}function nearest(x,y,r=Infinity,exclude=null){let b=null,bd=r;for(const e of en)if(!e.dead&&(!exclude||!exclude.has(e.id))){const z=Math.hypot(e.x-x,e.y-y);if(z<bd){bd=z;b=e}}return b}
function enemiesAt(x,y,r){return en.filter(e=>!e.dead&&Math.hypot(e.x-x,e.y-y)<=r+e.r)}function slow(e,pct,dur){if(!e||e.dead)return;const k=e.id,s=slows.get(k);if(!s){slows.set(k,{e,base:e.spd,life:dur,pct});e.spd*=1-pct}else{s.life=Math.max(s.life,dur);if(pct>s.pct){e.spd=s.base*(1-pct);s.pct=pct}}}
function poison(e,power,stacks=1){if(!e||e.dead)return;const p=poisons.get(e.id)||{e,stacks:0,power:0,life:0,tick:.2};p.stacks=Math.min(12,p.stacks+stacks);p.power=Math.max(p.power,power);p.life=4;poisons.set(e.id,p)}
const oldHit=hit;hit=function(e,a,k,crit=false,kb=0){if(!e||e.dead)return;const s=shreds.get(e.id),mult=s?1+s.amount:1,was=e.hp;oldHit(e,a*mult,k,crit,kb);const id=allIds.find(x=>get(x)?.name===k||x===k);if(id){state.totalDamage[id]=(state.totalDamage[id]||0)+Math.min(was,a*mult);if(!goal4Mode)save()}};
function castMark(id){const d=effective(id);cd[id]=d.cooldown;age[id]=0;skillCasts[id]=(skillCasts[id]||0)+1;state.totalCasts[id]=(state.totalCasts[id]||0)+1;if(!goal4Mode)save();try{setDecision('CAST '+d.name.toUpperCase());announce(d.name.toUpperCase(),d.color||'#fff')}catch(e){}}
function spawnShot(d,x,y,vx,vy,extra={}){shots.push({x,y,vx,vy,r:d.projectileRadius||5,life:d.duration||2.6,def:d,hit:new Set(),tick:0,bounces:d.bounces||0,...extra})}
function fireToward(d,t,extra={}){if(!t)return false;const dx=t.x-P.x,dy=t.y-P.y,l=len(dx,dy),s=d.projectileSpeed||340;spawnShot(d,P.x,P.y,dx/l*s,dy/l*s,extra);ring(P.x,P.y,18,d.color,2);return true}
function chainFrom(d,start,max=d.chains||4,mult=.82){let cur=start,seen=new Set();for(let i=0;i<max&&cur;i++){seen.add(cur.id);hit(cur,roll(d,Math.pow(mult,i)),d.name,false,0);ring(cur.x,cur.y,18,d.color,2);cur=nearest(cur.x,cur.y,d.chainRange||110,seen)}}
function executeNew(id,t){const d=effective(id);if(!d)return false;switch(d.behavior){
 case'pierce_chill':return fireToward(d,t,{mode:'pierce_chill'});
 case'chain':if(!t)return false;chainFrom(d,t,d.chains||4,.82);return true;
 case'meteor':if(!t)return false;delays.push({kind:'meteor',x:t.x,y:t.y,left:d.delay||.8,def:d});ring(t.x,t.y,d.area,'#ff9a62',2);return true;
 case'orbit':zones.push({kind:'orbit',x:P.x,y:P.y,r:d.area,life:d.duration,tick:0,def:d});return true;
 case'hook':if(!t)return false;{const dx=P.x-t.x,dy=P.y-t.y,l=len(dx,dy);t.x=P.x-dx/l*(P.r+t.r+17);t.y=P.y-dy/l*(P.r+t.r+17);hit(t,roll(d),d.name,false,4);ring(t.x,t.y,24,d.color,2);return true}
 case'charge':if(!t)return false;{const sx=P.x,sy=P.y,dx=t.x-P.x,dy=t.y-P.y,l=len(dx,dy),travel=Math.min(d.range,l);P.x=clamp(P.x+dx/l*travel,P.r+10,W-P.r-10);P.y=clamp(P.y+dy/l*travel,P.r+40,H-P.r-36);collideObstacle(P);for(const e of alive())if(segmentPointDistance(e.x,e.y,sx,sy,P.x,P.y)<d.area+e.r)hit(e,roll(d),d.name,false,d.knockback||20);ring(P.x,P.y,d.area,d.color,3);return true}
 case'moving_zone':if(!t)return false;zones.push({kind:'blade',x:t.x,y:t.y,r:d.area,life:d.duration,tick:0,def:d});return true;
 case'counter':{const x=nearest(P.x,P.y,d.range);if(!x)return false;hit(x,roll(d),d.name,true,22);ring(P.x,P.y,d.range,d.color,4);return true}
 case'freeze_nova':{for(const e of enemiesAt(P.x,P.y,d.area)){hit(e,roll(d),d.name,false,8);slow(e,.72,1.15)}ring(P.x,P.y,d.area,d.color,5);return true}
 case'orb_pulse':return fireToward(d,t,{mode:'orb_pulse',tick:0});
 case'glacier_line':if(!t)return false;{const a=Math.atan2(t.y-P.y,t.x-P.x);zones.push({kind:'glacier',x:t.x,y:t.y,a,r:d.area,life:4.2,tick:0,def:d});ring(t.x,t.y,30,d.color,3);return true}
 case'tele_chain':if(!t)return false;{const dx=t.x-P.x,dy=t.y-P.y,l=len(dx,dy);P.x=clamp(t.x-dx/l*(P.r+t.r+12),P.r+10,W-P.r-10);P.y=clamp(t.y-dy/l*(P.r+t.r+12),P.r+40,H-P.r-36);collideObstacle(P);chainFrom({...d,chains:3,chainRange:d.chainRange||95},t,3,.72);ring(P.x,P.y,34,d.color,4);return true}
 case'turret':summons.push({kind:'turret',x:P.x+25,y:P.y-12,life:d.duration,tick:0,def:d});return true;
 case'ball_pulse':return fireToward(d,t,{mode:'ball_pulse',tick:0});
 case'poison':if(!t)return false;hit(t,roll(d),d.name,false,3);poison(t,d.baseDamage*.13,1);return true;
 case'poison_detonate':{let did=false;for(const [k,p] of [...poisons])if(!p.e.dead&&dist(P,p.e)<=d.area){hit(p.e,roll(d)*(1+p.stacks*.36),d.name,false,12);poisons.delete(k);did=true}if(!did)for(const e of enemiesAt(P.x,P.y,d.area))hit(e,roll(d),d.name,false,5);ring(P.x,P.y,d.area,d.color,5);return true}
 case'shred_pool':if(!t)return false;zones.push({kind:'acid',x:t.x,y:t.y,r:d.area,life:d.duration,tick:0,def:d});ring(t.x,t.y,d.area,d.color,3);return true;
 case'fan':if(!t)return false;{const a=Math.atan2(t.y-P.y,t.x-P.x),s=d.projectileSpeed||330;for(let i=-2;i<=2;i++){const z=a+i*.14;spawnShot(d,P.x,P.y,Math.cos(z)*s,Math.sin(z)*s,{mode:'simple'})}return true}
 case'bounce':return fireToward(d,t,{mode:'bounce',bounces:d.bounces||3});
 case'barrage':if(!t)return false;channels.push({kind:'barrage',targetId:t.id,left:d.shots||7,tick:0,def:d});return true;
 case'bruiser':summons.push({kind:'bruiser',x:P.x+28,y:P.y,life:d.duration,tick:0,def:d});return true;
 case'swarm':for(let i=0;i<3;i++)summons.push({kind:'raven',x:P.x,y:P.y,life:d.duration,tick:i*.08,phase:i/3*Math.PI*2,def:d});return true;
 case'pull':if(!t)return false;zones.push({kind:'gravity',x:t.x,y:t.y,r:d.area,life:d.duration,tick:0,def:d});ring(t.x,t.y,d.area,d.color,4);return true;
 default:return false}}
const oldSkillState=skillState;skillState=function(id,t,comboBoost=false){if(!isNew(id))return oldSkillState(id,t,comboBoost);const d=effective(id),c=cd[id]||0,a=age[id]||0;if(c>0)return{ok:false,reason:c.toFixed(1)+'s',age:a};const dis=t?dist(P,t):Infinity,k=d.brain?.kind||'single';if(k==='counter')return{ok:roomClock-lastHitAt<2.25&&!!nearest(P.x,P.y,d.range),reason:roomClock-lastHitAt<2.25?'COUNTER READY':'WAIT FOR HIT',age:a};if(k==='utility'){const same=summons.some(s=>s.def.id===id&&s.life>0)||zones.some(z=>z.def.id===id&&z.life>0);return{ok:!same,reason:!same?'READY':'ACTIVE',age:a}}if(k==='single'){const ok=!!t&&dis<=(d.range||80)&&(!d.tags.includes('Projectile')||typeof hasLineOfSight!=='function'||hasLineOfSight(P,t,4));return{ok,reason:ok?'READY':'SEEK RANGE',age:a}}const count=enemiesAt(P.x,P.y,d.area||d.range||100).length,need=d.brain?.minTargets||2,flex=brain.skillFlexAfter||2.5,targetIn=t&&dis<=(d.range||d.area||120);if(count>=need)return{ok:true,reason:'READY',count,need,age:a};if(a>=flex&&targetIn)return{ok:true,forced:true,reason:'FLEX CAST',count,need,age:a};return{ok:false,reason:`WAIT ${count}/${need}`,count,need,age:a}};
const oldCastSkill=castSkill;castSkill=function(id,t,forced=false,fromCombo=false){if(!isNew(id))return oldCastSkill(id,t,forced,fromCombo);if(!owned(id))return false;const ok=executeNew(id,t);if(ok)castMark(id);return ok};
tryScheduledSkills=function(t,aoeOnly=false){for(const id of brain.skills||[]){if(!id||!owned(id))continue;const d=get(id);if(!d)continue;if(aoeOnly&&d.brain?.kind==='single')continue;const st=skillState(id,t,false);if(st.ok&&castSkill(id,t,!!st.forced,false))return true}return false};

function process(dt){for(const id of newIds){cd[id]=Math.max(0,(cd[id]||0)-dt);age[id]=(cd[id]||0)<=0?(age[id]||0)+dt:0}
 for(const [k,p] of [...poisons]){p.life-=dt;p.tick-=dt;if(p.e.dead||p.life<=0){poisons.delete(k);continue}if(p.tick<=0){p.tick=.35;hit(p.e,p.power*p.stacks*.35,'Poison',false,0)}}
 for(const [k,s] of [...slows]){s.life-=dt;if(s.e.dead||s.life<=0){if(!s.e.dead)s.e.spd=Math.max(s.e.spd,s.base);slows.delete(k)}}for(const [k,s] of [...shreds]){s.life-=dt;if(s.life<=0||!en.some(e=>e.id===k&&!e.dead))shreds.delete(k)}
 for(const d of delays){d.left-=dt;if(d.left<=0&&d.life!==-1){d.life=-1;if(d.kind==='meteor'){ring(d.x,d.y,d.def.area,d.def.color,7);burst(d.x,d.y,d.def.color,12);for(const e of enemiesAt(d.x,d.y,d.def.area))hit(e,roll(d.def),d.def.name,false,28)}}}for(let i=delays.length-1;i>=0;i--)if(delays[i].life===-1)delays.splice(i,1);
 for(const c of channels){c.tick-=dt;if(c.tick<=0&&c.left>0){c.tick=c.def.interval||.11;c.left--;const t=en.find(e=>e.id===c.targetId&&!e.dead)||nearest(P.x,P.y,c.def.range);if(t)fireToward(c.def,t,{mode:'simple',damageMult:.62})}}for(let i=channels.length-1;i>=0;i--)if(channels[i].left<=0)channels.splice(i,1);
 for(const p of shots){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;p.tick-=dt;let blocked=false;for(const o of obstacles)if(Math.hypot(p.x-o.x,p.y-o.y)<o.r+p.r){blocked=true;break}if(blocked){p.life=0;continue}if(p.mode==='orb_pulse'||p.mode==='ball_pulse'){if(p.tick<=0){p.tick=p.def.tickRate||.25;for(const e of enemiesAt(p.x,p.y,p.def.area||58))if(!p.hit.has(`${e.id}:${Math.floor(roomClock*4)}`)){hit(e,roll(p.def,p.mode==='ball_pulse'?.58:.62),p.def.name,false,0);p.hit.add(`${e.id}:${Math.floor(roomClock*4)}`);if(p.mode==='orb_pulse')slow(e,.25,.6)}}continue}let target=null;for(const e of en)if(!e.dead&&!p.hit.has(e.id)&&Math.hypot(p.x-e.x,p.y-e.y)<e.r+p.r+4){target=e;break}if(target){p.hit.add(target.id);hit(target,roll(p.def,p.damageMult||1),p.def.name,false,2);if(p.mode==='pierce_chill'){slow(target,.32,1.1);if(p.hit.size>=4)p.life=0}else if(p.mode==='bounce'&&p.bounces>0){p.bounces--;const n=nearest(target.x,target.y,p.def.chainRange||120,p.hit);if(n){const dx=n.x-p.x,dy=n.y-p.y,l=len(dx,dy),s=p.def.projectileSpeed||360;p.vx=dx/l*s;p.vy=dy/l*s}else p.life=0}else p.life=0}}
 for(let i=shots.length-1;i>=0;i--)if(shots[i].life<=0)shots.splice(i,1);
 for(const z of zones){z.life-=dt;z.tick-=dt;if(z.kind==='orbit'){z.x=P.x;z.y=P.y;if(z.tick<=0){z.tick=z.def.tickRate||.24;for(const e of enemiesAt(P.x,P.y,z.r))hit(e,roll(z.def,.7),z.def.name,false,0)}}else if(z.kind==='blade'){const t=nearest(z.x,z.y,240);if(t){const dx=t.x-z.x,dy=t.y-z.y,l=len(dx,dy);z.x+=dx/l*42*dt;z.y+=dy/l*42*dt}if(z.tick<=0){z.tick=z.def.tickRate||.34;for(const e of enemiesAt(z.x,z.y,z.r))hit(e,roll(z.def),z.def.name,false,4)}}else if(z.kind==='glacier'){if(z.tick<=0){z.tick=.32;const dx=Math.cos(z.a)*z.r,dy=Math.sin(z.a)*z.r;for(const e of alive())if(segmentPointDistance(e.x,e.y,z.x-dx*.5,z.y-dy*.5,z.x+dx*.5,z.y+dy*.5)<18+e.r){hit(e,roll(z.def,.68),z.def.name,false,4);slow(e,.55,.7)}}}else if(z.kind==='acid'){if(z.tick<=0){z.tick=z.def.tickRate||.42;for(const e of enemiesAt(z.x,z.y,z.r)){hit(e,roll(z.def),z.def.name,false,0);const s=shreds.get(e.id)||{life:0,amount:0};s.life=1.2;s.amount=Math.min(.35,s.amount+.04);shreds.set(e.id,s)}}}else if(z.kind==='gravity'){for(const e of enemiesAt(z.x,z.y,z.r)){const dx=z.x-e.x,dy=z.y-e.y,l=len(dx,dy);e.x+=dx/l*52*dt;e.y+=dy/l*52*dt}if(z.tick<=0){z.tick=.4;for(const e of enemiesAt(z.x,z.y,z.r))hit(e,roll(z.def,.42),z.def.name,false,0)}}}
 for(let i=zones.length-1;i>=0;i--)if(zones[i].life<=0)zones.splice(i,1);
 for(const s of summons){s.life-=dt;s.tick-=dt;if(s.kind==='turret'&&s.tick<=0){s.tick=s.def.tickRate||.48;const t=nearest(s.x,s.y,s.def.range);if(t)hit(t,roll(s.def),s.def.name,false,0)}else if(s.kind==='bruiser'){const t=nearest(s.x,s.y,320);if(t){const dx=t.x-s.x,dy=t.y-s.y,l=len(dx,dy);s.x+=dx/l*72*dt;s.y+=dy/l*72*dt;if(l<50&&s.tick<=0){s.tick=s.def.tickRate||.62;hit(t,roll(s.def),s.def.name,false,15)}}}else if(s.kind==='raven'){s.phase+=dt*2.4;const t=nearest(s.x,s.y,s.def.range);if(t){s.x+=(t.x+Math.cos(s.phase)*28-s.x)*Math.min(1,dt*4);s.y+=(t.y+Math.sin(s.phase)*28-s.y)*Math.min(1,dt*4);if(s.tick<=0){s.tick=s.def.tickRate||.32;hit(t,roll(s.def,.72),s.def.name,false,0)}}}}
 for(let i=summons.length-1;i>=0;i--)if(summons[i].life<=0)summons.splice(i,1)}
const oldStep=step;step=function(dt){process(dt);oldStep(dt)};
const oldBegin=beginRoom;beginRoom=function(){shots.length=zones.length=delays.length=summons.length=channels.length=0;poisons.clear();slows.clear();shreds.clear();for(const id of newIds){cd[id]=0;age[id]=0}oldBegin();for(const id of newIds)dmg[get(id).name]=0;syncBrain()};
const oldForce=forceRoom;forceRoom=function(types,obs=[]){shots.length=zones.length=delays.length=summons.length=channels.length=0;poisons.clear();slows.clear();shreds.clear();for(const id of newIds){cd[id]=0;age[id]=0}oldForce(types,obs);for(const id of newIds)dmg[get(id).name]=0;syncBrain()};

const g3Hud=hud;hud=function(){const desired=Array.isArray(brain.skills)?brain.skills.slice(0,3):[];g3Hud();if(desired.some(isNew))brain.skills=desired;const cards=[skillEls.Slash,skillEls.Whirlwind,skillEls.Slam];cards.forEach((el,i)=>{const id=brain.skills[i];if(el&&id&&get(id)){el.querySelector('.name').textContent=`${get(id).name.toUpperCase()} • LV ${level(id)}`}});const chip=document.getElementById('skillProgressChip');if(chip){const n=nextUnlock();chip.textContent=n?`SKILLS ${ownedIds().length}/${allIds.length} • NEXT ${get(n.id).name.toUpperCase()} @ LV ${n.monsterLevel}`:`SKILLS ${allIds.length}/${allIds.length} • COLLECTION COMPLETE`}};

let filter='all';
function renderLab(){const panel=document.getElementById('skillLabPanel'),card=panel?.querySelector('.g3card');if(!card)return;const load=syncBrain(),n=nextUnlock(),rows=allIds.filter(id=>filter==='all'||(get(id).tags||[]).some(t=>t.toLowerCase()===filter)||String(get(id).role||'').toLowerCase().includes(filter));card.innerHTML=`<div class="g3head"><div><h2>30-SKILL ARSENAL</h2><div class="g3sub">Build a three-skill Brain from genuinely different combat tools.</div></div><button id="g4close">CLOSE</button></div><div class="g4collection"><b>COLLECTION ${ownedIds().length}/${allIds.length}</b> • ${n?`Next: ${get(n.id).name} from monster level ${n.monsterLevel}+`:'All 30 discovered'}<br><span>${state.drops} Goal 04 drops • ${state.upgrades} upgrades</span></div><div class="g4load">${[0,1,2].map(i=>`<div class="g4slot"><small>PRIORITY ${i+1}</small><b>${load[i]?get(load[i]).name:'EMPTY'}</b><span>${load[i]?'Lv '+level(load[i]):'Choose an owned skill'}</span>${load[i]?`<button data-clear="${i}">CLEAR</button>`:''}</div>`).join('')}</div><div class="g4toolbar">${['all','melee','projectile','spell','minion','control','movement','dot'].map(k=>`<button class="g4filter ${filter===k?'on':''}" data-filter="${k}">${k.toUpperCase()}</button>`).join('')}</div><div class="g4grid">${rows.map(id=>{const d=get(id),o=owned(id),slot=load.indexOf(id),e=effective(id),identity=d.identity||({Slash:'Heavy single-target melee with cleave and execute masteries.',Whirlwind:'Sustained point-blank spin that rewards staying in the pack.',Slam:'Slow, enormous impact with stagger and aftershock.',Firebolt:'Direct ranged fire projectile with ignite and splash.',Dash:'Gap-closing melee strike with recovery.',Scorch:'Persistent ground burn that ramps heat.',Wisp:'Temporary ranged fire minion with chaining.'}[id]||d.role||'Core Goal 03 skill.');return`<div class="g4skill ${o?'':'locked'}"><div style="display:flex;justify-content:space-between;gap:5px"><h3>${d.name}</h3><b class="${isNew(id)?'g4new':''}">${o?'LV '+level(id):'LOCKED'}</b></div><div>${(d.tags||[]).map(t=>`<span class="g4tag">${t}</span>`).join('')}</div><div class="g4identity">${identity}</div><div class="g4meta">${d.role||'Goal 03 core'} • ${o?`DMG ${Math.round(e.baseDamage||0)} • CD ${(e.cooldown||0).toFixed(2)}s`:`Drops from monster level ${unlockDepth(id)}+`}</div>${o?`<div class="g4equip">${[0,1,2].map(i=>`<button data-equip="${id}" data-slot="${i}" class="${slot===i?'on':''}">${slot===i?'P'+(i+1)+' ✓':'P'+(i+1)}</button>`).join('')}</div>`:''}</div>`}).join('')}</div>`;card.querySelector('#g4close').onclick=()=>{panel.style.display='none';pausedForBrain=false;last=performance.now()};card.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(b.dataset.equip,+b.dataset.slot));card.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>equip(null,+b.dataset.clear));card.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderLab()})}
const labBtn=document.getElementById('skillLabBtn');if(labBtn)labBtn.onclick=()=>{pausedForBrain=true;document.getElementById('skillLabPanel').style.display='block';renderLab()};
syncBrain();hud();

window.DopamineGoal4=Object.freeze({version:'Goal 04 Runtime v1.0',ids:()=>[...allIds],newIds:()=>[...newIds],get,owned,level,effective,grant,renderLab,debugUnlockAll(lv=10){for(const id of newIds)state.owned[id]=clamp(lv,1,20);save();syncBrain();return ownedIds()},debugReset(){state=fresh();if(!goal4Mode)localStorage.removeItem(KEY);syncBrain();return true},debugState:()=>JSON.parse(JSON.stringify(state)),effects:()=>({shots:shots.length,zones:zones.length,summons:summons.length,poisons:poisons.size})});
})();
